import json,struct,glob
out=[]
out.append("== Busin0 LIBRARY / Item Compendium (アイテム図鑑) — JP source map ==")
out.append("")
out.append("TITLE (UL, ornate, pre-rendered strip): ライブラリー  [Library]")
out.append("SUBTITLE (UR, red banner strip):        アイテム図鑑  [Item Compendium]")
out.append("")
out.append("CATEGORY MENU (left, 5 rows, each + yellow NEW tag) — PRE-RENDERED STRIPS (not glyph stream):")
out.append("  cat0  アイテム図鑑   Item Compendium    glyphids ar/i/te/mu/zu/kan")
out.append("  cat1  人物名鑑       Character Directory")
out.append("  cat2  用語辞典       Glossary")
out.append("  cat3  冒険の手引き   Adventurer's Guide")
out.append("  cat4  書物リスト     Book List")
out.append("")
out.append("FOOTER (help): R2+↑↓:早送り  [R2+Up/Down: Fast-forward]")
out.append("")
out.append("BODY/CONTENT TEXT (right panel) -> R2654 (2654_type44.raw) msg-glyph BE-u16 groups.")
out.append("R2654 sub10 (off 0xA8F0 sz 0x3972, 47 FFFF groups) = 冒険の手引き Adventurer's Guide body.")
out.append("Sample (compendium item-intro group): 武器・扉番・アクセサリーから魔法腕… これら全てはアイテムという名前で…")
open('_library_jp_sourcemap.txt','w',encoding='utf-8').write('\n'.join(out))
print('wrote _library_jp_sourcemap.txt')
