#!/usr/bin/env python3
"""Analyze 4 GS dumps from 2026-06-05 18:56 to determine original vs patched,
then parse keyboard draw calls for F/M cell analysis."""

import struct
from pathlib import Path
from collections import defaultdict

import zstandard as zstd

SNAPS_DIR = Path(r"C:/Users/Fabian Trunz/OneDrive - Berner Fachhochschule/Dokumente/PCSX2/snaps")

DUMP_FILES = [
    "Busin 0 - Wizardry Alternative Neo_SLPM-65378_20260605185636.gs.zst",
    "Busin 0 - Wizardry Alternative Neo_SLPM-65378_20260605185641.gs.zst",
    "Busin 0 - Wizardry Alternative Neo_SLPM-65378_20260605185644.gs.zst",
    "Busin 0 - Wizardry Alternative Neo_SLPM-65378_20260605185648.gs.zst",
]

PSM_NAMES = {
    0x00: "PSMCT32", 0x01: "PSMCT24", 0x02: "PSMCT16", 0x0A: "PSMCT16S",
    0x13: "PSMT8", 0x14: "PSMT4", 0x1B: "PSMT8H",
    0x24: "PSMT4HL", 0x2C: "PSMT4HH",
}


def parse_tex0(val):
    return {
        'tbp0': val & 0x3FFF, 'tbw': (val >> 14) & 0x3F,
        'psm': (val >> 20) & 0x3F,
        'tw': 1 << ((val >> 26) & 0xF), 'th': 1 << ((val >> 30) & 0xF),
        'cbp': (val >> 37) & 0x3FFF, 'cpsm': (val >> 51) & 0xF,
        'csa': (val >> 56) & 0x1F, 'cld': (val >> 61) & 7,
    }


def load_gs_dump(path):
    dctx = zstd.ZstdDecompressor()
    with open(path, 'rb') as f:
        return dctx.decompress(f.read(), max_output_size=512 * 1024 * 1024)


def extract_vram(data):
    """Extract the initial VRAM state (4MB) from a GS dump.

    GS dump layout:
      4 bytes: fake CRC
      4 bytes: header_total_size
      header_total_size bytes: state header (includes state_version, state_size, ...)
      state_size bytes: GS internal state
      0x2000 bytes (8192): registers
      Then: VRAM (4MB) should be embedded in the state

    Actually, the GS dump state includes VRAM. Let's parse the header properly.
    """
    pos = 0
    fake_crc = struct.unpack_from("<I", data, pos)[0]; pos += 4
    header_total_size = struct.unpack_from("<I", data, pos)[0]; pos += 4

    # Parse the 9-int header
    hdr = struct.unpack_from("<9I", data, pos)
    state_version = hdr[0]
    state_size = hdr[1]

    print(f"    fake_crc=0x{fake_crc:08X}, header_total_size={header_total_size}")
    print(f"    state_version={state_version}, state_size={state_size}")

    # The state data starts after the 8-byte prefix + header
    data_start = 8 + header_total_size
    # State data: data[data_start : data_start + state_size]
    # Then 0x2000 bytes of register data
    # Then the GIF packets begin

    # VRAM is inside the state data. For PCSX2 GS dumps, VRAM (4MB) is typically
    # at the beginning of the state data or after some register state.
    # Let's check - state_size should be >= 4MB if it contains VRAM

    vram_size = 4 * 1024 * 1024  # 4MB

    print(f"    data_start={data_start}, state covers data[{data_start}:{data_start+state_size}]")
    print(f"    state_size={state_size} ({state_size/1024/1024:.1f} MB)")

    if state_size >= vram_size:
        # VRAM is likely at the end of the state data
        # Or at a specific offset within it
        # Try: VRAM at the start of state data (common for PCSX2 GS dumps)
        vram_candidate = data[data_start : data_start + vram_size]
        return vram_candidate, data_start

    # If state is smaller, VRAM might be right after the header
    # Try different offsets
    print(f"    WARNING: state_size < 4MB, trying alternative VRAM locations")
    return None, 0


def check_r1272_vram(vram, label=""):
    """Check if R1272 font atlas at TBP0=0x3000 contains English or Japanese glyphs.

    R1272 is PSMT4, 256x512, TBW=4
    TBP0=0x3000 -> byte offset = 0x3000 * 256 = 0x300000 = 3,145,728

    For PSMT4: each byte holds 2 pixels (4 bits each)
    The texture is 256 wide x 512 tall

    In the English patched version, positions 0-94 are ASCII glyphs
    In the Japanese original, these would be different (kanji/kana)

    Let's check a region that would differ - the very first few glyph cells.
    Each glyph cell is roughly 16x16 pixels.

    Actually, a simpler check: look at the raw byte patterns. The English atlas
    has been regenerated by generate_font_atlas.py with different glyph shapes.
    Let's just hash a region and compare.
    """
    # TBP0=0x3000 in PSMT4 with TBW=4
    # Block address 0x3000 = 12288 blocks * 256 bytes/block = 3,145,728 bytes
    tbp_offset = 0x3000 * 256

    if tbp_offset + 8192 > len(vram):
        print(f"    {label}: TBP0=0x3000 offset {tbp_offset} exceeds VRAM size {len(vram)}")
        return "UNKNOWN"

    # Read first 4KB of the font region
    region = vram[tbp_offset : tbp_offset + 4096]
    nonzero = sum(1 for b in region if b != 0)

    # Read a broader sample
    region_8k = vram[tbp_offset : tbp_offset + 8192]

    # Hash to compare between dumps
    import hashlib
    h = hashlib.md5(region_8k).hexdigest()

    # Check specific byte patterns
    # The first 64 bytes
    first_bytes = region[:64]

    print(f"    {label}: R1272 region @ 0x{tbp_offset:X}: {nonzero}/4096 non-zero bytes, hash={h[:16]}")
    print(f"    First 32 bytes: {first_bytes[:32].hex()}")

    return h


def check_r2840_vram(vram, label=""):
    """Check TBP0=0x2840 (keyboard atlas) in VRAM."""
    tbp_offset = 0x2840 * 256

    if tbp_offset + 4096 > len(vram):
        print(f"    {label}: TBP0=0x2840 offset exceeds VRAM")
        return "UNKNOWN"

    region = vram[tbp_offset : tbp_offset + 4096]
    nonzero = sum(1 for b in region if b != 0)

    import hashlib
    h = hashlib.md5(region).hexdigest()

    print(f"    {label}: Keyboard region @ 0x{tbp_offset:X}: {nonzero}/4096 non-zero, hash={h[:16]}")
    return h


def parse_gs_draws(data):
    """Parse GS dump draw calls, return list of draws."""
    pos = 0
    pos += 4  # fake_crc
    header_total_size = struct.unpack_from("<I", data, pos)[0]
    pos += 4
    hdr = struct.unpack_from("<9I", data, pos)
    state_version, state_size = hdr[0], hdr[1]

    data_start = 8 + header_total_size
    packets_start = data_start + state_size + 0x2000

    cur_tex0 = None
    cur_xyoffset = (0, 0)
    cur_frame_fbp = 0
    all_draws = []
    draw_seq = 0

    pos = packets_start
    vsync_count = 0

    while pos < len(data) and vsync_count < 4:  # parse up to 4 vsyncs
        if pos >= len(data):
            break
        tag = data[pos]; pos += 1

        if tag == 0:  # Transfer
            if pos + 5 > len(data): break
            path_idx = data[pos]; pos += 1
            size = struct.unpack_from("<I", data, pos)[0]; pos += 4
            if pos + size > len(data): break
            gif_data = data[pos:pos + size]
            pos += size

            gpos = 0
            while gpos + 16 <= len(gif_data):
                lo = struct.unpack_from("<Q", gif_data, gpos)[0]
                hi = struct.unpack_from("<Q", gif_data, gpos + 8)[0]
                nloop = lo & 0x7FFF
                eop = (lo >> 15) & 1
                pre = (lo >> 46) & 1
                prim_data = (lo >> 47) & 0x7FF
                flg = (lo >> 58) & 3
                nreg = (lo >> 60) & 0xF
                if nreg == 0: nreg = 16
                gpos += 16

                reg_ids = [(hi >> (r * 4)) & 0xF for r in range(nreg)]

                if flg == 0:  # PACKED
                    verts = []
                    uvs = []
                    tme = 0
                    prim_type = 6

                    if pre:
                        prim_type = prim_data & 0x7
                        tme = (prim_data >> 4) & 1

                    for loop in range(nloop):
                        for ri, reg_id in enumerate(reg_ids):
                            if gpos + 16 > len(gif_data): break
                            plo = struct.unpack_from("<Q", gif_data, gpos)[0]
                            phi = struct.unpack_from("<Q", gif_data, gpos + 8)[0]

                            if reg_id == 0x0E:  # A+D
                                reg_addr = phi & 0xFF
                                if reg_addr in (0x06, 0x07):
                                    cur_tex0 = parse_tex0(plo)
                                elif reg_addr == 0x00:
                                    prim_type = plo & 0x7
                                    tme = (plo >> 4) & 1
                                elif reg_addr in (0x4C, 0x4D):
                                    cur_frame_fbp = plo & 0x1FF
                                elif reg_addr == 0x18:
                                    cur_xyoffset = (plo & 0xFFFF, (plo >> 32) & 0xFFFF)
                                elif reg_addr in (0x04, 0x05, 0x0C, 0x0D):
                                    x = plo & 0xFFFF; y = (plo >> 16) & 0xFFFF
                                    verts.append((x, y))
                                elif reg_addr == 0x03:
                                    u = plo & 0x3FFF; v = (plo >> 16) & 0x3FFF
                                    uvs.append((u, v))
                            elif reg_id == 0x05:  # XYZ2
                                x = plo & 0xFFFF; y = (plo >> 32) & 0xFFFF
                                verts.append((x, y))
                            elif reg_id == 0x04:  # XYZF2
                                x = plo & 0xFFFF; y = (plo >> 32) & 0xFFFF
                                verts.append((x, y))
                            elif reg_id == 0x03:  # UV
                                u = plo & 0x3FFF; v = (plo >> 32) & 0x3FFF
                                uvs.append((u, v))
                            elif reg_id == 0x00:  # PRIM
                                prim_type = plo & 0x7
                                tme = (plo >> 4) & 1
                            gpos += 16

                    if verts and cur_tex0:
                        all_draws.append({
                            'seq': draw_seq, 'tex0': dict(cur_tex0),
                            'prim': prim_type, 'tme': tme,
                            'verts': verts, 'uvs': uvs,
                            'xyoff': cur_xyoffset, 'fbp': cur_frame_fbp,
                        })
                        draw_seq += 1

                elif flg == 1:  # REGLIST
                    verts = []
                    uvs = []
                    tme = 0
                    prim_type = 6

                    if pre:
                        prim_type = prim_data & 0x7
                        tme = (prim_data >> 4) & 1

                    total_regs = nloop * nreg
                    for i in range(total_regs):
                        if gpos + 8 > len(gif_data): break
                        reg_id = reg_ids[i % nreg]
                        rd = struct.unpack_from("<Q", gif_data, gpos)[0]

                        if reg_id == 0x00:
                            prim_type = rd & 0x7
                            tme = (rd >> 4) & 1
                        elif reg_id == 0x05:
                            x = rd & 0xFFFF; y = (rd >> 16) & 0xFFFF
                            verts.append((x, y))
                        elif reg_id == 0x04:
                            x = rd & 0xFFFF; y = (rd >> 16) & 0xFFFF
                            verts.append((x, y))
                        elif reg_id == 0x0D:
                            x = rd & 0xFFFF; y = (rd >> 16) & 0xFFFF
                            verts.append((x, y))
                        elif reg_id == 0x03:
                            u = rd & 0x3FFF; v = (rd >> 16) & 0x3FFF
                            uvs.append((u, v))
                        gpos += 8

                    if (total_regs % 2) == 1:
                        gpos += 8

                    if verts and cur_tex0:
                        all_draws.append({
                            'seq': draw_seq, 'tex0': dict(cur_tex0),
                            'prim': prim_type, 'tme': tme,
                            'verts': verts, 'uvs': uvs,
                            'xyoff': cur_xyoffset, 'fbp': cur_frame_fbp,
                        })
                        draw_seq += 1

                elif flg == 2:  # IMAGE
                    gpos += nloop * 16

                if eop: break

        elif tag == 1:
            if pos + 1 > len(data): break
            pos += 1; vsync_count += 1
        elif tag == 2:
            if pos + 4 > len(data): break
            size = struct.unpack_from("<I", data, pos)[0]; pos += 4
        elif tag == 3:
            if pos + 0x2000 > len(data): break
            pos += 0x2000
        else:
            break

    return all_draws


def analyze_keyboard(all_draws):
    """Detailed keyboard draw analysis."""
    kbd_draws = [d for d in all_draws if d['tex0']['tbp0'] == 0x2840]
    if not kbd_draws:
        return None

    # Deduplicate by UV coordinates (same sprite drawn twice for XYZ3+XYZ2)
    seen_uvs = set()
    unique_draws = []
    for d in kbd_draws:
        if d['uvs']:
            key = tuple(d['uvs'][0])
            if key not in seen_uvs:
                seen_uvs.add(key)
                unique_draws.append(d)

    grid = []
    for d in unique_draws:
        ox, oy = d['xyoff']
        if len(d['verts']) >= 2 and len(d['uvs']) >= 2:
            x0 = (d['verts'][0][0] - ox) / 16.0
            y0 = (d['verts'][0][1] - oy) / 16.0
            u0 = d['uvs'][0][0] / 16.0
            v0 = d['uvs'][0][1] / 16.0

            cell_col = int(round(u0)) // 16
            cell_row = int(round(v0)) // 16
            cell_idx = cell_row * 16 + cell_col

            grid.append({
                'sx': x0, 'sy': y0,
                'u0': u0, 'v0': v0,
                'cell_col': cell_col, 'cell_row': cell_row,
                'cell_idx': cell_idx,
            })

    cell_indices = sorted(set(g['cell_idx'] for g in grid))
    has_F = 38 in cell_indices
    has_M = 45 in cell_indices

    # Group by screen Y
    rows = defaultdict(list)
    for g in grid:
        row_key = round(g['sy'] / 5) * 5
        rows[row_key].append(g)

    return {
        'total_raw_draws': len(kbd_draws),
        'unique_draws': len(unique_draws),
        'cell_indices': cell_indices,
        'has_F': has_F,
        'has_M': has_M,
        'grid': grid,
        'rows': dict(rows),
        'tex0_configs': list(set(
            (d['tex0']['tbp0'], d['tex0']['tbw'], d['tex0']['psm'],
             d['tex0']['tw'], d['tex0']['th'], d['tex0']['cbp'])
            for d in kbd_draws
        )),
    }


def main():
    print("=" * 90)
    print("ANALYSIS OF 4 GS DUMPS FROM 2026-06-05 18:56")
    print("Goal: Determine original vs patched, then compare keyboard F/M draws")
    print("=" * 90)

    vram_hashes = {}
    kbd_results = {}
    all_cell_sets = {}

    for i, fname in enumerate(DUMP_FILES):
        path = SNAPS_DIR / fname
        ts = fname.split("_")[-1].replace(".gs.zst", "")
        label = f"Dump {i+1} ({ts})"

        print(f"\n{'='*80}")
        print(f"{label}")
        print(f"{'='*80}")

        # Decompress
        data = load_gs_dump(path)
        print(f"  Decompressed size: {len(data):,} bytes")

        # Extract VRAM
        vram, vram_start = extract_vram(data)
        if vram:
            print(f"  VRAM extracted: {len(vram):,} bytes from offset {vram_start}")

            # Check R1272 font atlas at TBP0=0x3000
            r1272_hash = check_r1272_vram(vram, "R1272")
            vram_hashes[label] = r1272_hash

            # Check keyboard atlas at TBP0=0x2840
            r2840_hash = check_r2840_vram(vram, "R2840")
        else:
            print(f"  WARNING: Could not extract VRAM")

        # Parse draw calls
        all_draws = parse_gs_draws(data)
        print(f"\n  Total draw calls parsed: {len(all_draws)}")

        # Summary of all TBP0 values used
        tbp0_counts = defaultdict(int)
        for d in all_draws:
            tbp0_counts[d['tex0']['tbp0']] += 1

        print(f"  TBP0 usage summary:")
        for tbp0 in sorted(tbp0_counts.keys()):
            psm = None
            for d in all_draws:
                if d['tex0']['tbp0'] == tbp0:
                    psm = d['tex0']['psm']
                    break
            psm_name = PSM_NAMES.get(psm, f"0x{psm:02X}") if psm is not None else "?"
            print(f"    TBP0=0x{tbp0:04X}: {tbp0_counts[tbp0]} draws ({psm_name})")

        # Keyboard analysis
        kbd = analyze_keyboard(all_draws)
        if kbd:
            kbd_results[label] = kbd
            all_cell_sets[label] = set(kbd['cell_indices'])

            print(f"\n  KEYBOARD DRAW ANALYSIS (TBP0=0x2840):")
            print(f"    Raw draws: {kbd['total_raw_draws']}, Unique (by UV): {kbd['unique_draws']}")
            print(f"    Cell 38 (F): {'PRESENT' if kbd['has_F'] else 'MISSING'}")
            print(f"    Cell 45 (M): {'PRESENT' if kbd['has_M'] else 'MISSING'}")
            print(f"    All cell indices: {kbd['cell_indices']}")
            print(f"    TEX0 configs: {kbd['tex0_configs']}")

            # Print rows with detail
            print(f"\n    Grid rows (sorted by Y):")
            for row_y in sorted(kbd['rows'].keys()):
                row_cells = kbd['rows'][row_y]
                row_cells.sort(key=lambda g: g['sx'])
                cell_str = " ".join(
                    f"{g['cell_idx']:3d}" + (f"({chr(ord('A')+g['cell_idx']-33)})" if 33 <= g['cell_idx'] <= 58 else "")
                    for g in row_cells
                )
                print(f"      Y~{row_y:4.0f}: {cell_str}")

            # Check spacing in rows where F/M should appear
            for row_y in sorted(kbd['rows'].keys()):
                row_cells = sorted(kbd['rows'][row_y], key=lambda g: g['sx'])
                cells_in_row = [g['cell_idx'] for g in row_cells]

                # Row with A-J (should have F=38)
                if 33 in cells_in_row and 37 in cells_in_row:
                    print(f"\n    ** Row containing A-E (Y~{row_y:.0f}) spacing analysis:")
                    for j in range(len(row_cells)):
                        g = row_cells[j]
                        spacing = f"  gap={g['sx'] - row_cells[j-1]['sx']:.0f}" if j > 0 else ""
                        letter = chr(ord('A') + g['cell_idx'] - 33) if 33 <= g['cell_idx'] <= 58 else f"#{g['cell_idx']}"
                        print(f"      X={g['sx']:6.1f}  cell={g['cell_idx']:3d} ({letter}){spacing}")

                    # Check for gap where F should be
                    xs = [(g['sx'], g['cell_idx']) for g in row_cells]
                    for j in range(len(xs)-1):
                        if xs[j][1] == 37 and xs[j+1][1] == 39:
                            gap = xs[j+1][0] - xs[j][0]
                            print(f"      *** GAP between E(37) and G(39): {gap:.0f}px (normal ~24px)")

                # Row with K-T (should have M=45)
                if 43 in cells_in_row and 44 in cells_in_row:
                    print(f"\n    ** Row containing K-L (Y~{row_y:.0f}) spacing analysis:")
                    for j in range(len(row_cells)):
                        g = row_cells[j]
                        spacing = f"  gap={g['sx'] - row_cells[j-1]['sx']:.0f}" if j > 0 else ""
                        letter = chr(ord('A') + g['cell_idx'] - 33) if 33 <= g['cell_idx'] <= 58 else f"#{g['cell_idx']}"
                        print(f"      X={g['sx']:6.1f}  cell={g['cell_idx']:3d} ({letter}){spacing}")

                    for j in range(len(xs)-1):
                        xs2 = [(g['sx'], g['cell_idx']) for g in row_cells]
                        if xs2[j][1] == 44 and xs2[j+1][1] == 46:
                            gap = xs2[j+1][0] - xs2[j][0]
                            print(f"      *** GAP between L(44) and N(46): {gap:.0f}px (normal ~24px)")

        else:
            print(f"\n  No TBP0=0x2840 keyboard draws found in this dump")

    # ===== COMPARISON =====
    print(f"\n\n{'='*90}")
    print("COMPARISON ACROSS ALL 4 DUMPS")
    print("=" * 90)

    # VRAM hash comparison to identify original vs patched
    print("\nR1272 VRAM HASHES (font atlas at TBP0=0x3000):")
    unique_hashes = set(vram_hashes.values())
    for label, h in vram_hashes.items():
        print(f"  {label}: {h[:16]}")

    if len(unique_hashes) == 1:
        print(f"\n  ALL DUMPS HAVE IDENTICAL R1272 VRAM -> ALL from same build")
        print(f"  Since screenshots show English UI, ALL are from PATCHED build")
    elif len(unique_hashes) > 1:
        # Group by hash
        hash_groups = defaultdict(list)
        for label, h in vram_hashes.items():
            hash_groups[h].append(label)
        print(f"\n  FOUND {len(unique_hashes)} DISTINCT R1272 patterns:")
        for h, labels in hash_groups.items():
            print(f"    Hash {h[:16]}: {labels}")
        print(f"  Different hashes = different builds (original vs patched)")

    # Keyboard cell comparison
    print("\nKEYBOARD CELL COMPARISON:")
    if kbd_results:
        for label, kbd in kbd_results.items():
            print(f"  {label}: F={'YES' if kbd['has_F'] else 'NO'}, M={'YES' if kbd['has_M'] else 'NO'}, cells={len(kbd['cell_indices'])}")

        # Cross-compare cell sets
        labels = list(all_cell_sets.keys())
        for i in range(len(labels)):
            for j in range(i+1, len(labels)):
                s1 = all_cell_sets[labels[i]]
                s2 = all_cell_sets[labels[j]]
                if s1 == s2:
                    print(f"  {labels[i]} vs {labels[j]}: IDENTICAL cells")
                else:
                    only1 = sorted(s1 - s2)
                    only2 = sorted(s2 - s1)
                    if only1:
                        print(f"  Only in {labels[i]}: {only1}")
                    if only2:
                        print(f"  Only in {labels[j]}: {only2}")
    else:
        print("  No keyboard draws found in any dump!")

    # Final verdict
    print(f"\n{'='*90}")
    print("VERDICT")
    print("=" * 90)

    all_same_vram = len(unique_hashes) == 1
    any_has_F = any(kbd.get('has_F', False) for kbd in kbd_results.values())
    any_has_M = any(kbd.get('has_M', False) for kbd in kbd_results.values())

    if all_same_vram:
        print("All 4 dumps are from the SAME build (identical R1272 VRAM).")
        print("Based on screenshots showing English UI, all are from the PATCHED build.")
        print("CANNOT determine original Japanese behavior from these dumps alone.")
    else:
        print("Dumps are from DIFFERENT builds - can compare original vs patched!")

    print(f"\nF (cell 38) drawn in any dump: {'YES' if any_has_F else 'NO'}")
    print(f"M (cell 45) drawn in any dump: {'YES' if any_has_M else 'NO'}")


if __name__ == '__main__':
    main()
