#!/usr/bin/env python3
"""
Fix 649 entries in batch_01.json for resource R1196 that have Japanese
mixed into their English translations.

Translations derived from:
1. guide_full_text.txt reference (same story, professionally translated)
2. Context from surrounding properly-translated entries in batch_01.json
3. English vocabulary hints present in the corrupted english field
4. Knowledge of Wizardry: Busin 0 story/characters
"""

import json
import sys

def has_japanese(text):
    return any(ord(c) > 127 for c in text)

def build_translation_map():
    t = {}

    # ============================================================
    # SCENE: Zel explains the trial / labyrinth purpose (179-213)
    # Characters: Zel (knight commander), Princess Oriana
    # Context: The labyrinth was a test to find a warrior to defeat The Devourer
    # ============================================================
    t[179] = "If this plan fails, / not only Duhan but / all of Venoa will perish."
    t[180] = "However, you / were born."
    t[181] = "His Majesty barely / made it in time."
    t[182] = "A warrior capable / of defeating The / Devourer was created."
    t[183] = "You must have things / to say. But please / know this at least."
    t[184] = "Above all else, / the gods needed one / who could defeat"
    t[185] = "The Devourer. And / that one will lead / Duhan's future."
    t[186] = "You truly have / that quality."
    t[187] = "Zel wore a smile / tinged with sadness."
    t[188] = "I too shall head / to the labyrinth."
    t[189] = "A mere nobody at / the Battle of Banquo / has survived this long."
    t[190] = "You wouldn't know, / but His Majesty and / I have been frozen"
    t[191] = "in time since / Banquo. Where our / comrades perished!"
    t[192] = "I know what His / Majesty is trying / to seal away."

    # Princess Oriana speaks (uses 余 = royal "I")
    t[193] = "At times like these, / I wish I too had / the strength to help!"
    t[194] = "I feel ashamed of / these arms that can / only rely on others."
    t[195] = "The only thing / I can offer / is this:"
    t[196] = "This brooch I / received. I hope it / may be of some use."
    t[197] = "It is said among / the elves to ward / off evil magic."
    t[198] = "The princess took / a beautiful brooch / from her garment and"
    t[199] = "handed it over. / You received the / Princess's Brooch."
    t[200] = "A dazzling light / burst forth from / the Princess's Brooch,"
    t[201] = "and an overwhelming / surge of power / flowed into you."
    t[202] = "An Identification / Bracelet shone with / light, meant to end"
    t[203] = "the suffering. You / obtained Allied Art."

    t[205] = "It is the same / voice I heard in / my dream in the"
    t[206] = "labyrinth! It feels / so nostalgic, it / almost brings me"
    t[207] = "to tears! I believe / the spell that / befell us is deeply"
    t[208] = "connected to the / past. Father said / Duhan is cursed."
    t[209] = "This spell has been / going on far longer / than any of us"
    t[210] = "realize! The princess / stepped forward and / firmly grasped"
    t[211] = "your hand. If anyone / can end this spell, / it can only be you."
    t[213] = "I can only return / to the castle, but / I pray for your"

    # ============================================================
    # SCENE: Castle - Bergran and King Ortrud (214-294)
    # ============================================================
    t[214] = "safe return. You / were led to a room / and greeted by"
    t[215] = "Bergran. Just now, / I received a report / from Zel's unit."
    t[216] = "It seems you found / His Majesty's / keepsake. Thank you."
    t[217] = "I intend to deploy / an investigation / team at once to"
    t[218] = "shed light on this / matter. Now then, / His Majesty awaits"
    t[219] = "you. As Bergran / was about to escort / you to the king,"
    t[220] = "a hoarse voice / suddenly rang / through the room."
    t[221] = "\"Long ago, the King / of Sepoy said:\""
    t[222] = "\"While you still / live, look to the / future and obtain"
    t[223] = "the holy sword.\" / \"Wise indeed, if not / for all the soldiers"
    t[224] = "sacrificed.\" A / cloaked figure crept / past the guards."
    t[225] = "What an outrage!"
    t[226] = "What are the guards / doing?!"
    t[227] = "Are you saying no / one noticed him / coming all this way?"
    t[228] = "Throw him out / at once!"
    t[229] = "\"Never mind, / let him through.\""
    t[230] = "\"This is Grand / Magician Wezbel. / No one here can"
    t[231] = "stop him.\" King / Ortrud spoke to the / guards who rushed in."
    t[232] = "Wezbel, a rune / knight of Gilten, / was renowned for"
    t[233] = "his speed. The / magicians of old / Irikia could move"
    t[234] = "mountains with / their power. But / they are all dead."
    t[235] = "That woman killed / them! The great / kingdom no longer"
    t[236] = "even has a record / of existing. Do you / understand what I"
    t[237] = "am saying, Ortrud? / Why would I know / what Grand Magician"
    t[238] = "Wezbel thinks? / I am not that / sharp."
    t[239] = "But you did not / come here just / to visit."
    t[240] = "Grand Magician / Wezbel, what do you / want to say,"
    t[241] = "bringing up the / old kingdom? What / are you hiding,"
    t[242] = "Ortrud? Why has / Duhan survived?"
    t[243] = "All these years, / why has that woman / done nothing?"
    t[244] = "If she became / serious, she could / not only curse"
    t[245] = "your bloodline but / easily destroy / Duhan. You surely"
    t[246] = "know something. / Tell me."
    t[247] = "Enough, Wezbel. / Things are dire / enough as it is."
    t[248] = "My body has been / cursed, and my / people suffer more"
    t[249] = "each day. The / labyrinth has forced / us to restrict"
    t[250] = "trade. You have seen / how Duhan has / fallen into ruin."
    t[251] = "And you want me to / bear even more?"
    t[252] = "I simply want / to know."
    t[253] = "The one hailed as / the Holy King, who / brought peace to"
    t[254] = "war-torn Venoa -- / why now, when the / kingdom is under"
    t[255] = "threat, do you only / let the witch / roam free?"
    t[256] = "Deploy the knights! / I want to know why / you ignore their"
    t[257] = "plight. Wezbel, / enough pretense. / What do you want"
    t[258] = "to say? That I have / some secret pact / with Aurora?"
    t[259] = "That the witch / spares me, curses / my body, and"
    t[260] = "created the / labyrinth? Hmph, / ridiculous!"
    t[261] = "If you have time / for such nonsense, / join the strike force!"
    t[262] = "Hmm! So you're / saying it's fine if / I go myself?"
    t[263] = "What is there to / fear? Whoever slays / the witch becomes"
    t[264] = "Duhan's new hero. / And I look forward / to that. That is my"
    t[265] = "only wish. Very / well, I shall gather / comrades and enter"

    # Zel rushes in (266-282)
    t[266] = "the labyrinth. Zel, / who had been watching / hurried over."
    t[267] = "Zel: Your Majesty, / urgent news!"
    t[268] = "Lord Webster has / entered the labyrinth / with the Langobalt"
    t[269] = "training corps. / What shall we do?"
    t[270] = "My, today is full / of surprises."
    t[271] = "And what prompted / Lord Webster to / act on his own?"
    t[272] = "His Majesty's / keepsake was found / in the labyrinth."
    t[273] = "Of course, that is / not the only reason, / I'm sure."
    t[274] = "He is a stubborn / old man who never / budges."
    t[275] = "You wouldn't know, / but no one in all / of Venoa can beat"
    t[276] = "him at chess. He / has extraordinary / resourcefulness."
    t[277] = "Managing the front / lines with one hand / while dealing with"
    t[278] = "the papal court / with the other. If / such a man raised"
    t[279] = "the battle flag, / everything must be / in place. Your"
    t[280] = "Majesty, what shall / we do? Pay it no / mind. Let things"
    t[281] = "proceed as they / have. We can only / wait, even if it"
    t[282] = "leads to our ruin. / Zel left in / silence."

    # Ortrud addresses adventurer (283-294)
    t[283] = "Ortrud, who had / been watching, / spoke quietly."
    t[284] = "Adventurer, what a / grand sight. People / of all kinds gather"
    t[285] = "in Duhan. The / righteous and the / wicked alike fight"
    t[286] = "for their dreams. / Some come to reclaim / what was lost."
    t[287] = "Others head to the / labyrinth to pursue / the unknown."
    t[288] = "Whatever they seek, / it all serves to / protect Duhan."
    t[289] = "Anyone is welcome. / If one who can / defeat Aurora"
    t[290] = "exists, I would / gladly give up / this throne."
    t[291] = "Ortrud stared at / you intently."
    t[292] = "Perhaps you are / the one."
    t[294] = "With a pained smile, / Ortrud walked away."

    # ============================================================
    # SCENE: Bergran's strategy room / briefing (295-411)
    # Based directly on guide_full_text.txt lines 22165-22280
    # ============================================================
    t[295] = "Upon entering the / castle, you were led / to a room like a"
    t[296] = "strategy hall. / King Ortrud sat / supported by an"
    t[297] = "attendant, looking / weary. The king / skipped formalities."
    t[298] = "Ortrud: Recently, / attacks on the / strike force have"
    t[299] = "grown frequent. / Some say adventurers / are posing as"
    t[300] = "knights to attack / them. When we must / unite against the"
    t[301] = "enemy, we cannot / ignore this. Tell / me, was it monsters"
    t[302] = "that attacked the / strike force? / [Yes] [Maybe not]"
    t[303] = "As I suspected -- / the work of monsters, / same as before!"
    t[304] = "Good grief, the / problems only mount."
    t[305] = "The escort knights / were all found dead / in the labyrinth."
    t[306] = "They must have / suffered greatly, / unable to even"
    t[307] = "avenge themselves. / Meanwhile, there are / unsavory rumors"
    t[308] = "about the knights -- / that all the strike / force attacks were"
    t[309] = "staged by knights. / You recalled the / strange wounds the"
    t[311] = "strike force woman / had. A knight has / many ways to kill"
    t[312] = "without such marks. / That leaves one / conclusion."
    t[313] = "Before the monsters / attacked, the strike / force clashed with"
    t[314] = "someone else. / Valuable intel."
    t[315] = "There are unsavory / rumors about the / knights lately."
    t[316] = "That all the strike / force attacks were / staged by the"
    t[317] = "knights. Absurd!"
    t[318] = "The king glared and / sighed deeply."
    t[319] = "How frustrating!"
    t[320] = "The witch's curse / causes this body / to wither day by"
    t[321] = "day. I can barely / walk. If only I / could go myself!"
    t[322] = "You there. Thank you / for your service."
    t[323] = "An attendant placed / a shining sword / before you."
    t[324] = "You received the / Magic Sword."
    t[325] = "Nothing special, / but it is imbued / with magic. It"
    t[326] = "should be useful. / Please accept it as / a token of thanks."
    t[327] = "Adventurer, may I / ask you something?"
    t[328] = "Why do you enter / the labyrinth?"
    t[329] = "For wealth? For / revenge? Or do you / fight without"
    t[330] = "reason? / [For wealth] / [For revenge]"

    # Response: "For wealth" (332-341)
    t[332] = "I once had nothing. / Born to a poor / family, I could"
    t[333] = "barely afford armor. / But looking back, / I had everything."
    t[334] = "Comrades I could / trust, dreams worth / risking my life"
    t[335] = "for. I became King / of Duhan and gained / wealth and revenge."
    t[336] = "But now, everything / I once had / is gone."
    t[337] = "As one who was once / an adventurer, / let me say this:"
    t[338] = "Find comrades you / can truly trust."
    t[339] = "Companions you can / rely on in battle / are worth more"
    t[340] = "than any fortune. / They watch your back / and give you"
    t[341] = "everything -- wealth, / revenge, dreams."

    # Response: "For revenge" (342-352)
    t[342] = "For revenge! I once / had nothing. Born / to a poor family,"
    t[343] = "I could barely / afford armor."
    t[344] = "But looking back, / I had everything."
    t[345] = "Comrades I could / trust, dreams worth / risking my life for."
    t[346] = "I became the King / of Duhan and gained / wealth and revenge."
    t[347] = "But now, everything / I once had / is gone."
    t[348] = "As one who was once / an adventurer, / let me say this:"
    t[349] = "Find comrades you / can trust from / the heart."
    t[350] = "Companions you can / rely on in battle / are worth more"
    t[351] = "than any fortune. / They watch your back / and give you"
    t[352] = "everything -- wealth, / revenge, dreams."

    # Response: "No reason" (353-356)
    t[353] = "Then let me say: / Find comrades you / can truly trust."
    t[354] = "Companions you can / rely on in battle / are worth more"
    t[355] = "than any fortune. / They watch your back / and give you"
    t[356] = "everything -- wealth, / revenge, dreams!"
    t[357] = "Ha, must be the / drink talking. I've / grown sentimental."
    t[358] = "That will be all / for today. The / servants should be"
    t[359] = "returning with / food soon. Ortrud / left, supported by"

    # Bergran meeting (360-411)
    t[360] = "an attendant. / Inside the castle, / you were led to"
    t[361] = "a strategy room. / Well-kept but / simple -- no fire,"
    t[362] = "no tapestries. / Bergran: Welcome. / Please, be at ease."
    t[363] = "Bergran placed a / stack of documents / on the table."
    t[364] = "Contracts and / reports, all sealed / with the king's crest."
    t[365] = "Duhan is facing / a dire crisis."
    t[366] = "The reason we watch / those entering the / city and gather"
    t[367] = "adventurers is / all because of / this. You know of"
    t[368] = "Karman's Labyrinth, / yes? Their numbers / are still small,"
    t[369] = "but monsters have / been emerging. What / we ask is for you"
    t[370] = "to enter the / labyrinth and slay / the witch behind"
    t[371] = "all this. Her name / is Aurora. The / personification of"
    t[372] = "evil, leading Duhan / to ruin. She cursed / all of Duhan and"

    # Aurora appears at the engagement ceremony (373-390)
    t[373] = "created the / labyrinth. It began / at the engagement"
    t[374] = "of Princess Oriana / and Lord Webster. / \"It has been a"
    t[375] = "while, Your / Majesty.\" A woman / with dazzling eyes"
    t[376] = "stepped forward. / \"Au-Aurora!\" / \"I hope you are"
    t[377] = "well.\" \"What did / you come for?!\" / The attendees"
    t[378] = "began to murmur. / Everyone knew that / fearsome name --"
    t[379] = "the immortal witch / who ruined many / kingdoms. \"How dare"
    t[380] = "you! Speak, what is / your wish?\" \"I wish / for this kingdom,"
    t[381] = "the Kingdom of / Duhan.\" A commotion / erupted. Everyone"
    t[382] = "watched in shock. / \"You want Duhan?\" / \"Yes.\" \"Insane?\""
    t[383] = "\"I only speak my / heart's desire.\" / Soldiers rushed"
    t[384] = "forward, but the / witch's gaze froze / them in place."
    t[385] = "\"Is that your / answer?\" \"Think / what you will.\""
    t[386] = "\"Then your body / shall wither and / you shall become"
    t[387] = "a wreck.\" The witch / left with a curse. / Soon after,"
    t[388] = "disasters plagued / the king's lineage."
    t[389] = "It became rumored / that the witch had / cursed the royal"
    t[390] = "bloodline."

    # Bergran continues (391-411)
    t[391] = "We must defeat / Aurora and lift / the curse as soon"
    t[392] = "as possible. Bring / us Aurora's head / and you will be"
    t[393] = "greatly rewarded. / Even crucial intel / would suffice."
    t[394] = "Will you join the / strike force?"
    t[395] = "If you defeat her, / the reward will be / even greater."
    t[396] = "Will you lend us / your strength?"
    t[397] = "Bergran showed you / a document sealed / with the royal"
    t[398] = "crest. The reward / was immense: a / vast tract of land,"
    t[399] = "the right to build / a castle, maintain / an army --"
    t[400] = "essentially your / own small kingdom."
    t[401] = "The kingdom's fate / depends on this / contract, so the"
    t[402] = "reward is enormous. / I shall head to / the labyrinth to"
    t[403] = "brief the others. / Please come along / when you are ready."
    t[404] = "Will you assist the / strike force? / [Yes] [No]"
    t[405] = "Excellent. Quick / decisions show good / leadership."
    t[406] = "Very well. If you / wish to help Duhan, / come see us."
    t[407] = "I will wait here."
    t[408] = "So, have you / decided? Will you / join the strike"
    t[409] = "force? Or will you / just tour the city / and leave?"
    t[410] = "Your help would / be most welcome."
    t[411] = "We are counting / on you."

    # ============================================================
    # SCENE: Girl at Vigger Shop / misc (436-439)
    # ============================================================
    t[436] = "Hmm, I see. Okay, / I'll have to change / the battle lineup."
    t[437] = "Right, no time to / waste. Don't blame / me if it goes wrong."
    t[438] = "Nooo~ Cheapskate!"
    t[439] = "\"It's a patient! / Please open / the gate!\""

    # ============================================================
    # SCENE: Karman Labyrinth emergency / wounded being evacuated (440-469)
    # Wezbel's soldier scene (old magician observing)
    # ============================================================
    t[440] = "Wounded were being / carried out of / Karman's Labyrinth."
    t[441] = "The medical tent / is this way! / Everyone, hurry!"
    t[442] = "The medics called / out to those / emerging from the"
    t[443] = "labyrinth, guiding / them to the tent. / The knights carried"
    t[444] = "stretchers covered / with white sheets. / The number of"
    t[445] = "wounded exceeded / ten in the brief / time you watched."
    t[446] = "\"Just a little / longer, hang in / there!\" The medic"
    t[447] = "called to the / wounded, but not / even a groan came"
    t[448] = "from under the / sheets. One of / the sheets slipped"
    t[449] = "off. The medic / quickly replaced it, / but beneath lay"
    t[450] = "a horribly / disfigured corpse. / \"Those are all"
    t[451] = "victims of Aurora.\" / An elderly mage / with a massive"
    t[452] = "staff stood among / the onlookers. / \"Pitiful souls."
    t[453] = "I do not grieve. / It is folly to / send unreliable"
    t[454] = "adventurers against / the witch. No matter / how battle-"
    t[455] = "hardened they are, / the result is the / same. Ordinary"
    t[456] = "mortals who fear / death cannot stand / against true evil."
    t[457] = "But I am different. / I know that witch."
    t[458] = "She stands atop / all evil, a / merciless destroyer"
    t[459] = "who seeks / destruction for / its own sake,"
    t[460] = "devoid of any / mercy. I met her / at the fortress"
    t[461] = "of Banquo, on a / battlefield strewn / with countless dead."
    t[462] = "Amidst that / unearthly carnage, / she stood there"
    t[463] = "smiling. I can / never forget."
    t[464] = "She began humming / a song of cursing / while smiling."
    t[465] = "Look at this! While / the suffering cry / out in agony,"
    t[466] = "where is God? / Probably lounging / in paradise!"
    t[467] = "Shameful! I could / only mutter words / of prayer, trying"
    t[468] = "my best. True evil / can shatter even / iron faith."
    t[469] = "Mere adventurers / cannot hope to / prevail.\" The old"

    # ============================================================
    # SCENE: Lute and Emilia rescue (470-500)
    # Elf girls who hid Princess Oriana from Webster
    # ============================================================
    t[470] = "mage walked away / sadly. \"Thank / you for rescuing"
    t[471] = "us!\" Out of the / darkness emerged / Lute and Emilia."
    t[472] = "Emilia: If you / hadn't been there, / the princess would"
    t[473] = "have been killed / by him. We cannot / thank you enough."
    t[474] = "You may have / noticed, but we've / been hiding the"
    t[475] = "princess all along. / Yes, to deceive / Lord Webster, we"
    t[476] = "faked her death. / We knew that Lord / Webster was after"
    t[477] = "the princess's / life. We saw him / receive secret"
    t[478] = "orders from the / Langobalt training / corps."
    t[479] = "To carry out his / plan, he needed / the living blood"
    t[480] = "of an elf. And / the princess has / that blood!"
    t[481] = "We told the king, / but he wouldn't / believe us."
    t[482] = "He just waved us / off, saying 'yes, / yes, I understand.'"
    t[483] = "So we decided / on our own to fake / the princess's"
    t[484] = "death using our / magic potions, to / fool whoever was"
    t[485] = "after her life. / We took the princess / into the labyrinth,"
    t[486] = "but it's dangerous / there. We wanted / to get her to"
    t[487] = "safety as soon as / possible. Now we / don't have to wear"
    t[488] = "those awful Orc / disguises anymore. / If we'd had to"
    t[489] = "keep it up, we / would've gone crazy. / We need to thank"
    t[490] = "you properly! / If you'd like, we / could help with"
    t[491] = "the fight against / Aurora. We're / pretty confident"
    t[492] = "in our magic. / Which of us should / be your companion?"
    t[493] = "Lute or me? / We have the same / abilities, so"
    t[494] = "either choice is / fine. Who will you / choose? [Lute]"
    t[495] = "[Emilia] Then I'll / head to the Guild / to register."
    t[496] = "Phew, what a / relief! I'll go / practice magic at"
    t[497] = "the castle. Lute / has been registered / at the Guild."
    t[498] = "Then I'll head / to the Guild to / register."
    t[499] = "Bummer! I'll go / practice magic with / Barbo the Orc."
    t[500] = "Emilia has been / registered at / the Guild."

    # ============================================================
    # SCENE: Iris arrives / conversation (501-530)
    # ============================================================
    t[501] = "Iris burst into / the room."
    t[502] = "\"So you are saying / that in exchange / for cooperating"
    t[503] = "with me, you want / me to take them to / the land of Sasan?\""
    t[504] = "\"That's right! / Sasan is totally / isolated from the"
    t[505] = "papal court and / every other nation / in Venoa.\""
    t[506] = "\"I see, that / explains it.\""
    t[508] = "\"Now I understand / why the escort / needs three people.\""

    # Bergran castle scene (508-530)
    t[508] = "Bergran came / walking from inside / the castle."
    t[509] = "Bergran: I heard / from Zel that you / recovered His"
    t[510] = "Majesty's keepsake. / Thank you. On / behalf of the late"
    t[512] = "Majesty, I thank / you. His Majesty / always thought of"
    t[513] = "you all, without / ever seeing his / own children, never"
    t[514] = "forgetting Duhan. / Look at this -- / His Majesty's will."
    t[515] = "Bergran handed / over the will."
    t[516] = "\"Bergran, my dear / friend. Since we met / on the battlefield,"
    t[517] = "you have been my / pride. You must / resent me. Why"
    t[518] = "don't I send the / knights into the / labyrinth? But"
    t[519] = "if you die, who / leads them? Who / protects Duhan"
    t[520] = "after The Devourer / is gone? Perhaps / as king, I had a"
    t[521] = "father's weakness. / Bergran, my last / wish: protect"
    t[522] = "Oriana and devote / your strength to / Duhan's future.\""
    t[524] = "Bergran solemnly / declared: \"Duhan's / Order pledges its"
    t[525] = "loyalty to you / and the late / Majesty!\" He placed"
    t[526] = "his armor before / you and made his / oath. Then, with"
    t[527] = "a mischievous / grin: \"His Majesty / would scold me, but"
    t[528] = "I'm always ready / for battle. If / you plan to face"
    t[529] = "the final fight, / please call on me. / As commander, I"
    t[530] = "must punish those / who harmed His / Majesty.\" Bergran"

    # Bergran registered / Orc message / Zel scene (530-567)
    t[531] = "has been registered / at the Guild. Upon / returning to town,"
    t[532] = "you found an Orc / loitering about. / Spotting you, the"
    t[533] = "Orc rushed over. / Orc: Oh, you're / finally out!"
    t[534] = "I've been waiting / for you to return!"
    t[535] = "The princess is / waiting for you!"
    t[536] = "Come on, hurry / to the castle!"
    t[537] = "Having delivered / the message, the / Orc happily ran"
    t[538] = "off into town. / \"I heard you were / attacked by rogue"
    t[539] = "knights.\" From the / darkness emerged / a lone figure."
    t[540] = "It was Zel, leader / of the knight unit. / Zel: I heard you"
    t[541] = "fought rogues on / the third floor. / I hurried there,"
    t[543] = "but you'd already / dealt with them. / To be clear, those"
    t[544] = "rogues have nothing / to do with us. / They are scum who"
    t[545] = "deserted the Order. / I intended to / deal with them"
    t[546] = "myself eventually. / Thank you for / handling it."
    t[547] = "Zel said this with / a brief nod, but / his cold expression"
    t[548] = "betrayed no / emotion. \"I have / one more request."
    t[549] = "Show me the / keepsake you / obtained."
    t[550] = "The one you / received from / a man called Ingo.\""
    t[552] = "\"Indeed, this / belongs to His / Majesty. Well found."
    t[553] = "This will help / in the search / for His Majesty.\""
    t[554] = "\"Perhaps His / Majesty is still / alive.\""
    t[555] = "Lord Webster / appeared from / the darkness."
    t[556] = "Webster: It took / time to get access, / but I had someone"
    t[557] = "examine His / Majesty's coffin. / Astonishingly,"
    t[558] = "it was empty. / So someone took / the remains?"
    t[559] = "It's possible, / but unless one is / a skilled alchemist,"
    t[560] = "there'd be no need / for remains. If / they're operating"
    t[561] = "in the city, / someone must know. / Webster frowned"
    t[562] = "and thought. But / it's certain that / someone is working"
    t[563] = "in the shadows. / All answers lie / in the labyrinth."
    t[564] = "Webster left with / a stern expression."
    t[565] = "Now go to the / castle."
    t[566] = "His Majesty will / be pleased by your / accomplishment."
    t[567] = "Zel's face melted / into the darkness."

    # ============================================================
    # SCENE: Duhan city at night - Simson encounter (568-614)
    # Simson is a broken ex-mercenary who went mad in the labyrinth
    # (See guide: "Simson Dupin" - San Lazar Demons leader)
    # ============================================================
    t[568] = "A heavy fog had / settled over the / deserted streets."
    t[569] = "No one was in / sight. Not a sound, / not even the wind."
    t[570] = "The city was / deathly still. But / what you saw upon"
    t[571] = "entering was not / the famed \"Jewel of / Venoa,\" the proud"
    t[572] = "capital. It was / a dreary, desolate / city that hinted"
    t[573] = "at dark times. / After a while, you / heard voices from"
    t[574] = "the fog. \"Hey, / come on. Tell me. / It doesn't matter"
    t[575] = "if you hide it.\" / A man approached, / staggering."
    t[576] = "His hair was a / mess, clothes filthy, / eyes unfocused,"
    t[577] = "face twitching. / \"Hey friend, hehe, / you know where God"
    t[578] = "is hiding, right? / Come on, tell me. / I need to tell"
    t[579] = "Him something. / Hehe, I know you're / looking for God's"
    t[580] = "hiding place too. / Better find him / fast, for your"
    t[581] = "own sake.\" The man / glared at you with / a twisted grin."
    t[582] = "\"Ahh, I see. You / don't know about / what happened."
    t[583] = "That's why you're / looking for God's / hiding place."
    t[584] = "But you know what? / I saw it!"
    t[585] = "Yeah, they were / there alright, / hiding in the dark."
    t[586] = "And if you let / your guard down, / they come at you."
    t[587] = "Hehe, my friends / got chomped right / from the start."
    t[588] = "Munch, chomp. / Munch, chomp."
    t[589] = "The man made / exaggerated biting / motions over and"
    t[590] = "over. Nothing / works, nothing!"
    t[591] = "Some even fought / while crying."
    t[592] = "Hehehehe, / Ahahahahaha!"
    t[593] = "His hysterical / laughter echoed / through the streets."
    t[594] = "The man fell to / his knees, clutching / his head, laughing."
    t[595] = "He was so far gone / he didn't even / notice the drool"
    t[596] = "running down his / chin. Ahahaha! / Some fought with"
    t[597] = "everything they / had! But nothing / worked, nothing!"
    t[598] = "Sure thing, I tell / you. Even God / would be done for!"

    # Sister comes for Simson (600-614)
    t[600] = "\"What are you doing / out here?\""
    t[601] = "A sister spotted / you from afar and / came running."
    t[602] = "Sister: I've been / looking everywhere! / Walking around"
    t[603] = "in this weather, / you'll catch cold! / Come now, dinner"
    t[604] = "is ready. The man / called Simson / obediently followed"
    t[605] = "the sister. Please / don't judge him. He / fought for this"
    t[606] = "city and ended up / like that. He was / once a famous"
    t[607] = "mercenary captain. / But Karman's / Labyrinth destroyed"
    t[608] = "his mind. Now he / wanders the streets, / as if fleeing"
    t[609] = "from something. / I don't know what / he saw."
    t[610] = "But whatever it / was, it was / terrible enough"
    t[611] = "to break him. You / seem to be an / adventurer too."
    t[612] = "It's a hard life. / Having to risk / your life to gain"
    t[613] = "anything. May God / watch over you."
    t[614] = "Please take care / of yourself."

    # Repeat of night scene (615-619, same as 568-572)
    t[615] = "A heavy fog had / settled over the / deserted streets."
    t[616] = "No one was in / sight. Not a sound, / not even the wind."
    t[617] = "The city was / deathly still. But / what you saw upon"
    t[618] = "entering was not / the famed \"Jewel of / Venoa,\" the proud"
    t[619] = "capital. It was / a dreary, desolate / city."

    # ============================================================
    # SCENE: Meeting elf girls Lute & Emilia in the city (620-649)
    # ============================================================
    t[620] = "After looking / around, you heard / girls' voices from"
    t[621] = "the fog. Girl A: / \"A new person!\" / Girl B: \"What do"
    t[622] = "they look like?\" / They were elf / girls."
    t[623] = "Elf girl: Hey, / you're a new / adventurer, right?"
    t[624] = "I saw you at the / entrance earlier."
    t[625] = "Despite slight / differences in / hair color, the"
    t[626] = "twins were nearly / identical. \"You're / going to Karman's"
    t[627] = "Labyrinth too, / right? With things / as they are, no"
    t[628] = "one can leave this / city. Sigh, it's / so depressing."
    t[629] = "Ever since the / princess died, / nothing but bad"
    t[630] = "things happen. / Monsters from the / labyrinth, the city"
    t[631] = "blockaded, and the / king gravely ill. / All because of"
    t[632] = "the witch in the / labyrinth, and / nobody has been"
    t[633] = "able to find her. / Basically, everyone / is useless."
    t[634] = "What about you?"
    t[635] = "Think you could / find her? If you / defeat the witch,"
    t[636] = "a huge reward / awaits! We asked / around. Someone"
    t[637] = "told us: soon, / something that will / determine Duhan's"
    t[638] = "fate will happen. / So we're watching / for new adventurers."
    t[639] = "And there's one / more important / thing."
    t[640] = "Someone with / great knowledge is / being sought."
    t[641] = "A terrifying / prophecy: the city / will be swallowed"
    t[642] = "by darkness and / all will perish. / We don't know what"
    t[643] = "it means, but / something big is / coming. We're"
    t[644] = "prepared for it. / The twin girls / whispered."
    t[645] = "Girl A: \"Emilia, / let's go.\" Girl B: / \"Right. They might"
    t[646] = "notice we're gone.\" / \"Well, we have / things to do."
    t[647] = "Let's meet again. / My name is Emilia."
    t[648] = "I'm Lute. We both / live at the castle. / See you!\""
    t[649] = "The elf girls / hurried back into / the fog."

    # ============================================================
    # SCENE: Simson encounter (repeat/variant) (650-674)
    # Same Simson scene, slightly different version
    # ============================================================
    t[650] = "\"Hey, come on. Tell / me. It doesn't / matter if you hide"
    t[651] = "it.\" A man / staggered toward / you."
    t[652] = "His hair was a / mess, clothes filthy, / eyes unfocused,"
    t[653] = "face twitching. / \"Hey friend, hehe, / you know where God"
    t[654] = "is hiding, right? / Come on, tell me. / I need to tell"
    t[655] = "Him something. / Hehe, I know you're / looking for God's"
    t[656] = "hiding place too. / Better find him / fast, for your"
    t[657] = "own sake.\" The man / glared at you with / a twisted grin."
    t[658] = "\"Ahh, I see. You / don't know about / what happened."
    t[659] = "That's why you're / looking for God's / hiding place."
    t[660] = "But you know what? / I saw it!"
    t[661] = "Yeah, they were / there, hiding / in the dark."
    t[662] = "And if you let / your guard down, / they come at you."
    t[663] = "Hehe, my friends / got chomped right / from the start."
    t[664] = "Munch, chomp. / Munch, chomp."
    t[665] = "The man made / exaggerated biting / motions over and"
    t[666] = "over. Nothing / works, nothing!"
    t[667] = "Some even fought / while crying."
    t[668] = "Hehehehe, / Ahahahahaha!"
    t[669] = "His hysterical / laughter echoed / through the streets."
    t[670] = "The man fell to / his knees, clutching / his head, laughing."
    t[671] = "He was so far gone / he didn't notice / the drool running"
    t[672] = "down his chin. / Ahahaha! Some / fought desperately!"
    t[673] = "But nothing / worked, nothing!"
    t[674] = "Sure thing, I tell / you. Even God / would be done for!"

    # Sister variant (676-689)
    t[676] = "\"What are you / doing out here?\""
    t[677] = "A sister spotted / him and came / running."
    t[678] = "Sister: I've been / looking everywhere! / You'll catch cold"
    t[679] = "out here! Come, / dinner is ready. / Please come eat."
    t[680] = "The man called / Simson obediently / followed the sister."
    t[681] = "Please don't judge / him. He fought / for this city."
    t[682] = "He was once a / famous mercenary / captain."
    t[683] = "But Karman's / Labyrinth destroyed / his mind."
    t[684] = "Now he wanders, / as if fleeing / from something."
    t[685] = "I don't know what / he saw."
    t[686] = "But it was terrible / enough to break / even a strong man."
    t[687] = "You seem to be / an adventurer too."
    t[688] = "It's a hard life, / having to risk / everything."
    t[689] = "Please, take care."

    # ============================================================
    # SCENE: Elf ritual / Allied Art creation (690-770)
    # Lute & Emilia try to create Allied Art with Identification Bracelet
    # ============================================================
    t[690] = "Following the memo, / you entered and / a strange light"
    t[691] = "greeted you. In / the center of a / magic circle, an"
    t[692] = "elf girl stood / perfectly still. / Two Orcs sat"
    t[693] = "watching over them. / One noticed you / and quietly"
    t[694] = "approached. Orc: / Shh, be quiet!"
    t[695] = "They're in the / middle of a ritual!"
    t[696] = "Don't break their / concentration!"
    t[697] = "The twins were / the elf girls from / earlier."
    t[698] = "Through intense / concentration, / their skin had"
    t[699] = "turned pale, and / faint marks had / appeared on"
    t[700] = "their foreheads. / One raised the / Identification"
    t[701] = "Bracelet and began / to chant softly. / Her voice was"
    t[702] = "hauntingly / beautiful. \"O / light in darkness,"
    t[703] = "small star in the / deep night, show / your face like"
    t[704] = "the moon.\" As / she chanted, / energy began to"
    t[705] = "manifest. A great / light filled the / room."
    t[706] = "The Orcs watched / in breathless awe."
    t[707] = "One moment, two / moments -- agonizing / time passed."
    t[708] = "But nothing / happened."
    t[709] = "\"You idiots!\" / The elf girls / scolded the Orcs."
    t[710] = "Girl A: \"No good, / not at all!\" / Girl B: \"What is"
    t[711] = "this? The energy / is too dispersed!\" / Girl A: \"Did"
    t[712] = "you fight like I / told you?\" Orc A: / \"W-We did!\" Orc B:"
    t[713] = "\"We fought 32 / turns!\" Girl A: / \"So ordinary energy"
    t[714] = "won't work!\" / Girl B: \"We need / much stronger power.\""
    t[715] = "Just then, your / Identification / Bracelet reacted."
    t[716] = "\"Why did only his / bracelet activate / the imprint?\""
    t[717] = "\"Why did only her / bracelet activate / the imprint?\""
    t[718] = "In a haze, you / heard the girls' / voices."
    t[719] = "\"It was probably / something obtained / somewhere.\""
    t[720] = "\"Did the memory / resurface, or is / it a coincidence?\""
    t[721] = "\"Either way, now / he will enter / the great flow.\""
    t[722] = "\"Yes, just as the / prophecy we saw / foretold.\""
    t[723] = "\"It was probably / something obtained / somewhere.\""
    t[724] = "\"Did the memory / resurface, or is / it a coincidence?\""
    t[725] = "\"Either way, now / she will enter / the great flow.\""
    t[726] = "\"Yes, just as the / prophecy we saw / foretold.\""
    t[727] = "When you regained / consciousness, / Lute and Emilia"
    t[728] = "were there. They / introduced / themselves."
    t[729] = "\"That Identification / Bracelet you have--"
    t[730] = "where did you / get it?\""
    t[731] = "\"You've just gained / the power called / Allied Art."
    t[732] = "A special combat / technique normally / only monsters"
    t[733] = "can use. We want / to know how it was / stored in the"
    t[734] = "bracelet. We know / you saw a dead / adventurer's"
    t[735] = "memories. But why / did only yours / activate?"
    t[736] = "Could the memories / you saw be from / the moment of"
    t[738] = "death? I knew it! / I suspected it / from the start."
    t[739] = "Memory imprinting / can't be done / carelessly."
    t[740] = "Only intense / emotions at the / moment of death"
    t[741] = "can trigger it. / What should we do, / Lute?\""
    t[742] = "Lute pondered / with a troubled / expression."
    t[743] = "\"I absolutely hate / human experiments.\""
    t[744] = "\"I know, I know, / but for now, / silence is best.\""
    t[745] = "\"What? You mean / pretend we don't / know?\""
    t[747] = "\"Bergran is / a good person. / He won't harm us."
    t[748] = "But if word gets / out that we know / the secret, others"
    t[749] = "will come for us.\" / \"Iris is back!\""
    t[750] = "\"Sorry I'm late. / It took a while / to slip past the"
    t[751] = "knights.\" It was / the female / adventurer from"
    t[752] = "the labyrinth. / \"Oh? It's you!\""
    t[753] = "Lute: \"Listen! His / Identification / Bracelet activated!\""
    t[754] = "Emilia: \"Yes, just / as we predicted!\""
    t[755] = "Lute: \"Listen! Her / Identification / Bracelet activated!\""
    t[756] = "Emilia: \"Yes, just / as we predicted!\""
    t[757] = "The girls showed / Iris the light / from earlier."
    t[759] = "\"So the Bracelet / stores a dead / adventurer's"
    t[760] = "memories?\" Lute: / \"We knew it could / store memories.\""
    t[761] = "Emilia: \"Of course, / we designed it / that way.\""
    t[762] = "Lute: \"But we didn't / know it could / capture dying"
    t[763] = "moments.\" \"The / memories of the / dead? The Pope"
    t[764] = "would be furious.\" / Iris said with / a wry smile."
    t[765] = "\"But this clears / things up. The / Identification"
    t[766] = "Bracelet given / to the strike force / exists to grant"
    t[767] = "Allied Art. This / explains how / Duhan's knights"
    t[768] = "obtained it. But / to think such / a thing was"
    t[769] = "possible... / 'Imprinting' -- / an astounding"
    t[770] = "phenomenon. / 'Memory / imprinting.'\""

    # ============================================================
    # SCENE: Gin's tavern quests (823-843)
    # Gin is a tavern keeper who gives requests
    # ============================================================
    t[823] = "I originally / thought completing / about three requests"
    t[824] = "would do. But come / to think of it, / you've already"
    t[825] = "done that many. / So as a token / of our gratitude,"
    t[826] = "here you go. Gin / went through a / back door into"
    t[827] = "the tavern and / soon returned with / a large box."
    t[829] = "You received / Gin's Box."
    t[830] = "Now then! Don't / linger around here / too long. Get"
    t[831] = "back to the main / street. Very well, / complete three"
    t[832] = "requests for me."
    t[833] = "They don't have / to be from us -- / any request that"
    t[834] = "benefits us will / do. Truth is, / I've been too busy"
    t[835] = "with work to go / out much. If you / can complete my"
    t[836] = "three requests, / come back. / Gin: Oh, what is it?"
    t[837] = "You reported / completing the / requests Gin"
    t[838] = "had given you. / Good, excellent. / Wait here a moment."
    t[839] = "Gin went through / the back door and / into the tavern."
    t[840] = "He soon returned / with a large box."
    t[842] = "You received / Gin's Box."
    t[843] = "Now then! Don't / linger here. / Get back to the"

    # ============================================================
    # SCENE: Venoan Bookstore / Lidi (844-929)
    # Lidi runs the Venoan Bookstore, sells information
    # ============================================================
    t[844] = "main street. / Following the / address from the"
    t[845] = "tavern notice, / you headed to the / Venoan Bookstore."
    t[846] = "After searching / through unfamiliar / backstreets for"
    t[847] = "an hour, you / found a terraced / house with a sign:"
    t[848] = "\"Venoan Bookstore / Office - Open, / Please Enter.\""
    t[849] = "You knocked but got / no answer, so you / opened the"
    t[850] = "unlocked door. A / bell chimed, but / no one responded."
    t[851] = "The place looked / more like a / regular room"
    t[852] = "than an office. / \"Yes, yes, / yeeeees!\""
    t[854] = "Almost at once / you heard footsteps / racing down"
    t[855] = "the stairs. / \"Gyaaaahhhh!\""
    t[856] = "With a tremendous / crash, Lidi came / tumbling down"
    t[858] = "the stairs. She / approached, / clutching her head."
    t[859] = "Lidi: Welcome!"
    t[860] = "Oww, that hurt!"
    t[861] = "This place is so / narrow, the stairs / are steep too."
    t[862] = "And with the / storage upstairs, / I'm always running"
    t[863] = "up and down! So I / slip and fall / constantly!"
    t[864] = "Ugh, my head / hurts!"
    t[865] = "Lidi enthusiast- / ically demonstrated / how she slips and"
    t[866] = "falls. Oh, sorry! / That doesn't matter."
    t[867] = "Thanks for coming! / Are you here / for information?"
    t[868] = "What will you say? / [Yes] [No]"
    t[869] = "I see! Since it's / your first time, / let me explain"
    t[870] = "our system. Oh! / But first, wait!"
    t[871] = "Huh, that's not it? / Well, you might / need information"
    t[872] = "someday, right? / So let me explain / our system anyway."
    t[873] = "Oh! But first, / wait!"
    t[874] = "Lidi opened a / drawer by the wall / and took out"
    t[875] = "scissors. Our info / isn't free, you / know! That's no"
    t[876] = "way to run a / business. But I / think it's worth"
    t[877] = "it! Here, I give / these out for free, / so take one!"
    t[878] = "It's a file to / keep the info you / buy from us!"
    t[879] = "Library: Info File / has been registered."
    t[880] = "Info costs 1000g / each. Normally / 1200g, but since"
    t[881] = "you know Pipin... / Just then, a small / sound came from"
    t[882] = "upstairs. Oh, / Pipin! He can stop / hiding now."
    t[883] = "Anyway, that's the / intro done. / Come again when"
    t[884] = "you need info! / I'll be waiting!"
    t[886] = "Info costs 1000g / each. Normally / 1200g, but Pipin"
    t[887] = "put in a word / for you. Just then, / a small sound"
    t[888] = "came from upstairs. / Oh, Pipin! No need / to hide here."
    t[889] = "Anyway, that's the / intro done."
    t[890] = "Come again when / you need info! / I'll be waiting!"
    t[892] = "Lidi saw you off / as you left the / Venoan Bookstore."
    t[893] = "Lidi: Welcome! / Need information?"
    t[894] = "Buy information? / [Cost: 1000g] / [Yes] [No]"
    t[895] = "Oh, that's not it? / Well, come again!"
    t[896] = "Not enough gold!"
    t[897] = "Aww, not enough / money? Sorry, but / I can't give"
    t[898] = "discounts. Bring / enough next time! / Bye-bye!"
    t[899] = "You paid Lidi / 1000g."
    t[900] = "Thanks! Now then, / let me find your / information..."
    t[902] = "Library: Info File / has been updated."
    t[903] = "See for yourself! / Come again soon!"
    t[904] = "Sorry, I don't / have any more / information for"
    t[905] = "you right now. / Lidi clapped her / hands together"
    t[906] = "apologetically. / I can't just leave / the shop, and"
    t[907] = "no new tips are / coming in from / adventurers!"
    t[908] = "Lidi pondered / with her chin / in her hand."
    t[909] = "But soon she / brightened up / and spoke."
    t[910] = "Hey, how about / you let me join / your party?"
    t[911] = "Sitting here won't / get me any new / scoops."
    t[912] = "I'll close the / info shop for now / and go back to"
    t[913] = "the labyrinth. / But I can't go / alone past the"
    t[914] = "fourth floor. So, / please? I want to / see the depths"
    t[915] = "of the labyrinth! / Will you take Lidi / as a companion?"
    t[916] = "[Yes] [No] Yay, / it's decided!"
    t[917] = "I'll dash to the / Adventurer's Guild / right now!"
    t[918] = "By the time you / get back, I should / be ready to"
    t[919] = "join your party! / Oh, I need to post / a closure notice"
    t[920] = "too! So much to / do! Lidi rushed / out, smiling"
    t[921] = "despite her busy / chatter. Lidi has / been registered"
    t[922] = "at the Guild. When / you declined, / her smile vanished."
    t[923] = "Awww, no? I guess / I'm just dead / weight, right?"
    t[924] = "But I can't stay / cooped up here / forever."
    t[925] = "Alright, I'll try / the labyrinth / alone again!"
    t[926] = "Too bad we can't / go together, but / let's both do"
    t[927] = "our best! First, / I need to post a / closure notice"
    t[928] = "and prepare. Well / then, goodbye! / Let's meet again"
    t[929] = "someday! Lidi / looked a bit sad / but waved cheerfully."

    # ============================================================
    # SCENE: Reactions to Identification Bracelet / memory reveal (930-952)
    # Vela, Konde, Erika react
    # ============================================================
    t[930] = "Vela: What a / terrible feeling!"
    t[931] = "Like having a / needle driven into / your heart!"
    t[932] = "Being forced to / see someone's dying / moments -- how"
    t[933] = "can this be right? / Those girls said / they designed the"
    t[934] = "Bracelet, but they / didn't know how / it would be used."
    t[935] = "King Ortrud must / have known."
    t[936] = "That the Bracelet / can trap a dying / person's memories."
    t[937] = "Konde: The memories / of the dead? / Unsettling talk."
    t[938] = "For one who has / seen much death / firsthand, it is"
    t[939] = "not a pleasant / thought. Death is / cruel -- a sense"
    t[940] = "of helplessness / and regret. Being / unable to help"
    t[941] = "is the worst. But / what matters now / is not that."
    t[942] = "Why use such / advanced alchemy / to imprint"
    t[943] = "memories into the / Bracelet? I sense / something akin"
    t[944] = "to a conspiracy. / I hope I'm wrong."
    t[945] = "Erika: My heart / aches!"
    t[946] = "Unable to receive / last rites, dying / in the depths"
    t[947] = "of the labyrinth / like that... For / our adventurer"
    t[948] = "friends to endure / such hardship... / I never truly"
    t[949] = "considered it. / Trapping a dying / person's memories"
    t[950] = "is wrong. But / rather than / pursuing blame,"
    t[951] = "we should ensure / no one else suffers / the same fate."
    t[952] = "I may be speaking / out of turn, but / that is what I"

    return t


def main():
    print("Loading batch_01.json...", file=sys.stderr)
    with open('C:/Programmieren/wizardrytranslation/data/type2_translated/batch_01.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    translation_map = build_translation_map()

    # Find and fix all R1196 entries with Japanese in English field
    total_problem = 0
    fixed = 0
    unfixed_indices = []

    for i, entry in enumerate(data):
        if entry['resource'] == 1196 and has_japanese(entry['english']):
            total_problem += 1
            idx = entry['msg_index']
            if idx in translation_map:
                data[i]['english'] = translation_map[idx]
                fixed += 1
            else:
                unfixed_indices.append(idx)

    print(f"Total problematic entries: {total_problem}", file=sys.stderr)
    print(f"Fixed: {fixed}", file=sys.stderr)
    print(f"Remaining unfixed: {len(unfixed_indices)}", file=sys.stderr)
    if unfixed_indices:
        print(f"Unfixed indices: {unfixed_indices}", file=sys.stderr)

    # Verify no Japanese remains in fixed entries
    still_jp = 0
    for entry in data:
        if entry['resource'] == 1196 and has_japanese(entry['english']):
            still_jp += 1

    print(f"Entries still with Japanese after fix: {still_jp}", file=sys.stderr)

    # Write output
    with open('C:/Programmieren/wizardrytranslation/data/type2_translated/batch_01.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Wrote updated batch_01.json", file=sys.stderr)


if __name__ == '__main__':
    main()
