import json, sys, os

# Load batch_06.json
path = "C:/Programmieren/wizardrytranslation/data/type2_translated/batch_06.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Translation dictionary for R1209 entries
# Built from guide_full_text.txt cross-referenced with garbled Japanese source
translations = {
    0: "The medal obtained by defeating the floor master was offered to the gods.",
    1: "The lever has been locked and won't move.",
    2: "Will you use the lever? Yes No",
    4: "The lever has been locked and won't move.",
    5: "Will you use the lever? Yes No",
    7: "Let's search thoroughly! Architect? Treasury Misc. 1 Treasury Misc. 2 Treasury Misc. 3 Treasury Misc. 4 Treasury Misc. 5 Treasury Misc. 6 Treasury Misc. 7 Treasury Misc. 8 Treasury Misc. 9 Treasury Misc. 10 Shadow Check Item Appraisal Thanks to the damage? Cursed Alleid Info 1 Cursed Alleid Info 2 Cursed Alleid Info 3 Cursed Alleid Info 4 Cursed Alleid Info 5 Cursed Alleid Info 6 Cursed Alleid Info 7 Cursed Alleid Info 8 The quest has been completed.",
    8: "In Yoppen's room, a Succubus was sleeping with her wings folded.",
    10: "Shhhh, you have to open the door quietly or else Big Sister will wake up.",
    11: "There was not only a Succubus, but also Yoppen in the room.",
    12: "Yoppen spoke to you in a quiet voice so as not to wake up the sleeping Succubus.",
    13: "I was looking for Big Sister so that I could talk to her in person.",
    14: "I couldn't find her at all, so I went for a break and suddenly there she was, I had finally found her!",
    15: "I was wondering how to wake her up, but now that you're here, I've got an idea!",
    16: "Would you mind subduing Big Sister for a moment?",
    17: "Big Sister always runs away when I approach her! I wonder why!?",
    18: "I know it sounds a bit rough, but please! If you catch her, I can talk to Big Sister!",
    19: "Oh, ok. Then get out of here.",
    20: "Because if there are too many people here, Big Sister might wake up, you know?",
    21: "Yoppen told you to leave the room quietly.",
    22: "Fufufu, please hurry up. If Big Sister wakes up, there's no point, so do it as soon as possible!",
    23: "At Yoppen's insistence, you walked over to the sleeping Succubus.",
    25: "The Succubus was awakened by your presence!",
    26: "You forcibly subdued the Succubus, who was desperately and violently resisting.",
    27: "What... what are you doing...!?",
    28: "Seeing the Succubus subdued, Yoppen started to speak to the Succubus with a big smile on his face.",
    29: "Hey there, I finally found you... Big Sister............. Big Succubus Sister.........",
    30: "Don't come near me! You're disgusting!",
    31: "Big Sister, please think of me too. I'll stay at the nearby inn until Big Sister comes back!",
    32: "I refuse to breathe in the life energy of someone like you! You will only stain my blood!",
    33: "Seeing the Succubus disgusted by him, Yoppen had tears in his eyes.",
    34: "Big Sister, why are you so mean...!",
    35: "Because you're disgusting! Get away from me! Get away from me!",
    36: "The Succubus flapped her wings, desperately trying to escape.",
    37: "Yoppen, with tears streaming down his face, came closer to her, trying to touch her!",
    38: "Nooooooooooooooooo!",
    39: "The Succubus' desperate cry conjured a strong magical force that made her disappear to some place unknown.",
    40: "Whaa... Big Sister...!!",
    41: "The only sound left in the room was the sobbing sound of the stranded Yoppen.",
    42: "Ugh... Eugh! After little sister Pixie, Big Sister left me alone too... Why...!!",
    43: "Maybe... I... I wonder if they really hate me...!?",
    44: "What's your response? Yes No",
    45: "Ughhhhh... I see... I didn't know that... I guess you don't like me either...",
    46: "I don't need any words of comfort. Only a princess can soothe me now.",
    47: "That's right! Princess! I'm sure Princess Aurora will respond to my wishes!",
    48: "My life is dedicated to princesses-only now!",
    49: "You, thank you. Thank you for making me realize the truth.",
    50: "I don't mind it at all now, that the Pixie and Big Sister are hating on me.",
    51: "Well, I'm going to go back to the city and start preparing for the real princess hunt.",
    52: "I'm sure we'll meet again, so see you soon.",
    53: "Yoppen wiped his tears and left the room.",
    54: "In Yoppen's room, Yoppen was silently staring at the Succubus, who was still sleeping.",
    55: "Yoppen looked annoyed and complained in a small voice.",
    57: "Just don't keep coming in and out of the door, it's too noisy. If Big Sister wakes up, it's your fault.",
    58: "Or are you still interested in doing me a favor?",
    59: "Then don't come in here!",
    60: "Yoppen told you to leave the room quietly.",
    61: "The Vigger Shop store front on labyrinth B7 has been established.",
    62: "A creepy, haunting voice rang out.",
    63: "In the dimly lit room, there was an altar-like structure in the back, surrounded by several alchemists.",
    64: "An alchemist, noticing the intruder, approached with a knife drawn.",
    65: "Don't do it. You'd be throwing your lives away. You're no match for them.",
    66: "It was Lord Webster's voice.",
    67: "The alchemists opened the way.",
    68: "Webster: Well, well, what can I do for you?",
    69: "I'm afraid I'm a bit busy at the moment. I'm sorry, but if you don't have any business with me, you'll have to leave.",
    70: "Emilia peeked out from behind your back.",
    71: "What the hell are you doing? Give us back our princess!",
    72: "Give back the princess!",
    73: "Are you a fool? Do you think you can get away with such a dirty trick?",
    74: "Dirty? Haha, is that what you children think?",
    75: "One life will save many lives and bring permanent peace to Venoa.",
    76: "If you can save the world with your sentimental feelings, so be it.",
    77: "But as always, the truth is ruthless. Do you think that a compassionate heart can save a sick motherland?",
    78: "If you think that God will help us, then pray to him.",
    79: "But it is useless to expect God to do so.",
    81: "A criminal, as good as dead, has ruined your plans, and now this little elf girl is standing in his way.",
    82: "Who could have imagined such an outcome?",
    83: "I was imagining various things.",
    84: "Would Ortrud, having learned of my betrayal, attack me with his Royal Knights?",
    85: "Or would the witch come with her menagerie of demons?",
    86: "But then again, God is a shifty fellow.",
    87: "The moment a dream comes true is always such an unsightly one.",
    88: "What are you trying to do!?",
    89: "It's over for you. Bergran will be here soon!",
    90: "There's nowhere for you to run now!",
    91: "Then we have little time.",
    92: "Let me enlighten you a little bit more before I say goodbye to this body.",
    93: "Twenty years ago, as a child, I lost everything when Ortrud killed my mother and father in front of my eyes.",
    94: "Since then, I have only lived to save my family's grudge.",
    95: "To become the Vizier of Duhan, to marry the princess,",
    96: "to take back the Duhan royal family into my hands.",
    98: "If I only had wanted to take the throne, I could have simply waited for the king to die.",
    99: "But I was enchanted by the dream of rescuing Duhan from the hands of the witch and becoming the true Holy King.",
    100: "If I succeed in resurrecting the black spirit and bringing back the Warrior God, it will not be a wishful dream after all.",
    101: "But this is the result of high hopes.",
    102: "Even though we finally have Her Highness, who will act as the divine body for the Warrior God,",
    103: "we are yet left to rot in the depths of the labyrinth, halfway through.",
    104: "So did Lord Webster say, and looked up to the sky.",
    105: "God did take everything from me once, and now he really is planning to do it again.",
    106: "Lord Webster's voice had a sombre sound, as if it were coming from a distant past.",
    107: "All right, this is the last call.",
    108: "If I can bring Her Highness to the Warrior God, the world will be mine.",
    109: "Unless you defeat me here, then it will all be over.",
    110: "Of course, I will raise the price. Not only my life, but also my soul will be on the table.",
    111: "Whether this is the day when my family will be rewarded for their untimely deaths in Kadina, or whether God wants to destroy me,",
    112: "I will not regret my actions, even if my soul will decay for eternity.",
    113: "Lord Webster suddenly slashed his own wrists with his knife, dripping spilled blood onto the cover of the shiny black book.",
    114: "Lord Webster's face went as white as that of a dead man.",
    115: "Once possessed by the King of San-Goth...!",
    116: "You, the eternal knight and immortal being...!",
    117: "Oh, Black Spirit of Death, reveal thyself!",
    118: "An eerie white smoke-like miasma erupted from the book in his hand and surrounded Lord Webster completely.",
    119: "The cold, freezing mist was the grudge of countless possessed adventurers that died in the labyrinth.",
    120: "The atmosphere in the room suddenly changed.",
    121: "It became chilling, dismal, and a cold malevolence surrounded you.",
    122: "The grudges of the dead swarmed together, shouting their resentment against the living, and attacked Lord Webster.",
    123: "Lord Webster let out a scream of desperation.",
    124: "His form changed into a hideous shape as you looked on.",
    125: "The body of the Grim Reaper collapsed and turned to ash.",
    126: "Countless wandering souls rose from the ashes with shouts of joy at their release.",
    128: "Emilia rushed towards the altar.",
    129: "The princess was lying on the floor.",
    130: "Emilia tried to help the princess sit up, but the princess, in her dazed state, was mumbling something.",
    131: "Lord Webster... don't blame him...!",
    132: "He, too, has been taken advantage of by the voices of darkness...!!",
    133: "Emilia stood up and took a closer look at the princess, making sure she had not been harmed anywhere.",
    134: "Emilia: Fortunately, she's only sleeping because she's extremely tired.",
    135: "I'm going to return with the Princess to the city.",
    136: "It should be safe now, now that Lord Webster is no more.",
    137: "I'm glad you're safe.",
    138: "Suddenly, a man dressed in black appeared before you.",
    139: "Ce-... Cell. What are you doing here?",
    140: "Emilia braced herself.",
    141: "Cell: Don't worry, I'm on your side.",
    142: "I've been watching over Her Highness with my ninjas under the orders of His Majesty Ortrud.",
    144: "Lies! You were under Lord Webster's command, and you were looking for us, weren't you?",
    145: "All at the behest of His Majesty, the King.",
    146: "Whether it was to help Lord Webster or to protect Her Highness who was hiding in the labyrinth.",
    147: "What is going on here?",
    148: "And how could His Majesty have known about us?",
    149: "His Majesty knew everything.",
    150: "He knew that she was alive, and that you were hiding her in the depths of the labyrinth.",
    151: "I can't believe it! Then why didn't you help us earlier?",
    152: "If you had been watching over us, you should have known that we were in big trouble.",
    153: "Yes, I knew that.",
    154: "I, as a matter of unpleasant necessity, would have taken care of Lord Webster myself if no one else had reached this place.",
    155: "That however would have been against His Majesty's will.",
    156: "Because, as you must know, it was forbidden for us to touch him.",
    157: "We were ordered to leave no stone unturned until the end, and let the adventurers solve the problem.",
    158: "What are you talking about? What the hell does he want? Explain it to me.",
    159: "I am sure that His Majesty put a lot of thoughts into this, but I, as his servant, do not know either.",
    160: "Hmm, if you say so, I'll return to the castle and ask him directly then.",
    161: "Emilia and the princess returned to the city with the help of the Return Medicine.",
    162: "Adventurers, if you want to know the truth, come to the castle as well.",
    163: "Cell disappeared into thin air.",
    164: "You received 3 Vigger Friends Points.",
    165: "The party's HP and MP have been fully restored.",
    166: "You received 3 Vigger Friends Points.",
    167: "After resting for a while, you started to doze off.",
    168: "In the haze between waking and dreaming, you could see the shadow of a monster.",
    169: "Without time to judge whether it was a dream or reality, the monster's shadow came rushing towards you!",
    170: "After the battle with the orc, as you were catching your breath, the store clerk came running in a hurry.",
    171: "Whoa, are you alright!?",
    172: "Our shop sometimes gets attacked by scary monsters like that!",
    173: "You weren't waking up, so we left you behind when we evacuated!",
    174: "Well, glad you're safe! Go ahead and rest some more.",
    175: "But be careful not to doze off, okay?",
    176: "The party's HP and MP have been fully restored.",
    177: "This was your first visit to the store front of the Vigger Shop.",
    178: "What once had been just another room in the labyrinth was now decorated to look like a store.",
    179: "There was a demon at the counter, who seemed to have been hired as a clerk.",
    180: "Lucy was talking to the demon.",
    181: "Lucy noticed you, waved, and left the counter to approach you.",
    182: "You came to check out the shop? Me too actually.",
    183: "This is my first store front. I even went to the trouble of registering as an adventurer and hiring an escort to get here.",
    184: "It was a big deal, but it was worth seeing. I'm really impressed!",
    185: "It's thanks to you that we've been able to expand so much. I really appreciate it!",
    186: "So go ahead and do some shopping, so that we can grow even further!",
    187: "Well, I better return to the city now. It's much easier to go home because of this Return Medicine!",
    188: "I wish someone would invent medicine that lets you teleport to store fronts!",
    189: "Well, don't just visit the store front, come to the main shop too!",
    190: "Lucy once again waved to you, then took a bottle of Return Medicine out of her bag and downed it in one gulp.",
    191: "And then, her body disappeared in front of your eyes.",
    192: "There was a space divided by a pile of wood in one corner of the store.",
    193: "The words 'Event Space' were written on a plaque that was affixed at the entrance.",
    194: "There was a stack of papers on the counter that read: 'To commemorate the opening of the Event Venue, the Vigger Friends have now opened up applications for new members!'",
    195: "An imp sitting in front of the space noticed you and started talking.",
    196: "There was a sign at the Imp's Event Space saying 'The Vigger Friends are currently accepting new members!'",
    197: "The imp sitting in front of the space started talking to you.",
    198: "Haha, I'm sure you are very interested in joining the Vigger Friends!",
    199: "There's no need to be shy. How could you not be interested in such a great project like this!?",
    200: "How about it, shall I explain the Vigger Friends system to you? Or do you want to join right away?",
    201: "What will it be? Hear the explanation Join right away Do nothing",
    202: "I see, very good! Let me explain our system to you then!",
    203: "Ah, you can listen to my explanation while you're shopping, since I will give you a piece of paper when you join.",
    205: "Ahem! I'll start explaining now!",
    206: "We, the Vigger Friends, are a bunch of pals who want to make the Vigger Shop a more exciting and fun place!",
    207: "Customers who paid the admission fee to join are offered a variety of special services!",
    208: "These events will be held at the Event Space, and the more events you attend, the better!",
    209: "Plus, the more events you attend at the Event Space, the higher the chances are to win at our lottery game!",
    210: "So, do you want to get in too? I, of course, am a member of this club! No wonder why it's so great!",
    211: "I see, so you're in! Then, please put your name on the application form along with the admission fee of 5000G!",
    212: "I see, it's okay though. You don't have to join right away!",
    213: "Please make sure that you get in next time, bro!",
    214: "I see, it's okay though. You don't have to join right away!",
    215: "Please make sure that you get in next time, sis!",
    216: "Do you want to join? (Admission Fee: 5000G) Yes No",
    217: "Good, good, then let me take the admission fee.",
    218: "You paid 5000G.",
    219: "Yupp, I certainly got it! Now, let me give you the Vigger Friends membership card.",
    220: "0123456789-000000 Eh, your membership number is Number. It's not written on the membership card, though.",
    221: "Thank you very much!",
    222: "You received the Membership Card!",
    223: "Good, good, then let me take the admission fee.",
    224: "Wait, what!? You don't have 5000G!? That's a bit tough, you know!",
    225: "What a shame! Make sure you bring 5000G, no, even more than that, next time you come!",
    226: "Until then, we'll have to put your membership on hold!",
    227: "I see, it's okay though. You don't have to join right away!",
    228: "Please make sure that you get in next time, bro!",
    229: "I see, it's okay though. You don't have to join right away!",
    230: "Please make sure that you get in next time, sis!",
    231: "There was a sign at the Imp's Event Space saying 'The Vigger Friends are currently accepting new members!'",
    232: "The imp sitting in front of the space started talking to you.",
    233: "0123456789-000000 Welcome! Eh, you're member number, right?",
    234: "Between the 1st and 5th of the month is the Vigger Friends new member sign-up campaign.",
    235: "So right now there are no events running.",
    237: "The event schedule board read: 'Our talented worker is currently on a break. Please come back later.'",
    238: "The event schedule board read: 'Our talented worker is currently on a break. Please come back later.'",
    239: "?????Lomi: Hey there, welcome! Want me to read your fortune?",
    240: "The event schedule board read: 'I will tell you about your hidden power.'",
    241: "However, there was no one at the fortune-telling counter.",
    244: "A voice called you out from somewhere.",
    245: "You looked around, but there was no one who looked like the owner of the voice.",
    246: "As you turned back to the counter, you saw a faint shadow of a person.",
    247: "I feel sorry for you. Even though you're their leader, you don't possess IT.",
    248: "If you're going to bear a grudge, don't curse me, curse your fate instead.",
    249: "Good for you. You've got potential talent growing inside.",
    250: "Good for you. You don't have anything now, but I'm sure a hidden talent will blossom!",
    251: "I hope it blossoms while you're still alive.",
    252: "I'm Lomi the Ghost. If you pay me 2000G, I'll give you a more detailed reading.",
    253: "Would you like to have your fortune read? (Appraisal fee: 2000G per person) Yes No",
    254: "Then put the gold on the counter. I can't take it because my body is ethereal.",
    255: "You didn't have enough money to pay.",
    256: "No, I won't give you a discount.",
    257: "If you don't have any money, bring some. It's 2000G, okay?",
    258: "You paid 2000G.",
    259: "Thank you very much. Whose fortune do you want me to read?",
    260: "Thank you very much. This will also net you 4 Vigger Friends Points.",
    261: "So whose fortune do you want me to read?",
    262: "Fine, I don't care...",
    263: "After expressing her disappointment, Lomi disappeared again.",
    264: "Whose fortune do you want me to read?",
    265: "Your hidden talent has already blossomed.",
    266: "The talent hidden within you is...",
    267: "Your hidden talent has already blossomed.",
    268: "The talent hidden within you is...",
    269: "Your hidden talent has already blossomed.",
    270: "The talent hidden within you is...",
    271: "Your hidden talent has already blossomed.",
    272: "The talent hidden within you is...",
    273: "Your hidden talent has already blossomed.",
    274: "The talent hidden within you is...",
    275: "Your hidden talent has already blossomed.",
    276: "The talent hidden within you is...",
    277: "Good for you, having talent. Being able to learn lots of magic sounds impressive and amazing.",
    278: "Good for you, having talent. If you're good at healing magic, you might be suited for a support role.",
    279: "Good for you, having talent. Being brave enough to fight dragons is really strong.",
    280: "Good for you, having talent. Being good at defeating demons makes you a demon to the demons.",
    281: "Good for you, having talent. Oh, but please don't find mine and don't dig me up! I'm already dead though!",
    282: "Good for you, having talent. But you seem a bit scary! Don't bully me, okay?",
    283: "Good for you, having talent. Don't just keep taking attacks, make sure you attack too!",
    284: "Good for you, having talent. That's amazing, your body is the exact opposite of mine.",
    285: "Good for you, having talent. They say a miss is a lesson learned, and having few misses is a very good thing.",
    286: "Good for you, having talent. I don't have any fighting equipment, so I don't know, but monsters would be very scared of you.",
    287: "Good for you, having talent. You're good at finding items!? Give me something sometime!",
    288: "Good for you, having talent. Hey, even if you dissect me, you won't find any alchemy ingredients!",
    289: "Talent Reading #13 is Cut.",
    290: "Good for you, having talent. But just because you have the personality doesn't mean you have true character, right?",
    291: "Good for you, having talent. Just because you're good at running away doesn't mean you should always run.",
    292: "Good for you, having talent. Being able to use anything is amazing! But don't swing me around, okay?",
    293: "Good for you, having talent. You can put on anything!? But it would be wrong to wear me, right?",
    294: "Good for you, having talent. What amazing magical power! You could become a great mage at the Yugurta Magic Academy.",
    295: "Good for you, having talent. Being able to protect yourself is beyond brave, it's remarkable.",
    296: "Good for you, having talent. Being able to draw out hidden power is a wonderful talent, I think.",
    297: "No... nothing... I see nothing...",
    298: "...............",
    299: "It's unfortunate, but don't be depressed. Most people in this world are ordinary.",
    300: "Because if everyone had talent, it would be the new normal! In other words, everyone would be ordinary.",
    301: "There are only a few people who have talent.",
    302: "Being normal is normal, so don't be sad. You're not inferior.",
    303: "The key to developing your talent will be to work hard and accumulate a lot of knowledge.",
    304: "Your talents can only be utilized if you have a high level of wisdom, so it's best to study.",
    305: "Your hidden talents are deeply connected to your faith.",
    306: "If you live with a stronger faith, I'm sure good things will happen to you in time.",
    307: "It's important to be brave enough to face giant monsters without being afraid of the difference in size.",
    308: "You may lose your life now, but that's good experience.",
    309: "In the future, you might no longer be afraid of them, and are willing to face them again.",
    310: "There's a demonic heart inside you that stands above dragons and demons.",
    311: "When that heart is awakened, it will be a menace to demons.",
    312: "Don't be afraid of the spiritual... Death... or the undead.",
    313: "Don't worry, you'll grow to love them, not fear them.",
    314: "You seem to have good motor nerves.",
    315: "I think you need to work more on your arm strength than anything else for your talent to blossom.",
    316: "One day, you'll be able to see the enemy's movements as if they were in slow motion.",
    317: "I think you have excellent kinetic vision by nature, so all you need to do is train it.",
    318: "You have a strong life force.",
    319: "If you train your muscles even more, you can harden your body into something incredibly tough.",
    320: "You've got great foresight. You also seem to be very focused.",
    321: "I'm sure you'll awaken your ability to see further and further into the future.",
    322: "Then you'll be able to detect the enemy's movements and prevent mistakes, I'm sure of it.",
    323: "You seem to be good at grasping the characteristics of everything.",
    324: "So when your talent is awakened, you will be able to detect the enemy's vital points and dispose of them quickly.",
    325: "I find your attention span to be amazing.",
    326: "I feel like you can easily find things that normal people would overlook without noticing.",
    327: "I don't know much about your personality, but it seems you'd be good at research.",
    328: "Even if you've never done it before, you might find you're naturally good at it.",
    329: "So all of a sudden, you might develop a perverted hobby like dissection.",
    330: "You might even become fond of gutting demons.",
    331: "Talent Reading #13 is Cut.",
    332: "I think you have an air of coolness around you, like a mood maker.",
    333: "No matter how foolish you may act, it is hard to really dislike you.",
    334: "Well, I guess being popular is a kind of talent too.",
    335: "It's of course a lot better than having a talent for being hated.",
    336: "You are a very perceptive person.",
    337: "So if you polish your perceptivity, your ability to read the signs of your surroundings will be greatly enhanced.",
    338: "Even the best tools of war are useless if an unrelated class uses them.",
    339: "That's why people usually don't use things that don't match their class, but in your case, it's different.",
    340: "You can't do it now because your talent is still dormant,",
    341: "but I'm sure you'll be able to bring out the best in yourself by forcefully wielding them.",
    342: "If you wear something that doesn't fit your class, it will be useless.",
    343: "That's why people don't usually wear things that don't match their class, but in your case, it's different.",
    344: "You can't do it now because your talents are still dormant,",
    345: "but I'm sure you'll be able to bring out the best in yourself if you force yourself to wear it.",
    346: "I can feel a very strong magical power deep inside of you.",
    347: "You look like a genius, so it's probably best not to make any effort right now.",
    348: "I think you will grow at a very fast pace if you enhance your magical power after your talent grows.",
    349: "You seem to have a talent for drawing out the power of things rather than your own.",
    350: "I guess you could say that you are better with things than other people...?",
    351: "Anyway, I'm sure you'll realize this as soon as your talent grows.",
    352: "Your body's immune system tends to be stronger than most.",
    353: "Eventually, you may get sick for a while, but it will eventually go away again.",
    354: "Then again, it's best if you don't get sick in the first place.",
    356: "Lomi's ghostly figure almost disappeared for a moment.",
    357: "Oh... I'm so tired. I'm going to take a break for a while,",
    358: "so if you want to read someone else's fortune, please come back after a while. Bye...",
    360: "Lomi disappeared.",
    361: "Lomi disappeared.",
    362: "Lomi disappeared.",
    363: "Lomi disappeared.",
    364: "Lomi disappeared.",
    365: "Please come back again!",
    366: "0123456789-0000000123456789- Oh, member number! Welcome aboard!",
    367: "Please wait a moment. I'll check your Friends Points.",
    369: "Oh no! You don't have enough points accumulated yet!",
    370: "You need at least 1 point to participate in the Number Lottery.",
    371: "Please participate more actively in events and accumulate points!",
    372: "Alright, looking good! So, what shall we do?",
    373: "What do you want to do? (Currently: Points) Spend 1 point Listen to explanation Don't participate",
    374: "What do you want to do? (Currently: Points) Spend 1 point Spend 3 points Listen to explanation Don't participate",
    375: "What do you want to do? (Currently: Points) Spend 1 point Spend 3 points Spend 5 points Listen to explanation Don't participate",
    376: "I'll take 1 point! Well then, let the Member Number Lottery begiiiiiiiiiiiiiiin!",
    377: "I'll take 3 points! Well then, let the Member Number Lottery begiiiiiiiiiiiiiiin!",
    378: "I'll take 5 points! Well then, let the Member Number Lottery begiiiiiiiiiiiiiiin!",
    380: "Tada~, the number is...!",
    381: "And your membership number was... Number!",
    382: "...............",
    383: "Oh my goodnessssssssssss!",
    384: "The imp congratulated you by sprinkling confetti made of finely chopped paper over your heads.",
    385: "You guys did it! You're the first ones to hit the jackpot!",
    386: "So, here's your special prize: A thought-filled Identification Bracelet!",
    387: "You received the Identification Bracelet!",
    388: "You learned the Alleid Warp Attack from the thoughts within the bracelet.",
    389: "You learned Warp Attack.",
    390: "By the way, from next time onwards, the prize will be a Bone of the Dead and Magical Wine!",
    391: "You guys did it again! With so many jackpots, business is going down!",
    392: "But hey, it's all part of the service! Take the Bone of the Dead and Magical Wine!",
    393: "You received the Magical Wine!",
    394: "Your magical power is surging!",
    395: "It seems like you don't have any points left.",
    396: "Please come back again with more points!",
    397: "It seems like you still have some points left.",
    398: "So, why don't you try one more time?",
    399: "Try one more time? Yes No",
    400: "What a shame! Well, please come back again!",
    401: "000000001234567890- Drawing...",
    402: "Tada~, the number is...!",
    403: "And your membership number was... Number!",
    404: "...............",
    405: "What a shame! So disappointing!",
    406: "So disappointing! But you will get a participation prize!",
    407: "Tada~, the number is...!",
    408: "And your membership number was... Number!",
    409: "...............",
    410: "What a shame! So disappointing!",
    411: "So disappointing! But you will get a participation prize!",
    412: "You received Recovery Medicine!",
    414: "Explanation it is, coming right up!",
    415: "Well, the Member Number Lottery is a lottery where you draw a number, and if that number matches your membership number, you win!",
    416: "If you win, you will get the luxury prize: an Identification Bracelet! It's got a lot of thoughts stuck in it!",
    417: "However, since there is only one bracelet available, we will replace it with another prize once a winner has been chosen.",
    418: "If you miss, you will get a participation prize: Recovery Medicine. It will completely restore your energy!",
    419: "You can choose how many points to spend per lottery: 1, 3, or 5.",
    420: "The more points you use, the better your chances of winning!",
    421: "That's why you have the points! It's really simple, isn't it? Now, please draw some lots!",
    422: "Explanation it is, coming right up!",
    423: "Well, the Member Number Lottery is a lottery where you draw a number, and if that number matches your membership number, you win!",
    424: "If you win, you get the Bone of the Dead and Magical Wine! Your magical power will be surging!",
    425: "If you miss, you will get a participation prize: Recovery Medicine. It will completely restore your energy!",
    426: "You can choose how many points to spend per lottery: 1, 3, or 5.",
    427: "The more points you use, the better your chances of winning!",
    428: "That's why you have the points! It's really simple, isn't it? Now, please draw some lots!",
    429: "No lottery for you today? Then please visit us again when we are holding a lottery!",
    430: "A Helmet of Fortitude was lying in front of the eerie-looking statue.",
    431: "You picked up the Helmet of Fortitude.",
    432: "An Identification Bracelet was lying in front of the eerie-looking statue.",
    433: "You learned the Alleid Sweep Attack from the thoughts within the bracelet.",
    434: "You learned Sweep Attack.",
    435: "Lomi: Hey, did you bring something for me?",
    436: "You handed Lomi the cloth bag that you had picked up with your party of 9.",
    437: "Strangely enough, the bag did not fall through Lomi's hands.",
    438: "It's truly mine! Thank you so much!",
    439: "This is a memento of my father and mother. They gave it to me as a good luck charm.",
    440: "Lomi happily untied the bag and pulled out a red gem from inside.",
    441: "Look! Isn't it a beautiful stone?",
    442: "You picked up the stone that Lomi offered to you.",
    443: "As soon as you touched the stone, warm feelings flowed into your mind!",
    444: "You learned the Alleid Silence Breaker from the thoughts within the old sacred sword.",
    445: "You learned Silence Breaker.",
    447: "You returned the stone to Lomi.",
    448: "Oh yes, I must thank you!",
    449: "Try opening that treasure chest on top of the counter.",
    450: "You did as Lomi told you and opened the little treasure box on the counter.",
    451: "Inside the chest was a beautiful hair ornament made of precious baked silver.",
    452: "I bought this with the gold I got from working here. I mean, I got one from this store.",
    453: "When my mom was alive, she used to wear one like this all the time, and I adored it!",
    454: "Did you know that baked silver is extremely precious and hard to come by?",
    455: "I bought it, but I can't wear it, so I'm giving it to you.",
    456: "Lomi took the hair ornament out of the treasure chest and handed it to you.",
    457: "Well, be sure to come back for more fortune-telling. Bye!",
    458: "You received the Silver Hair Ornament!",
    459: "Ogre: Oh, welcome, welcome to the Medal Store!",
    460: "So, what's it gonna be?",
    461: "Oh, welcome, welcome to the Medal Store!",
    462: "This is the Medal Shop. We sell and lend various types of medals.",
    463: "Normally we operate quietly by word of mouth, but we do special business here from the 16th to the 20th of every month.",
    464: "So, what's it gonna be?",
    465: "Medal Shop Menu: Purchase Trap Game Medal Purchase Dark Medal Loan Trap Game Medal Do nothing",
    466: "Oops, sorry about that. The loan option is limited to demons only who do not possess the capital to buy one.",
    467: "If you want a medal, you can buy it instead! Now, what to do?",
    468: "Right! Well, make sure to come back then!",
    469: "The Trap Game Medal costs 5 for 1000G. Want to buy them?",
    470: "Purchase Trap Game Medals? (5 for 1000G) Yes No",
    472: "This will also net you 2 Vigger Friends Points!",
    474: "You paid 1000G.",
    475: "You received 5 Trap Game Medals!",
    477: "Hey, hey, hey, come on! You don't have enough money!",
    478: "Just so you know, I won't give you even 1G off! Don't even think about trying to cheat me!",
    479: "So, anything else?",
    480: "Oh well. (Tch, this little brat is messing with me, I'll get them next time!)",
    481: "So, anything else?",
    482: "Oh, right, a Dark Medal!",
    483: "Ah, sorry about that! We're currently out of stock on those!",
    484: "We do have Trap Game Medals though. How about it?",
    485: "The Dark Medal costs 1 for 1000G. Want to buy one?",
    486: "Purchase a Dark Medal? (1 for 1000G) Yes No",
    488: "This will also net you 2 Vigger Friends Points!",
    490: "You paid 1000G.",
    491: "You received a Dark Medal!",
    493: "Hey, hey, hey, come on! You don't have enough money!",
    494: "Just so you know, I won't give you even 1G off! Don't even think about trying to cheat me!",
    495: "So, anything else?",
    496: "Oh well. (Tch, this little brat is messing with me, I'll get them next time!)",
    497: "So, anything else?",
    498: "Oh, right, a Dark Medal!",
    499: "Ah, sorry about that! We're currently out of stock on those!",
    500: "We do have Trap Game Medals though. How about it?",
    501: "Alchemist: I am a practitioner of alchemy. I make my living by inspecting the condition of those alchemically created dolls.",
    502: "The survey is a flat 1000G, regardless of the number of dolls. I will see how far your Automata has progressed to get her own heart.",
    503: "What do you think? Let's find out how far along your Automata is in its development, shall we?",
    504: "Would you like him to take a look at your Automata? (Inspection fee: 1000G) Yes No",
    505: "I am a practitioner of alchemy. I make my living by inspecting the condition of those alchemically created dolls.",
    506: "You don't have an Automata with you, by the looks of it!",
    507: "I'm here from the 6th to the 15th of every month. If you have a doll that doesn't have a heart, bring it here.",
    508: "You paid the 1000G inspection fee.",
    509: "Since you are with the Vigger Friends, you will get 2 points credited.",
    510: "Well then, let me appraise your Automata.",
    511: "Very well. Let me appraise your Automata.",
    512: "The alchemist used a special tool to carefully examine the Automata.",
    513: "It seems that this Automata has already developed a heart of its own.",
    514: "0123456789- This Automata already has a decent amount of experience accumulated.",
    515: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    516: "Expressed in numbers, this Automata has accumulated about this much experience.",
    517: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    518: "It seems that this Automata has already developed a heart of its own.",
    519: "0123456789- This Automata already has a decent amount of experience accumulated.",
    520: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    521: "Expressed in numbers, this Automata has accumulated about this much experience.",
    522: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    523: "It seems that this Automata has already developed a heart of its own.",
    524: "0123456789- This Automata already has a decent amount of experience accumulated.",
    525: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    526: "Expressed in numbers, this Automata has accumulated about this much experience.",
    527: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    528: "It seems that this Automata has already developed a heart of its own.",
    529: "0123456789- This Automata already has a decent amount of experience accumulated.",
    530: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    531: "Expressed in numbers, this Automata has accumulated about this much experience.",
    532: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    533: "It seems that this Automata has already developed a heart of its own.",
    534: "0123456789- This Automata already has a decent amount of experience accumulated.",
    535: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    536: "Expressed in numbers, this Automata has accumulated about this much experience.",
    537: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    538: "It seems that this Automata has already developed a heart of its own.",
    539: "0123456789- This Automata already has a decent amount of experience accumulated.",
    540: "You should go to the Alchemy Guild and introduce it to Guillaume.",
    541: "Expressed in numbers, this Automata has accumulated about this much experience.",
    542: "According to my research, by the time a doll has accumulated about 1,188,000 experience points, it can have a heart of its own. Please take that as a reference.",
    543: "The alchemist finished his appraisal and took a breath.",
    544: "How's that? Are you satisfied? If you ever want another appraisal, you can come here again.",
    545: "You didn't have enough money!",
    546: "Oh, you don't have enough money. I'm not running a charity here, so I can't appraise you for free.",
    547: "When you have the funds, come back again.",
    548: "I see, you'd rather not. It is a trivial thing after all to look into their heart. If you are curious, come back again.",
    549: "I am a practitioner of alchemy. Right now, I'm currently researching the legacy of the ancient elven kingdom.",
    550: "I'm still in the process of opening my business and am not ready yet.",
    551: "When I'm ready, this store should fulfill all your alchemy needs, so please come back sometime.",
    552: "I'm still in the process of opening my business and am not ready to offer my services yet. Please come back when I'm ready.",
    553: "You met an orc who was working part-time at the Vigger Shop.",
    554: "The orc seemed to remember your face too and approached you happily.",
    555: "You know who I am, don't you? Well... I'm a part-timer!",
    556: "I'm so glad you came to see us! Were you worried? Don't worry, we'll do our best!",
    557: "And good luck to you as well, senpai!",
    558: "The orcs happily returned to exploring the floor.",
    559: "The part-timer's trust level increased by 5!",
    560: "*sniff* Oh no! It's all my fault!",
    561: "It was all because I told them to hide on the seventh floor!",
    562: "If anything happens to the princess, it will be all my fault! I might as well die too!!",
    563: "Don't worry, everything will be fine!",
    564: "Lute will be bringing Bergran with her!",
    565: "So please stop crying!",
    566: "Near the elven girl, the orc was flustered, desperately trying to soothe her.",
    567: "The orc noticed you and leaped for joy.",
    568: "Oh, we're saved!!",
    569: "Emilia: Please, please, please help us!",
    570: "Duhan is in big trouble!",
    571: "The princess has been kidnapped by that Webster bastard!",
    572: "If you don't hurry up and rescue the princess, everything will go wrong!",
    573: "We first saw him walking around with that grandpa in high spirits at that place with the Warrior God,",
    574: "and then suddenly they appeared on the 7th floor!",
    575: "So, so careless... Oh, it's all my fault... that the princess has been kidnapped.",
    576: "Oh, please! Lend us your strength! Please help us find the princess!",
    577: "Will you lend Emilia your strength? Help her Refuse",
    578: "Thank you, you have my deepest gratitude!",
    579: "Well then, Barbo, I'm going to go with them to find the princess.",
    580: "You're going to go and get Lute.",
    581: "Barbo: Understood, leave it to me!",
    582: "I'll be following you as discreetly as I can.",
    583: "Come on, we must hurry!",
    584: "If you don't want to help us, then get the hell out of here!",
    585: "Come on, Emilia, we're going to find her!",
    587: "Suddenly, Emilia emerged from the shadows.",
    588: "Emilia: You'll find Lord Webster and the alchemists in the room over there.",
    590: "Can't you sense it? I can feel a very evil power coming from over there!",
    591: "That's why I'm waiting for backup to arrive.",
    592: "You may not want to jump in too soon.",
    593: "Unless, of course, you want to die!",
    594: "Emilia said, and turned her head to the side.",
    595: "Really, I'm such a good-natured person.",
    596: "Being so nice to, and helping those who didn't even want to help me.",
    597: "I've warned you about it, so bye bye.",
    598: "Emilia went to hide herself in the shadows again.",
    599: "Emilia, who had been following you from behind, tugged at your sleeve.",
    600: "Emilia: I can still sense the princess' thoughts from this floor.",
    601: "Come on, don't dawdle here, let's go find her quickly.",
    602: "Vera: A fearsome enemy indeed!",
    603: "I never thought I'd be fighting the legendary Grim Reaper.",
    604: "But don't you think that Webster's willingness to sacrifice his own soul to achieve his goals is what makes a man a hero?",
    605: "I can't say that I dislike men like him.",
    606: "His persistence and willpower would have made him a great man, if fate hadn't crossed his path.",
    607: "That's why it's such a shame.",
    608: "Couldn't he have just put aside his grudge and found a new path?",
    609: "Or is there no way to resist fate?",
    610: "Konde: What a sad fate.",
    611: "Hatred begets hatred and creates endless tragedies.",
    612: "I know the tragedy of Kadina, because it is a famous story.",
    613: "Ortrud killed all members of the royal family and nobles of Duhan in revenge for being cut off at the battle of Banquo.",
    614: "But did Webster know about it, I wonder?",
    615: "That the Holy See actually abandoned the royal families and nobilities of Duhan in fear of reprisal from Ortrud?",
    616: "If he had known about it, would he still have allied himself with the Holy See?",
    617: "Maybe all of this would never have happened.",
    618: "It's a pity, really...",
    619: "Erika: One after another, lives are lost.",
    620: "Simson, Lord Webster, and all the others who were attracted to this labyrinth died a horrible death.",
    621: "I know it sounds crazy, but I can't help but think that this labyrinth itself is some kind of eerie entity.",
    622: "Like a demon that lures and devours everything, good and bad!",
    623: "Am I overthinking things a bit?",
    624: "But there is no other place in the world as full of death as this labyrinth.",
    625: "The darkness of the labyrinth can drive any man mad.",
    626: "I think I finally understand what Priest Fouquet was trying to tell me at the church back then.",
    627: "Iris: There is a possibility that maybe Lord Webster was set up.",
    628: "Remember when earlier, the man called Cell said that the King was aware of everything?",
    629: "It's indeed strange to assume that the man who is called the Holy King would be unaware of a rebellion in his own ranks.",
    630: "So what piece of the puzzle are we missing here?",
    631: "If they had been too uncareful, their heads could have been all on a spike by now.",
    632: "Were they actually waiting all this time for Lord Webster to turn tail?",
    633: "If that was actually the case, then they were kind of prick-teasing him.",
}

# Apply translations
count = 0
for entry in data:
    if entry.get("resource") == 1209:
        eng = entry.get("english", "")
        if any(ord(c) > 127 for c in eng):
            idx = entry["msg_index"]
            if idx in translations:
                entry["english"] = translations[idx]
                count += 1
            else:
                print(f"WARNING: No translation for msg_index {idx}", file=sys.stderr)

# Verify all 607 were fixed
remaining = sum(1 for e in data if e.get("resource") == 1209 and any(ord(c) > 127 for c in e.get("english", "")))

print(f"Fixed {count} entries")
print(f"Remaining non-ASCII R1209 entries: {remaining}")

if remaining > 0:
    for e in data:
        if e.get("resource") == 1209 and any(ord(c) > 127 for c in e.get("english", "")):
            print(f"  MISSED: idx={e['msg_index']} english={e['english'][:80]}")

# Write back
with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("File saved successfully.")
