#!/usr/bin/env python3
"""Generate batch_r39_equip_b.json - sections 8-14 of R39."""
import sys, struct, json

sys.stdout.reconfigure(encoding='utf-8')

data = open('C:/Programmieren/wizardrytranslation/extracted/packdata_raw/0039_type15.raw', 'rb').read()
with open('C:/Programmieren/wizardrytranslation/data/msg_glyph_map.json', 'r', encoding='utf-8') as f:
    gmap = json.load(f)

def decode_glyphs(indices):
    return ''.join(gmap.get(str(g), f'[{g:04X}]') for g in indices)

# Extract all messages
messages_decoded = []
pos = 2702
current_msg = []
while pos < len(data) - 1:
    val = struct.unpack('>H', data[pos:pos+2])[0]
    if val == 0xFFFF:
        if current_msg:
            messages_decoded.append(decode_glyphs(current_msg))
        else:
            messages_decoded.append('')
        current_msg = []
    else:
        current_msg.append(val)
    pos += 2
if current_msg:
    messages_decoded.append(decode_glyphs(current_msg))

translations = []

def add(msg_idx, english):
    translations.append({
        "resource": 39,
        "msg_index": 97 + msg_idx,
        "japanese": messages_decoded[msg_idx],
        "english": english
    })

# ===== SECTION 8: Quest UI strings (msgs 315-344) =====
add(315, "")
add(316, "Accept this request?")
add(317, "Abandon this request?")
add(318, "Abandoning a request will\nlower your trust rating.\nAre you sure?")
add(319, "Yes")
add(320, "No")
add(321, "Client")
add(322, "Reward")
add(323, "Estimated Deadline")
add(324, "From Acceptance")
add(325, "Day(s)")
add(326, "Cannot accept any more")
add(327, "None")
add(328, "G")
add(329, "Request Failed")
add(330, "Request Abandoned")
add(331, "Request Completed")
add(332, "Request from Citizens")
add(333, "Request from Adventurers")
add(334, "Request from Dark Street")
add(335, "Order")
add(336, "Request")
add(337, "No active requests")
add(338, "No active orders")
add(339, "Remaining")
add(340, "Deadline Passed")
add(341, "In Progress")
add(342, "Also In Progress")
add(343, "\"Accepting\"")
add(344, "Completed")

# ===== SECTION 9: Quest titles (msgs 346-379) =====
add(346, "")
add(347, "Salem Church Missionary Work")
add(348, "Recruiting Employees")
add(349, "Come to B5F")
add(350, "Kreta Spell Book Wanted")
add(351, "Gather, Janken Masters!")
add(352, "Adventurer Support Plan")
add(353, "Please Take Care of Pippi")
add(354, "Treasure of the Ancient Royal Palace")
add(355, "About Pixies")
add(356, "Give Me Medals")
add(357, "Succubus Fan Gathering")
add(358, "Land For Sale")
add(359, "Help Me!")
add(360, "Want Ingo's Key")
add(361, "If You Want Ingo's Key!")
add(362, "Search for Kunnal")
add(363, "Trap Game Contest")
add(364, "Capture the Succubus")
add(365, "Labyrinth Survey")
add(366, "Let Me Join a Party!")
add(367, "Find My Body!")
add(368, "Retrieve My Lost Item")
add(369, "Karman Guide Wanted")
add(370, "Seeking Fine Armor")
add(371, "Please Temper My Armor")
add(372, "I Want to See a Great Battle")
add(373, "Healing Spring Research")
add(374, "Healing Spring Research 2")
add(375, "Healing Spring Research 3")
add(376, "I Want to Meet Someone Possessed")
add(377, "Find My Subordinate")
add(378, "Punish the Bad Guy")
add(379, "Take Me to the Water Jar Room")

# ===== SECTION 10: SP effect descriptions (msgs 381-403) =====
add(381, "")
add(382, "All party members' MP\nfully restored.\nSP activated.")
add(383, "All party members' HP\nfully restored.\nSP activated.")
add(384, "User's max HP increased.\nSP activated.")
add(385, "User's Strength increased.\nSP activated.")
add(386, "User's Intelligence increased.\nSP activated.")
add(387, "User's Piety increased.\nSP activated.")
add(388, "User's Vitality increased.\nSP activated.")
add(389, "User's Agility increased.\nSP activated.")
add(390, "User's Luck increased.\nSP activated.")
add(391, "A dead party member\nhas been revived.\nSP activated.")
add(392, "User's alignment changed\nto Good.\nSP activated.")
add(393, "User's alignment changed\nto Neutral.\nSP activated.")
add(394, "User's alignment changed\nto Evil.\nSP activated.")
add(395, "User's trust rating\nincreased.\nSP activated.")
add(396, "User's EXP increased.\nSP activated.")
add(397, "Allied action proficiency\nincreased.\nSP activated.")
add(398, "Automater's inner EXP\nincreased. SP activated.")
add(399, "User's ability charges\nrestored. SP activated.")
add(400, "Attack power of one\nweapon increased.\nSP activated.")
add(401, "User's Defense increased.\nSP activated.")
add(402, "All party members' status\nailments cured.\nSP activated.")
add(403, "The presence of death\nhas vanished from this\nfloor due to SP.")

# ===== SECTION 11: Skill/trait names (msgs 405-425) =====
add(405, "None")
add(406, "Magic Mastery: Arcane")
add(407, "Magic Mastery: Holy")
add(408, "Dragon Hunter")
add(409, "Demon Hunter")
add(410, "Vampire Hunter")
add(411, "Inhuman Strength")
add(412, "Parry")
add(413, "Ironskin")
add(414, "Accuracy Sense")
add(415, "Vital Sense")
add(416, "Thief Eye")
add(417, "Anatomy Sense")
add(418, "Auto-Heal")
add(419, "Charisma")
add(420, "Perception")
add(421, "Weapon Sense")
add(422, "Armor Sense")
add(423, "Magic Sense")
add(424, "Status Recovery")
add(425, "Defense Sense")

# ===== SECTION 12: NPC/location names (msgs 427-440) =====
add(427, "")
add(428, "Vigor General Store")
add(429, "Miri")
add(430, "Mocchi")
add(431, "Nocchi")
add(432, "Kunnal")
add(433, "Melaanie")
add(434, "Lidi")
add(435, "Lucy")
add(436, "Yoppen")
add(437, "Mage Guild")
add(438, "Adventurer's Guild")
add(439, "Duhan Town Hall")
add(440, "Soldier Corps")

# ===== SECTION 13: Equipment categories (msgs 442-547) =====
add(442, "")
add(443, "Weapons")
add(444, "Repair Weapons")
add(445, "Self-Repair Weapons")
add(446, "Cursed Weapons")
add(447, "Unidentified Weapons")
add(448, "Armor")
add(449, "Repair Armor")
add(450, "Self-Repair Armor")
add(451, "Cursed Armor")
add(452, "Unidentified Armor")
add(453, "Accessories")
add(454, "Repair Accessories")
add(455, "Self-Repair Accessories")
add(456, "Cursed Accessories")
add(457, "Unidentified Accessories")
add(458, "Items")
add(459, "Spell Book")
add(460, "Arcane Spell Book")
add(461, "Holy Spell Book")
add(462, "Automater Chip")
add(463, "Repair Chip")
add(464, "Self-Repair Chip")
add(465, "Equipment")
add(466, "Repair Equipment")
add(467, "Self-Repair Equipment")
add(468, "Cursed Equipment")
add(469, "Unidentified Equipment")
add(470, "Dagger")
add(471, "Shortsword")
add(472, "Longsword")
add(473, "Greatsword")
add(474, "Katana")
add(475, "Wand")
add(476, "Handaxe")
add(477, "Greataxe")
add(478, "Shuriken")
add(479, "Mace")
add(480, "Flail")
add(481, "Throwing Knives")
add(482, "Crossbow")
add(483, "Longbow")
add(484, "Cudgel")
add(485, "Poleaxe")
add(486, "Knuckles")
add(487, "? Shortsword")
add(488, "? Shuriken")
add(489, "? Katana")
add(490, "? Wand")
add(491, "? Axe")
add(492, "? Weapon")
add(493, "? Mace")
add(494, "? Flail")
add(495, "? Bow")
add(496, "? Cudgel")
add(497, "Helmet")
add(498, "Robe")
add(499, "Shield")
add(500, "Gauntlets")
add(501, "? Helmet")
add(502, "? Robe")
add(503, "? Shield")
add(504, "? Gauntlets")
add(505, "Amulet")
add(506, "Ring")
add(507, "Necklace")
add(508, "Gemstone")
add(509, "Boots")
add(510, "Cloak")
add(511, "? Amulet")
add(512, "? Ring")
add(513, "? Necklace")
add(514, "? Gemstone")
add(515, "? Boots")
add(516, "? Cloak")
add(517, "Hand Chip")
add(518, "? Hand Chip")
add(519, "Body Chip")
add(520, "? Body Chip")
add(521, "Arm Chip")
add(522, "? Arm Chip")
add(523, "Leg Chip")
add(524, "? Leg Chip")
add(525, "Brain Chip")
add(526, "? Brain Chip")
add(527, "Lv1 Spell Book")
add(528, "Lv2 Spell Book")
add(529, "Lv3 Spell Book")
add(530, "Lv4 Spell Book")
add(531, "Lv5 Spell Book")
add(532, "Lv6 Spell Book")
add(533, "Lv7 Spell Book")
add(534, "Lv1 Arcane Spell Book")
add(535, "Lv2 Arcane Spell Book")
add(536, "Lv3 Arcane Spell Book")
add(537, "Lv4 Arcane Spell Book")
add(538, "Lv5 Arcane Spell Book")
add(539, "Lv6 Arcane Spell Book")
add(540, "Lv7 Arcane Spell Book")
add(541, "Lv1 Holy Spell Book")
add(542, "Lv2 Holy Spell Book")
add(543, "Lv3 Holy Spell Book")
add(544, "Lv4 Holy Spell Book")
add(545, "Lv5 Holy Spell Book")
add(546, "Lv6 Holy Spell Book")
add(547, "Lv7 Holy Spell Book")

# ===== SECTION 14: Party rank messages (msgs 549-558) =====
add(549, "None")
add(550, "Party rank has become\n[Disabled].\n[AA] can no longer be used.")
add(551, "AA can no longer be used.")
add(552, "Party rank [Disabled]\nhas been restored.")
add(553, "A party rank has been\nestablished!")
add(554, "A party rank has been\nremoved!\n[AA] can no longer be used.")
add(555, "[Allied Points] have\nincreased!")
add(556, "[Allied Points] have\ndecreased!")
add(557, "[Some of AA's parts have\nbeen removed.]")
add(558, "")

# Write output
outpath = 'C:/Programmieren/wizardrytranslation/data/type2_translated/batch_r39_equip_b.json'
with open(outpath, 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"Wrote {len(translations)} translations to batch_r39_equip_b.json")
indices = [t["msg_index"] for t in translations]
print(f"msg_index range: {min(indices)} to {max(indices)}")
