import json, re

data = json.load(open('C:/Programmieren/wizardrytranslation/data/type2_translation_batches/batch_06_R1208_R1209.json', encoding='utf-8'))

# Hand translations keyed by (resource, msg_index)
HAND = {
    # ── LEVER MECHANICS (B6F dungeon) ──
    (1208, 0): "The medal from defeating / the floor boss was / offered to the gods.",
    (1208, 1): "The lever is ON. / Do you want to use it? / Yes  No",
    (1208, 2): "Turned the lever OFF.",
    (1208, 3): "The lever is OFF. / Do you want to use it? / Yes  No",
    (1208, 4): "Turned the lever ON.",
    (1208, 5): "The lever is ON. / Do you want to use it? / Yes  No",
    (1208, 6): "Turned the lever OFF.",
    (1208, 7): "The lever is OFF. / Do you want to use it? / Yes  No",
    (1208, 8): "Turned the lever ON.",
    (1208, 9): "The lever is ON. / Do you want to use it? / Yes  No",
    (1208, 10): "Turned the lever OFF.",
    (1208, 11): "The lever is OFF. / Do you want to use it? / Yes  No",
    (1208, 12): "Turned the lever ON.",
    (1208, 13): "The lever is locked / and won't move.",
    (1208, 14): "Do you want to use / the lever? / Yes  No",
    # ── PRINCESS ORIANA SCENE ──
    (1208, 16): "\"Good, you made it / this far.\"",
    (1208, 17): "When you crossed the / bridge earlier, there / were no signs of life,",
    (1208, 18): "but suddenly, a / black-clad figure drew / a blade from the shadows.",
    (1208, 19): "\"Traveler, forgive me, / but you must die here.\"",
    (1208, 20): "\"You probably came / here unknowing, but you / should turn back now.\"",
    (1208, 21): "The figure spoke as / though burdened by an / immense secret.",
    (1208, 22): "A voice full of / barely contained / sorrow could be heard.",
    (1208, 23): "The black-clad figure / began to move slowly.",
    (1208, 24): "Its movement was as / if to conceal / something precious.",
    (1208, 26): "From beyond the door, / a young woman's voice / could be heard.",
    (1208, 27): "The figure quickly / sheathed its blade and / stepped aside.",
    (1208, 28): "\"Sir Knight, please / do come in.\"",
    (1208, 29): "The traveler silently / nodded and said / \"Come in.\"",
    (1208, 30): "\"Are you hurt, / young lady?\"",
    (1208, 31): "Before their eyes / stood a weary young / woman in tattered robes.",
    (1208, 33): "\"They turned their / blades against me. / All fault lies with me.\"",
    (1208, 34): "\"I am...I am / Oriana!\"",
    (1208, 35): "\"The first princess of / the Duhan royal family, / presumed dead.\"",
    (1208, 36): "\"You must not say / that any further. / Everything will unravel.\"",
    (1208, 37): "\"Oriana, I know you / have been secretly / protecting me.\"",
    (1208, 38): "\"Enough. I do not / wish to see anyone / suffer because of me.\"",
    (1208, 39): "\"Besides, I am tired / of running any / further than this.\"",
    (1208, 40): "\"I am grateful for / everything you have / done until now.\"",
    (1208, 41): "\"But with the Duhan / royal court in such / a state as this,\"",
    (1208, 42): "\"it is unforgivable / that I alone should / be hiding like this.\"",
    (1208, 43): "\"Even if I am killed, / I wish to fulfill my / duty as a princess.\"",
    (1208, 44): "Lord Webster is / scheming in secret.",
    (1208, 45): "\"Just a little more. / His faction will / crumble soon enough.\"",
    (1208, 46): "\"If you go out now, / all our efforts will / have been for nothing.\"",
    (1208, 47): "\"Please, have / patience.\"",
    (1208, 48): "\"I understand. But / it is enough now.\"",
    (1208, 49): "\"I cannot bear that / you and the knights / suffer for hiding me.\"",
    (1208, 50): "\"Unable even to / complain, forced to / die...how great is\"",
    (1208, 51): "\"your sacrifice? Those / who should be Duhan's / treasure die for me.\"",
    (1208, 52): "\"When I think of it, / the grief is enough / to tear my heart apart.\"",
    (1208, 53): "\"Don't worry about us. / The late king and you / treated us as people.\"",
    (1208, 54): "\"Laying down our lives / for you is only / natural.\"",
    (1208, 55): "\"No one has died / with regrets.\"",
    (1208, 56): "\"No, enough. If Lord / Webster wants my life, / I shall offer it.\"",
    (1208, 57): "\"Now, please escort / me to the palace. / That will end it all.\"",
    # ── LUTE ARRIVES ──
    (1208, 59): "\"Your Highness, / bad news! Lord Webster / is heading this way!\"",
    (1208, 60): "Lute burst into / the room.",
    (1208, 61): "Lute saw the / black-clad figure's / blade and froze.",
    (1208, 62): "\"Don't worry, / we're allies.\"",
    (1208, 63): "\"Now that Webster's / schemes are exposed, / there's no reason to\"",
    (1208, 64): "\"hide the princess in / this labyrinth. So / I came to escort her.\"",
    (1208, 65): "\"So, is what she / said true?\"",
    (1208, 66): "\"Is it true that / Lord Webster is / heading this way?\"",
    (1208, 67): "\"Yes, that's right. / That's why I hurried / back here.\"",
    (1208, 68): "Lute said this and / turned to face / the princess.",
    (1208, 69): "\"Now, Your Highness, / please hurry!\"",
    (1208, 70): "\"We're also preparing / to bring the princess / back to town safely.\"",
    (1208, 71): "\"Until then, please / keep the princess / hidden somewhere.\"",
    (1208, 72): "\"First, we need / to assess how Lord / Webster will move.\"",
    (1208, 73): "The black-clad figure / left without a word.",
    (1208, 74): "Lute: \"Webster is / coming! Let's go, / Your Highness!\"",
    (1208, 75): "\"Forgive the trouble. / I shall repay this / kindness someday.\"",
    (1208, 76): "Princess Oriana bowed / slightly and left / with Lute.",
    # ── INVESTIGATION MENU (skip) ──
    (1208, 77): "[DATA]",
    # ── KUNNAL SCENE ──
    (1208, 78): "Kunnal stood in the / middle of a clearing, / gazing up and muttering.",
    (1208, 79): "\"This place too! / It's the same! / This must be it!\"",
    (1208, 80): "\"I keep seeing a / place just like this / in my dreams.\"",
    (1208, 81): "\"Elves in dazzling / robes, dancing with / beautiful voices!\"",
    (1208, 82): "\"When I first saw my / dream, I named this / place Diarant, the\"",
    (1208, 83): "\"kingdom of elves! / The face of the girl / on B3F looked just\"",
    (1208, 84): "\"like the Elf King! / Along with the King's / powers, the magical\"",
    (1208, 85): "\"beings appeared too! / But they weren't / monsters--they had\"",
    (1208, 86): "Kunnal closed his / eyes, lost deep / in fantasy.",
    (1208, 88): "After a while, / Kunnal finally / noticed you.",
    (1208, 90): "\"My dream is great, / isn't it! You normal / folks can't even see\"",
    (1208, 92): "You told Kunnal that / Melanie and the / others are looking.",
    (1208, 93): "\"Oh, they're not here? / Where are they?\"",
    (1208, 94): "You explained their / location.",
    (1208, 95): "\"What, they're there? / It's too far to go / back now, what a pain!\"",
    (1208, 96): "\"I don't want to / stare at this dark / place forever.\"",
    (1208, 97): "\"This is exactly / like my dream. Deeper / in, there should be\"",
    (1208, 98): "\"I must go deeper / and see it with / my own eyes.\"",
    (1208, 99): "\"Sorry but I'll leave / the girls to you.\"",
    (1208, 100): "\"Well, whether you / help them or leave them / is up to you!\"",
    (1208, 101): "\"If you make Melanie / cry, you'll definitely / get her wrath!\"",
    (1208, 103): "Kunnal chanted a / spell and vanished.",
    (1208, 104): "Vigger Shop branch / store on labyrinth / B6F is now open!",
    # ── TWO WOMEN CHATTING ──
    (1208, 105): "Arguing voices can / be heard from beyond / the door!",
    (1208, 106): "Girl A: \"Honestly, that / fool is hopeless.\" / Girl B: \"You kept calling / him a fool, so he / ran off, didn't he?\" / Girl A: \"I only told / the truth! If he gets / upset over that, / it's his problem!\"",
    (1208, 107): "Girl B: \"Even fools / have their uses! He / had one good quality: / endurance.\" / Girl A: \"True. Thanks to / him carrying stuff, / we never have to go / back to town.\" / Girl B: \"Right!\"",
    (1208, 108): "Girl A: \"But wandering / this scary place / alone is insane! / I refuse!\" / Girl B: \"Then what do / we do?\" / Girl A: \"Hmm! Let's go / back to town and post / a request! If only / some strong adventurer / would pass by...\"",
    (1208, 109): "Their sighs faded / into the silence.",
    # ── MELANIE & MIRI ──
    (1208, 110): "Miri & Melanie: / \"Ah!\"",
    (1208, 111): "The moment you / entered the room, / Melanie and Miri / cried out in surprise.",
    (1208, 112): "\"Whoa, your timing / is perfect!\"",
    (1208, 113): "\"We were just wishing / for someone strong / like you to show up!\"",
    (1208, 114): "...............",
    (1208, 115): "\"So that fool-- / I mean Kunnal-- / just wandered off!\"",
    (1208, 116): "\"He was acting weird / from the moment we / got to this floor.\"",
    (1208, 117): "\"But it's our first / time here, so we're / totally lost!\"",
    (1208, 118): "Miri nodded at / Melanie, and Melanie / agreed vigorously.",
    (1208, 119): "\"You get what we're / saying, right!?\"",
    (1208, 120): "\"Great! If you look / for him, finding / Kunnal is as good\"",
    (1208, 121): "\"as done! And with / Kunnal, we don't / even need an escort.\"",
    (1208, 122): "\"We'll wait here, / so hurry up and / bring him back!\"",
    (1208, 123): "\"Wait, what!? / What do you mean!?\"",
    (1208, 124): "\"If you won't look / for him, then bring / someone who will!\"",
    (1208, 125): "\"And this isn't a / request, it's an / order!\"",
    (1208, 126): "\"Hmph, so you / realized finding / Kunnal is your job?\"",
    (1208, 127): "\"Well? What'll / it be?\"",
    (1208, 128): "\"Great! If you look / for him, finding / Kunnal is as good\"",
    (1208, 129): "\"as done! And with / Kunnal, we don't / even need an escort.\"",
    (1208, 130): "\"We'll wait here, / so hurry up and / bring him back!\"",
    (1208, 131): "\"No matter how many / times, the answer / is no!\"",
    (1208, 132): "\"Fine, we'll wait / here for a while, / so think it over!\"",
    (1208, 133): "Melanie and Miri / were still resting / in the room.",
    (1208, 134): "\"Hey, are you done / yet? Hurry up!\"",
    (1208, 135): "You calmed Miri down / and told them you / found Kunnal.",
    (1208, 136): "\"Whaaat!? And you / just let him go / without stopping him!?\"",
    (1208, 137): "How do you answer? / Yes  No",
    (1208, 138): "\"What are you gonna / do!? That fool was / great at carrying!\"",
    (1208, 139): "\"Hmph, even if you / stopped him, he's not / here, so oh well.\"",
    (1208, 140): "\"What are you gonna / do!? That fool was / great at carrying!\"",
    (1208, 141): "Miri seems truly / angry.",
    (1208, 142): "\"Hey, what do we do? / We can't continue / like this!\"",
    (1208, 143): "\"Oh no! We need to / find someone who can / fight!\"",
    (1208, 144): "\"Without a pack / mule...!\"",
    (1208, 145): "\"There aren't many / of those! That guy's / only virtue was\"",
    (1208, 146): "\"Ah well, whatever. / If we stick around, / monsters will attack!\"",
    (1208, 147): "\"Melanie, let's go / back to town. If we / post a request,\"",
    (1208, 148): "\"Yeah..........\"",
    (1208, 149): "\"Honestly, this is / all your fault!\"",
    (1208, 150): "\"Let's go, Melanie!\"",
    (1208, 151): "\"Y-Yeah! / G-Goodbye!\"",
    (1208, 152): "They left the room!",
    (1208, 153): "Vigger Friends points / increased by 3!",
    (1208, 154): "Party HP and MP / fully restored!",
    (1208, 155): "Vigger Friends points / increased by 3!",
    # ── VIGGER BRANCH SHOP / REST EVENT ──
    (1208, 156): "After spacing out / for a while, you / started feeling drowsy.",
    (1208, 157): "As your consciousness / fades, you see / monster silhouettes.",
    (1208, 158): "Before you can tell / dream from reality, / the monsters attack!",
    (1208, 159): "Orc: After the battle, / the branch shop owner / came running over.",
    (1208, 160): "\"Whoaaa, are ya / alright there!?\"",
    (1208, 161): "\"Our shop gets / attacked by scary / monsters sometimes!\"",
    (1208, 162): "\"Ya wouldn't wake up, / so we left ya behind / when we evacuated!\"",
    (1208, 163): "\"Well, glad yer safe! / C'mon, take another / rest, nice 'n easy!\"",
    (1208, 164): "\"But be careful, / don't doze off!\"",
    (1208, 165): "Party HP and MP / fully restored!",
    # ── LUCY VISITS BRANCH ──
    (1208, 166): "Lucy visited the / Vigger Shop branch / store for the first time.",
    (1208, 167): "What was once an / empty room now had / proper shop fittings.",
    (1208, 168): "At the counter sat / a monster hired / as a shopkeeper.",
    (1208, 169): "Lucy and the monster / were having a chat.",
    (1208, 170): "Lucy noticed you, / stepped out from the / counter and walked over.",
    (1208, 171): "\"Came to check out / the place? Me too!\"",
    (1208, 172): "\"It's our only branch / store. I hired an / adventurer to escort\"",
    (1208, 173): "\"It was nerve-wracking, / but worth the trip. / I'm so impressed!\"",
    (1208, 174): "\"We got this far / thanks to you. / I really appreciate it!\"",
    (1208, 175): "\"So buy lots to make / it even bigger!\"",
    (1208, 176): "\"Well, time to head / back to town. The / return trip is easy\"",
    (1208, 177): "\"I wish someone / would build a portal / for the branch store!\"",
    (1208, 178): "\"Bye! Come visit / the main store too, / not just the branch!\"",
    (1208, 179): "Lucy waved, pulled a / key from her bag, / and vanished.",
    (1208, 180): "And with that, she / disappeared from sight.",
    # ── LOST & FOUND / IMP SPACE ──
    (1208, 181): "A space behind the / shop counter had been / sectioned off.",
    (1208, 182): "A sign by the / entrance reads: / \"Lost & Found\".",
    (1208, 183): "A sign on the / counter reads: / \"Lost & Found OPEN! / Vigger Friends / new member signup!\"",
    (1208, 184): "The Imp standing in / the space noticed / you and called out.",
    (1208, 185): "The Lost & Found / has a sign reading: / \"Vigger Friends / enrollment open!\"",
    (1208, 186): "The Imp standing in / the space called out.",
    (1208, 187): "\"Aha! I bet you're / interested in / Vigger Friends!\"",
    (1208, 188): "\"No need to be shy! / Who wouldn't be / interested in such\"",
    (1208, 189): "\"Want an explanation / of Vigger Friends? / Or sign up right away?\"",
    (1208, 190): "What will you do? / Hear explanation / Sign up now / Do nothing",
    (1208, 191): "\"Alright then! / Let me explain / the system!\"",
    (1208, 192): "\"Feel free to only / half-listen. I'll give / you a pamphlet too!\"",
    (1208, 194): "\"Here we go!\"",
    (1208, 195): "\"Vigger Friends is / a club to help grow / Vigger Shop together!\"",
    (1208, 196): "\"Members who pay the / enrollment fee get / exclusive services!\"",
    (1208, 197): "\"The Lost & Found / has special Vigger / Friends member events!\"",
    (1208, 198): "\"The more events you / join, the more chances / for a lucky number\"",
    (1208, 199): "\"You gotta join! / I'm a member too, / a hardcore one!\"",
    (1208, 200): "\"Signing up? That'll / be 5000G enrollment / fee plus your name!\"",
    (1208, 201): "\"What, you don't / wanna? Don't be / shy now!\"",
    (1208, 202): "\"Please join next / time, bro!\"",
    (1208, 203): "\"What, you don't / wanna? Don't be / shy now!\"",
    (1208, 204): "\"Please join next / time, sis!\"",
    (1208, 205): "Sign up? / \"Fee: 5000G\" / Yes  No",
    (1208, 206): "\"Alright, let me / collect the fee!\"",
    (1208, 207): "Paid 5000G.",
    (1208, 208): "\"Confirmed! Here's / your Vigger Friends / membership card!\"",
    (1208, 209): "0123456789-000000 / \"Your member number / is shown on the / card!\"",
    (1208, 210): "\"Thank you very / much!\"",
    (1208, 211): "Obtained member card!",
    (1208, 212): "\"Alright, let me / collect the fee!\"",
    (1208, 213): "\"What!? You don't / have 5000G!? That's / rough, buddy!\"",
    (1208, 214): "\"No way! Next time / bring 5000G or / more, alright?\"",
    (1208, 215): "\"Until then, no / membership!\"",
    (1208, 216): "\"What, you don't / wanna? Don't be / shy now!\"",
    (1208, 217): "\"Please join next / time, bro!\"",
    (1208, 218): "\"What, you don't / wanna? Don't be / shy now!\"",
    (1208, 219): "\"Please join next / time, sis!\"",
    (1208, 220): "The Lost & Found / has a sign reading: / \"Vigger Friends / enrollment open!\"",
    (1208, 221): "The Imp standing in / the space called out.",
    (1208, 222): "0123456789-000000 / \"Welcome, member / number !\"",
    (1208, 223): "\"Days 1-5 of each / month is the Vigger / Friends enrollment\"",
    (1208, 224): "\"So no events / right now.\"",
    (1208, 226): "A board reads: / \"Currently very busy. / Please come back later.\"",
    (1208, 227): "A board reads: / \"Currently very busy. / Please come back later.\"",
    # ── ROMY THE GHOST ──
    (1208, 228): "????? / Romy: \"Hi there! / Want me to tell / your fortune?\"",
    (1208, 229): "A board reads: / \"For those chosen by / destiny, I shall / tell your fortune.\"",
    (1208, 230): "But no one is at / the fortune counter.",
    (1208, 233): "A playful voice / comes from somewhere.",
    (1208, 234): "You looked around / but couldn't find / the source.",
    (1208, 235): "Looking at the / counter again, a / faint figure appeared.",
    (1208, 236): "\"Poor thing. Leader / but with nothing!\"",
    (1208, 237): "\"If you're going to / complain, complain / to destiny, not me.\"",
    (1208, 238): "\"Good for you! / Your talent has / already bloomed!\"",
    (1208, 239): "\"Good for you! / Nothing yet, but / hidden talent will / surely bloom!\"",
    (1208, 240): "\"I hope it blooms / while you're still / alive.\"",
    (1208, 241): "\"I'm Romy, the ghost. / Pay 2000G and I'll / tell you more.\"",
    (1208, 242): "Have your fortune / told? \"Fee: 2000G\" / Yes  No",
    (1208, 243): "\"Put the money on / the counter. My hands / pass right through.\"",
    (1208, 244): "Not enough money.",
    (1208, 245): "\"Nope, no discounts!\"",
    (1208, 246): "\"If you don't have / the money, bring / 2000G next time.\"",
    (1208, 247): "Paid 2000G.",
    (1208, 248): "\"Thank you! / Who shall I read?\"",
    (1208, 249): "\"Thank you! I'll add / 4 Vigger Friends / points too.\"",
    (1208, 250): "\"So, who shall / I read?\"",
    (1208, 251): "\"Fine! Whatever!\"",
    (1208, 252): "Romy said that and / vanished again.",
    (1208, 253): "Have your fortune / told?",
    # ── ROMY'S TALENT READINGS (various classes) ──
    (1208, 254): "'s talent has / already bloomed.",
    (1208, 255): "The talent hidden / within !",
    (1208, 266): "Good that you have / talent. Learning many / spells sounds amazing.",
    (1208, 267): "Good that you have / talent. If attack / magic is your thing,",
    (1208, 268): "Good that you have / talent. Taming a / dragon? That's so cool!",
    (1208, 269): "Good that you have / talent. Being good at / slaying demons makes",
    (1208, 270): "Good that you have / talent. Please don't / reveal mine! I'm dead!",
    (1208, 271): "Good that you have / talent. But you look / a bit scary...",
    (1208, 272): "Good that you have / talent. Don't just / take hits, attack too!",
    (1208, 273): "Good that you have / talent. Amazing, / same level as me!",
    (1208, 274): "Good that you have / talent. Making few / mistakes is great!",
    (1208, 275): "Good that you have / talent. I have no / sense, but monsters",
    (1208, 276): "Good that you have / talent. Good at / finding items? Give",
    (1208, 277): "Good that you have / talent. Don't defeat / me--I won't drop",
    (1208, 278): "[DATA]",
    (1208, 279): "Good that you have / talent. But having / presence doesn't mean",
    (1208, 280): "Good that you have / talent. Just because / you're good at running",
    (1208, 281): "Good that you have / talent. Turning / everything to stone?",
    (1208, 282): "Good that you have / talent. Turning / all to ash? Just don't",
    (1208, 283): "Good that you have / talent. Such power! / You could become a",
    (1208, 284): "Good that you have / talent. Healing / yourself? That goes",
    (1208, 285): "Good that you have / talent. Drawing out / the power of ash--",
    (1208, 286): "\"Nothing! I see / nothing at all!\"",
    (1208, 287): "...............",
    (1208, 288): "\"Don't be sad. Most / people in this world / are ordinary.\"",
    (1208, 289): "\"Because if everyone / had talent, that / would be 'normal'.\"",
    (1208, 290): "\"Only a very few / people are born / with talent.\"",
    (1208, 291): "\"Normal is normal, / it doesn't mean / you're inferior.\"",
    # ── ROMY'S SPECIFIC READINGS (292-340 are class-specific fortune readings) ──
    (1208, 292): "\"You grow by reading / widely and absorbing / all sorts of knowledge.\"",
    (1208, 293): "\"Your talent works / best with deep wisdom, / so study hard.\"",
    (1208, 294): "\"Your talent is / deeply tied to / your faith.\"",
    (1208, 295): "\"If you live with / stronger faith, good / things will surely come.\"",
    (1208, 296): "\"Stand firm against / even the mightiest / monsters. That's key.\"",
    (1208, 297): "\"You may lose your / life sometimes, but / that's good experience.\"",
    (1208, 298): "\"Eventually you'll / charge at dangerous / monsters willingly.\"",
    (1208, 299): "\"You have the eye of / a demon slayer / within you.\"",
    (1208, 300): "\"Once awakened, it / will become a / fearsome weapon.\"",
    (1208, 301): "\"A dangerous person! / Dead! Don't be afraid / of the big dead ones.\"",
    (1208, 302): "\"In time, they won't / be scary at all-- / you might even like it.\"",
    (1208, 303): "\"Your sensory / abilities seem good.\"",
    (1208, 304): "\"Rather than magic, / honing your body / will unlock potential.\"",
    (1208, 305): "\"Movements that were / too fast to see / will start feeling\"",
    (1208, 306): "\"Your reflexes are / naturally gifted. / Just keep training them.\"",
    (1208, 307): "\"You have strong / vitality.\"",
    (1208, 308): "\"If trained further, / you could gain an / incredibly tough body.\"",
    (1208, 309): "\"Your intuition / is sharp, and you're / quite perceptive.\"",
    (1208, 310): "\"Your desire to / read ahead will / keep growing.\"",
    (1208, 311): "\"Eventually, you'll / sense enemy moves / and avoid mistakes.\"",
    (1208, 312): "\"You seem good at / grasping the timing / of opportunities.\"",
    (1208, 313): "\"Once it awakens, / you'll sense weak / points and strike fast.\"",
    (1208, 314): "\"I sense something / truly remarkable / in your specialty.\"",
    (1208, 315): "\"You'll start noticing / things that ordinary / people would miss.\"",
    (1208, 316): "\"I don't know your / job, but I think / disarming traps\"",
    (1208, 317): "\"Even if you've never / tried it, you might / be surprisingly good.\"",
    (1208, 318): "\"So perhaps a new / criminal-like talent / may emerge in you.\"",
    (1208, 319): "\"You might come to / love extracting / monster parts.\"",
    (1208, 320): "[DATA]",
    (1208, 321): "\"You could become / a mood maker, the / kind who lifts spirits.\"",
    (1208, 322): "\"No matter how dire / things get, people / won't feel down.\"",
    (1208, 323): "\"Well, being popular / is a talent too. / Better than being hated.\"",
    (1208, 324): "\"You're very / sensitive.\"",
    (1208, 325): "\"If you polish that / sensitivity, your / foresight will grow.\"",
    (1208, 326): "\"In battle, having / an unrelated weapon / won't draw out power.\"",
    (1208, 327): "\"Normally you don't / use ill-fitting gear, / but you're different.\"",
    (1208, 328): "\"Your talent is still / dormant, but soon / you'll wield anything.\"",
    (1208, 329): "\"For things you wear, / an unrelated item / normally won't help.\"",
    (1208, 330): "\"Normally you don't / equip ill-fitting / gear, but you differ.\"",
    (1208, 331): "\"Your talent is still / dormant, but soon / anything you wear\"",
    (1208, 332): "\"Deep within your / body, I sense a / great magical power.\"",
    (1208, 333): "\"You're the cautious / type, so don't push / yourself too hard yet.\"",
    (1208, 334): "\"Once your talent / blooms, your magic / will grow rapidly.\"",
    (1208, 335): "\"Your body recovers / faster than anyone / else's.\"",
    (1208, 336): "\"Eventually, even / injured, you might / heal just by waiting.\"",
    (1208, 337): "\"Of course, not / getting hurt in / the first place is best.\"",
    (1208, 338): "\"Your talent is in / drawing out the power / of objects, not self.\"",
    (1208, 339): "\"How to put it... / you understand items / better than people.\"",
    (1208, 340): "\"Anyway, you'll / notice it as soon as / your talent blooms.\"",
    (1208, 341): "Romy's form / flickered for a moment.",
    (1208, 342): "\"Oh! I'm getting / tired.\"",
    (1208, 343): "\"I need to rest. / Come back later if / you want more readings.\"",
    (1208, 345): "\"Phew! I'm a bit / tired. Fortune- / telling drains me.\"",
    (1208, 346): "\"I have no body, / so it's really hard. / I can only do one\"",
    (1208, 347): "\"I need to rest. / Come back later if / you want more readings.\"",
    (1208, 349): "Romy vanished.",
    # ── IMP / LOTTERY ──
    (1208, 350): "Imp: \"Welcome, / welcome!\"",
    (1208, 351): "\"Days 26-30 are / the Vigger Friends / member number lottery!\"",
    (1208, 352): "\"Hey, you're not a / member? The lottery / is members only!\"",
    (1208, 353): "\"Vigger Friends / enrollment is days / 1-5 at this counter!\"",
    (1208, 354): "\"Please come back!\"",
    (1208, 355): "0123456789-0123456789- / \"Hey there, member / number !\"",
    (1208, 356): "\"Hold on, let me / check your Friend / Points...\"",
    (1208, 358): "\"Oops, you don't / have enough points!\"",
    (1208, 359): "\"You need at least / 1 point minimum / to enter the lottery!\"",
    (1208, 360): "\"Join Lost & Found / events more often / to earn points!\"",
    (1208, 361): "\"Alright, you're / all set! What'll / you do?\"",
    (1208, 362): "What will you do? / \"Cost: Points\" / 1 point / Hear rules / Don't play",
    (1208, 363): "What will you do? / \"Cost: Points\" / 1 point / 3 points / Hear rules / Don't play",
    (1208, 364): "What will you do? / \"Cost: Points\" / 1 point / 3 points / 5 points / Hear rules / Don't play",
    (1208, 365): "\"1 point received! / And now...the number / lottery begins!!\"",
    (1208, 366): "\"3 points received! / And now...the number / lottery begins!!\"",
    (1208, 367): "\"5 points received! / And now...the number / lottery begins!!\"",
    (1208, 369): "\"Ta-daa! The number / is...!\"",
    (1208, 370): "\"Your member number / is...!\"",
    (1208, 371): "...............",
    (1208, 372): "\"We have a / WIIIINNNNEEERRR!!\"",
    (1208, 373): "The Imp warmly / celebrated by tossing / confetti into the air!",
    (1208, 374): "\"Wow, nice! You're / actually the first / winner ever!\"",
    (1208, 375): "\"So here's the grand / prize! An Identify / Bracelet!\"",
    (1208, 376): "Obtained Identify / Bracelet!",
    (1208, 377): "From the memories / within the bracelet, / you learned a new Alleid!",
    (1208, 378): "Learned Warp Attack!",
    (1208, 379): "\"From now on, prizes / are Dragon Bone / and Magic Wine!\"",
    (1208, 380): "\"Wow, winning so / often! You're killing / my business here!\"",
    (1208, 381): "\"But hey, service is / service! Have a / Dragon Bone and\"",
    (1208, 382): "Obtained Magic Wine!",
    (1208, 383): "\"Your magic power / is tingling!\"",
    (1208, 384): "\"You're out of / points already.\"",
    (1208, 385): "\"Earn more points / and come back!\"",
    (1208, 386): "\"Oh, you still have / points left!\"",
    (1208, 387): "\"Wanna try one / more time?\"",
    (1208, 388): "Play the lottery / again? Yes  No",
    (1208, 389): "\"Too bad! / Come back again!\"",
    (1208, 390): "0000000123456789- / Drawing...",
    (1208, 391): "\"Ta-daa! The number / is...!\"",
    (1208, 392): "\"Your member number / is...!\"",
    (1208, 393): "...............",
    (1208, 394): "\"Better luck / neeeext tiiiime!!\"",
    (1208, 395): "\"Aww, too bad! / Here's a consolation / prize!\"",
    (1208, 396): "\"Ta-daa! The number / is...!\"",
    (1208, 397): "\"Your member number / is...!\"",
    (1208, 398): "...............",
    (1208, 399): "\"Better luck / neeeext tiiiime!!\"",
    (1208, 400): "\"Aww, too bad! / Here's a consolation / prize!\"",
    (1208, 401): "Obtained Potion of / Recovery!",
    (1208, 403): "\"Want an explanation? / Here goes!\"",
    (1208, 404): "\"The number lottery / draws a number. If it / matches your member\"",
    (1208, 405): "\"number, you win! / Grand prize: Identify / Bracelet with memories!\"",
    (1208, 406): "\"Only one bracelet / exists, so after / someone wins, prizes\"",
    (1208, 407): "\"Even losing gets / you a Potion of / Recovery! Not bad, huh?\"",
    (1208, 408): "\"You can choose to / spend 1, 3, or 5 / points per draw!\"",
    (1208, 409): "\"More points spent / means better odds / of winning!\"",
    (1208, 410): "\"Great deal, right? / Now go ahead and / play the lottery!\"",
    (1208, 411): "\"Want an explanation? / Here goes!\"",
    (1208, 412): "\"The number lottery / draws a number. If it / matches your member\"",
    (1208, 413): "\"number, you win! / Grand prize: Dragon / Bone and Magic Wine!\"",
    (1208, 414): "\"Even losing gets / you a Potion of / Recovery! Not bad, huh?\"",
    (1208, 415): "\"You can choose to / spend 1, 3, or 5 / points per draw!\"",
    (1208, 416): "\"More points spent / means better odds / of winning!\"",
    (1208, 417): "\"Great deal, right? / Now go ahead and / play the lottery!\"",
    (1208, 418): "\"Not playing? Well, / come back when the / lottery's running!\"",
    # ── ROMY'S QUEST (hair ornament) ──
    (1208, 419): "Romy: \"Hi! Did you / bring it for me?\"",
    (1208, 420): "You handed Romy the / package found on B9F.",
    (1208, 421): "Miraculously, it / passed through to / Romy's hands.",
    (1208, 422): "\"It's mine! / Thank you so much!\"",
    (1208, 423): "\"This is a memento / of my mom and dad. / They gave it to me.\"",
    (1208, 424): "Romy happily untied / the package and / pulled out a white sword.",
    (1208, 425): "\"Hehe! Pretty / sword, right?\"",
    (1208, 426): "You took the sword / that Romy offered.",
    (1208, 427): "The instant you / touched the sword, / a warm sensation / flooded your mind!",
    (1208, 428): "From the memories / within the white / sword, you learned / a new Alleid!",
    (1208, 429): "Learned Break Silence!",
    (1208, 431): "Returned the sword / to Romy.",
    (1208, 432): "\"Oh! I almost / forgot!\"",
    (1208, 433): "\"Open the treasure / chest below / the counter.\"",
    (1208, 434): "You opened the small / chest below the / Lost & Found counter.",
    (1208, 435): "Inside was a / beautiful hair / ornament made of / rare baked silver.",
    (1208, 436): "\"I bought this with / the money I earned / here. Well, the shop\"",
    (1208, 437): "\"When I was alive, / Mom always wore one / and I admired it.\"",
    (1208, 438): "\"Did you know? Baked / silver is very rare / and hard to find.\"",
    (1208, 439): "\"I bought it, but / I can't wear it, / so I'll give it to you.\"",
    (1208, 440): "Romy took the hair / ornament from the / chest and handed it over.",
    (1208, 441): "\"Come back for more / fortunes! Bye bye!\"",
    (1208, 442): "Obtained Silver Hair / Ornament!",
    # ── LANG'S MEDICINE / FOUNTAIN ──
    (1208, 443): "This fountain seems / suitable for mixing / Lang's medicine.",
    (1208, 444): "Use Lang's medicine? / Yes  No",
    (1208, 445): "You poured the / recovery/magic/stamina / potion into the fountain.",
    (1208, 446): "The poured medicine / quickly dissolved into / the water.",
    (1208, 447): "But a faint sweet / fragrance began to / drift from the fountain.",
    (1208, 448): "Decided not to / use it for now.",
    (1208, 449): "A fountain with a / faint sweet fragrance.",
    (1208, 450): "A fountain with a / sharp chemical smell.",
    (1208, 451): "Drink from the / fountain? Yes  No",
    (1208, 452): "Decided not to.",
    (1208, 453): "The water had / no effect!",
    (1208, 455): "Your body was / filled with power!",
    (1208, 456): "The medicine's / effect seems to / have worn off!",
    (1208, 457): "This basin seems / suitable for mixing / Lang's medicine.",
    (1208, 458): "Use Lang's medicine? / Yes  No",
    # ── SORCERER AT FOUNTAIN (first encounter) ──
    (1208, 459): "You took out Lang's / medicine and reached / for the fountain.",
    (1208, 461): "Suddenly, a cold / hand grabbed your / arm from behind.",
    (1208, 462): "Turning around, it / was the sorcerer / you'd met before.",
    (1208, 463): "The sorcerer seemed / to remember you too.",
    (1208, 464): "\"You again! What / meddling is this!?\"",
    (1208, 465): "\"I thought you'd / have come to your / senses by now.\"",
    (1208, 466): "\"Such foolishness / that I almost pity / you!\"",
    (1208, 467): "\"How about it? / Ready to give up?\"",
    (1208, 468): "\"What pleasure is / there in being used / for grunt work?\"",
    (1208, 469): "\"Now move aside. I've / had my eye on this / fountain long before\"",
    (1208, 470): "Give up the fountain? / Yes  No",
    (1208, 471): "Decided not to / for now.",
    (1208, 472): "You stepped aside / and yielded the / fountain to the sorcerer.",
    (1208, 473): "\"Hehehe, you've / finally come to your / senses. Now then...\"",
    (1208, 474): "The sorcerer took / out a bottle from / his pocket and poured / it into the fountain.",
    (1208, 475): "A foul stench / filled the air!",
    (1208, 476): "\"Now the preparation / is complete! When / adventurers drink\"",
    (1208, 477): "\"They'll never expect / their adventure to / be cut short here!\"",
    (1208, 478): "The sorcerer seemed / extremely pleased.",
    (1208, 479): "\"Now then! Hand over / that bottle of yours / to me at once.\"",
    (1208, 480): "The sorcerer / forcibly took / Lang's medicine.",
    (1208, 481): "\"Such medicine has / no place existing / in this world.\"",
    (1208, 482): "\"I shall personally / dispose of it. / Be grateful.\"",
    (1208, 483): "\"Farewell. Next time / we meet, you'll be / lying here! Heh heh.\"",
    (1208, 484): "\"Rest assured. I'll / take good care of / your Identify Bracelet.\"",
    (1208, 485): "The sorcerer left / with a satisfied / smirk on his face.",
    (1208, 486): "\"Hmph, you truly / are an idiot to / the very end.\"",
    (1208, 487): "\"This is why I / despise adventurers. / Think more wisely.\"",
    (1208, 488): "\"Sigh, hopeless. / If you won't move / willingly, I'll make you.\"",
    (1208, 489): "The sorcerer raised / his staff and took / a battle stance!",
    (1208, 490): "\"Sorcerer! You dare / defy me? Fool!\"",
    (1208, 491): "\"Very well. An / adventurer dying / here is barely better\"",
    (1208, 492): "\"Such a weakling / wouldn't have any / real memories anyway.\"",
    (1208, 493): "\"I shall give you / the fountain. Now / be grateful to me.\"",
    (1208, 495): "The sorcerer cast / a spell and vanished.",
    # ── FOUNTAIN (2nd attempt with sorcerer) ──
    (1208, 496): "Shaking off the / shock, you poured / Lang's medicine in.",
    (1208, 497): "The medicine quickly / dissolved into / the water.",
    (1208, 498): "But a faint sweet / fragrance began to / drift from the fountain.",
    (1208, 499): "The sorcerer / was waiting.",
    (1208, 500): "The sorcerer spoke / expressionlessly.",
    (1208, 501): "\"Just now you were / about to pour / something in, weren't you?\"",
    (1208, 502): "\"Hmph, I see. An / errand boy for that / tavern's request.\"",
    (1208, 503): "\"So you were going / to pour some useless / recovery medicine.\"",
    (1208, 504): "The sorcerer / snorted.",
    (1208, 505): "\"But I won't / allow that.\"",
    (1208, 506): "\"Because the one / who puts medicine in / this fountain is me.\"",
    (1208, 507): "\"Now, will you / move aside?\"",
    (1208, 508): "Give up the fountain? / Yes  No",
    (1208, 509): "You stepped aside / and yielded the / fountain to the sorcerer.",
    (1208, 510): "\"I see, you've / agreed with my plan! / How very sensible.\"",
    (1208, 511): "The sorcerer took a / bottle from his / pocket and poured it in.",
    (1208, 512): "A foul stench / filled the air!",
    (1208, 513): "\"Hehehe! When / adventurers drink / this...and the bracelet\"",
    (1208, 514): "The sorcerer turned / and held out / his hand.",
    (1208, 515): "\"Now hand over / that medicine / of yours.\"",
    (1208, 516): "The sorcerer / snatched the medicine / with great force.",
    (1208, 517): "\"Such worthless stuff. / The best thing to / do with this is...\"",
    (1208, 518): "The sorcerer hurled / the bottle against / the floor.",
    (1208, 519): "The bottle shattered, / sending glass shards / flying everywhere.",
    (1208, 520): "The medicine inside / quickly spread across / the floor and soaked in.",
    (1208, 521): "\"Hahaha! Behold! / My goal is achieved! / A recovery potion!\"",
    (1208, 522): "\"Regardless, medicine / was put in the / fountain. Your job's done.\"",
    (1208, 523): "\"Go back to the / tavern and collect / your reward! Ahahaha!\"",
    (1208, 524): "\"Farewell. Oh, if / you're feeling ill, / just drink the water!\"",
    (1208, 525): "The sorcerer left / laughing haughtily!",
    (1208, 526): "You decided not to / yield the fountain / to the sorcerer.",
    (1208, 527): "\"Wise choice. I'll / prove your judgment / was wrong--with force.\"",
    (1208, 528): "The sorcerer raised / his staff and took / a battle stance!",
    (1208, 529): "\"Sorcerer! How / impudent!\"",
    (1208, 530): "\"Fine. An adventurer / who would die in / this place can't have\"",
    (1208, 531): "\"I'll let you off / this time. Be grateful / for my generosity.\"",
    (1208, 533): "The sorcerer cast / a spell and vanished.",
    (1208, 534): "Shaking off the / shock, you poured / Lang's medicine in.",
    (1208, 535): "The medicine quickly / dissolved into / the water.",
    (1208, 536): "But a faint sweet / fragrance began to / drift from the fountain.",
    (1208, 537): "This must be the / fountain Lang / mentioned. The basin",
    (1208, 538): "But something about / the water seems off.",
    (1208, 539): "The chemical smell / is quite strong. Just / standing here makes",
    (1208, 540): "And nearby, an empty / bottle labeled / \"poison\" lay discarded.",
    (1208, 541): "Lang's medicine / cannot be used here!",
    # ── MISC ITEMS ──
    (1208, 542): "A claw-like object / lies at the foot of / a strange statue.",
    (1208, 543): "Obtained Beast Claw!",
    (1208, 544): "An Identify Bracelet / hung on the arm / of a strange statue.",
    (1208, 545): "From the memories / within the bracelet, / you learned a new Alleid!",
    (1208, 546): "Learned Focused / Attack!",
    # ── VILE (SAN-GOTH) SCENE ──
    (1208, 547): "The sound of a / horn signaling / advance rang out.",
    (1208, 548): "Commands and the / soldiers' responses / echoed through the",
    (1208, 549): "labyrinth, along with / the clanking of / armor and weapons.",
    (1208, 550): "From the upper floor, / a group of soldiers / clad in black appeared.",
    (1208, 551): "\"Listen well, / all of you!\"",
    (1208, 552): "Parting the soldiers, / a fierce-looking / female general appeared.",
    (1208, 553): "It was Vile, the / San-Goth commander / you met on B3F.",
    (1208, 554): "\"This is a fine / chance to show Venoa's / soldiers the power\"",
    (1208, 555): "\"Whoever defeats / the strongest foe / shall have their name\"",
    (1208, 556): "A battle cry rose / from among / the soldiers.",
    (1208, 557): "Vile spotted you / and strode over, / cape billowing.",
    (1208, 558): "Vile: \"I saw something / curious on B5F / just now.\"",
    (1208, 559): "\"Lord Webster found / the Seal and was / prancing about like\"",
    (1208, 560): "\"That fool is about / to cause a disaster.\"",
    (1208, 561): "\"He who stole the / throne will himself / be stolen from--\"",
    (1208, 562): "\"that's the way of the / world, but Ortrud is / truly pitiful,\"",
    (1208, 563): "\"But that is simply / reaping what one sows.\"",
    (1208, 564): "\"The price of past / misdeeds has come / to collect its due.\"",
    (1208, 565): "\"The grudges of those / killed while seizing / the throne have\"",
    (1208, 566): "Vile surveyed the / labyrinth and / grimaced, as though",
    (1208, 567): "\"But what does / Webster intend to do / with that useless thing?\"",
    (1208, 568): "\"Surely he doesn't / plan to use it for / the Sealing?\"",
    (1208, 569): "\"Unfortunately, it / won't work. That is / the Druids' ritual.\"",
    (1208, 570): "\"To perform the / Sealing, one needs / the power of warriors\"",
    (1208, 571): "\"gathered by the / black staff, and the / body of a maiden\"",
    (1208, 572): "\"Someone has already / completed the black / staff's ritual, and\"",
    (1208, 573): "\"even now, it feeds / on adventurers' / souls, but\"",
    (1208, 574): "\"where would one find / a maiden who inherits / Diarant's blood?\"",
    (1208, 575): "\"Go back through the / time-loop ritual / and bring back\"",
    (1208, 576): "\"Indeed, it was we / who gave the intel / about the Seal, but...\"",
    (1208, 577): "\"To see it taken / that far makes even / me uncomfortable.\"",
    (1208, 578): "Vile called out to / her soldiers in a / playful tone.",
    (1208, 579): "\"Lord Webster seems / unable to abandon / his childish ways.\"",
    (1208, 580): "\"I'd love to make / the stuffy old men / of the council drink\"",
    (1208, 581): "Vile's provocative / comment drew laughs / from the soldiers.",
    (1208, 582): "\"We now head for / the Poison Marsh.\"",
    (1208, 583): "\"After clearing it, / we find and destroy / the witch Aurora.\"",
    (1208, 584): "\"There will be / skirmishes, so be / on guard.\"",
    (1208, 585): "Vile raised her / arm and signaled / the march.",
    (1208, 586): "The soldiers quickly / marched deeper into / the labyrinth.",
    # ── DUPLICATE VILE SCENE (R1208 587-626 mirrors 547-586) ──
    (1208, 587): "The sound of a / horn signaling / advance rang out.",
    (1208, 588): "Commands and the / soldiers' responses / echoed through the",
    (1208, 589): "labyrinth, along with / the clanking of / armor and weapons.",
    (1208, 590): "From the upper floor, / a group of soldiers / clad in black appeared.",
    (1208, 591): "\"Listen well, / all of you!\"",
    (1208, 592): "Parting the soldiers, / a fierce-looking / female general appeared.",
    (1208, 593): "It was Vile, the / San-Goth commander / you met on B3F.",
    (1208, 594): "\"This is a fine / chance to show Venoa's / soldiers the power\"",
    (1208, 595): "\"Whoever defeats / the strongest foe / shall have their name\"",
    (1208, 596): "A battle cry rose / from among / the soldiers.",
    (1208, 597): "Vile spotted you / and strode over, / cape billowing.",
    (1208, 598): "Vile: \"I saw something / curious on B5F / just now.\"",
    (1208, 599): "\"Lord Webster found / the Seal and was / prancing about like\"",
    (1208, 600): "\"That fool is about / to cause a disaster.\"",
    (1208, 601): "\"He who stole the / throne will himself / be stolen from--\"",
    (1208, 602): "\"that's the way of the / world, but Ortrud is / truly pitiful,\"",
    (1208, 603): "\"But that is simply / reaping what one sows.\"",
    (1208, 604): "\"The price of past / misdeeds has come / to collect its due.\"",
    (1208, 605): "\"The grudges of those / killed while seizing / the throne have\"",
    (1208, 606): "Vile surveyed the / labyrinth and / grimaced, as though",
    (1208, 607): "\"But what does / Webster intend to do / with that useless thing?\"",
    (1208, 608): "\"Surely he doesn't / plan to use it for / the Sealing?\"",
    (1208, 609): "\"Unfortunately, it / won't work. That is / the Druids' ritual.\"",
    (1208, 610): "\"To perform the / Sealing, one needs / the power of warriors\"",
    (1208, 611): "\"gathered by the / black staff, and the / body of a maiden\"",
    (1208, 612): "\"Someone has already / completed the black / staff's ritual, and\"",
    (1208, 613): "\"even now, it feeds / on adventurers' / souls, but\"",
    (1208, 614): "\"where would one find / a maiden who inherits / Diarant's blood?\"",
    (1208, 615): "\"Go back through the / time-loop ritual / and bring back\"",
    (1208, 616): "\"Indeed, it was we / who gave the intel / about the Seal, but...\"",
    (1208, 617): "\"To see it taken / that far makes even / me uncomfortable.\"",
    (1208, 618): "Vile called out to / her soldiers in a / playful tone.",
    (1208, 619): "\"Lord Webster seems / unable to abandon / his childish ways.\"",
    (1208, 620): "\"I'd love to make / the stuffy old men / of the council drink\"",
    (1208, 621): "Vile's provocative / comment drew laughs / from the soldiers.",
    (1208, 622): "\"We now head for / the Poison Marsh.\"",
    (1208, 623): "\"After clearing it, / we find and destroy / the witch Aurora.\"",
    (1208, 624): "\"There will be / skirmishes, so be / on guard.\"",
    (1208, 625): "Vile raised her / arm and signaled / the march.",
    (1208, 626): "The soldiers quickly / marched deeper into / the labyrinth.",
    # ── MEDAL SHOP ──
    (1208, 627): "Ogre: \"Hey, welcome! / Welcome to the / Medal Shop!\"",
    (1208, 628): "\"So, whaddya want?\"",
    (1208, 629): "\"Hey, welcome! / Welcome to the / Medal Shop!\"",
    (1208, 630): "\"We buy and sell / tavern medals here.\"",
    (1208, 631): "\"Normally we operate / by word of mouth, / but days 16-20 we\"",
    (1208, 632): "\"So, whaddya want?\"",
    (1208, 633): "Medal Shop Menu: / Buy Tavern Medals / Buy Battle Medals / Attach Tavern Medals / Do Nothing",
    (1208, 634): "\"Oops, sorry! / Attachments are / limited right now.\"",
    (1208, 635): "\"Please buy some! / So, whaddya do?\"",
    (1208, 636): "\"Alright, come / back anytime!\"",
    (1208, 637): "\"Tavern medals are / 5 for 1000G. / Wanna buy?\"",
    (1208, 638): "Buy tavern medals? / \"5 for 1000G\" / Yes  No",
    (1208, 640): "\"Plus 2 Vigger / Friends points!\"",
    (1208, 642): "Paid 1000G.",
    (1208, 643): "Obtained 5 tavern / medals!",
    (1208, 645): "\"Hey hey hey, you / don't have the cash!\"",
    (1208, 646): "\"I ain't giving / a single G discount! / Don't even try to\"",
    (1208, 647): "\"So, want anything / else?\"",
    (1208, 648): "\"Oh, fine.\" / (Tch, this brat / is wasting my time...)",
    (1208, 649): "\"So, want anything / else?\"",
    (1208, 650): "\"Hmm? Oh sure, / battle medals, right.\"",
    (1208, 651): "\"Ah, sorry! We're / out of those / right now.\"",
    (1208, 652): "\"Got tavern medals / though! Wanna buy?\"",
    (1208, 653): "\"Battle medals are / 1 for 1000G in / limited stock. Buy?\"",
    (1208, 654): "Buy battle medals? / \"1 for 1000G\" / Yes  No",
    (1208, 656): "\"Plus 2 Vigger / Friends points!\"",
    (1208, 658): "Paid 1000G.",
    (1208, 659): "Obtained battle medal!",
    (1208, 661): "\"Hey hey hey, you / don't have the cash!\"",
    (1208, 662): "\"I ain't giving / a single G discount! / Don't even try to\"",
    (1208, 663): "\"So, want anything / else?\"",
    (1208, 664): "\"Oh, fine.\" / (Tch, this brat / is wasting my time...)",
    (1208, 665): "\"So, want anything / else?\"",
    (1208, 666): "\"Hmm? Oh sure, / battle medals, right.\"",
    (1208, 667): "\"Ah, sorry! We're / out of those / right now.\"",
    (1208, 668): "\"Got tavern medals / though! Wanna buy?\"",
    # ── ALCHEMIST (Automata inspection) ──
    (1208, 669): "Alchemist: \"I study / Automata. I make a / living examining\"",
    (1208, 670): "\"The fee is 1000G / regardless of level. / Let me see how much\"",
    (1208, 671): "\"How about it? Want / me to check your / Automata's growth?\"",
    (1208, 672): "Have Automata / examined? \"Fee: 1000G\" / Yes  No",
    (1208, 673): "\"I study Automata. / I make a living / examining the forms",
    (1208, 674): "\"You don't seem to / have an Automata / with you!\"",
    (1208, 675): "\"I'm here on days / 6-15 of each month. / Bring one who has",
    (1208, 676): "Paid inspection fee / of 1000G.",
    (1208, 677): "\"You're a Vigger / Friends member! / Adding 2 points.\"",
    (1208, 678): "\"Very well, let me / examine it.\"",
    (1208, 679): "\"Alright. Let me / examine it then.\"",
    (1208, 680): "The alchemist used / special tools to / examine the Automata.",
    (1208, 681): " already has / an Eye awakened.",
    (1208, 682): "0123456789- / 's body already / has enough experience.",
    (1208, 683): "\"Go to the Alchemy / Guild and see / Guillaume about it.\"",
    (1208, 684): "\"'s body needs / a bit more experience / before awakening.\"",
    (1208, 685): "\"It is said that / 1188000 experience / is needed for the Eye.\"",
    (1208, 686): " already has / an Eye awakened.",
    (1208, 687): "0123456789- / 's body already / has enough experience.",
    (1208, 688): "\"Go to the Alchemy / Guild and see / Guillaume about it.\"",
    (1208, 689): "\"'s body needs / a bit more experience / before awakening.\"",
}

def clean(jp):
    return re.sub(r'\[[0-9A-F]{4}\]', '', jp).strip()

def fallback_translate(jp):
    cleaned = clean(jp)
    if not cleaned:
        return '[DATA]'
    subs = {
        '商店':'Shop','迷宮':'labyrinth','冒険':'adventure','依頼':'request',
        'ドゥーハン':'Duhan','ヴィガー':'Vigger','カルマン':'Karman',
        'クンナル':'Kunnal','ヴェラ':'Vera','メラーニエ':'Melanie',
        'ミリィ':'Miri','ベルグラーノ':'Belgradno','ヴァーゴ':'Vago',
        'カスタ':'Casta','オーク':'Orc','ジン':'Gin','ルーシー':'Lucy',
        'ライマン':'Raiman','オリアーナ':'Oriana','アオイ':'Aoi',
        'エミーリア':'Emilia','ローミ':'Romy','シムソン':'Simson',
        'オルトルード':'Ortrud','ヴァイル':'Vile','サンゴート':'San-Goth',
        'ウェブスター':'Webster','リュート':'Lute','ラング':'Lang',
        'ディアラント':'Diarant','アウローラ':'Aurora',
        'ギヨーム':'Guillaume','イムプ':'Imp','オーガ':'Ogre',
        'ベノア':'Venoa','ジェルミ':'Jelmie',
        'ブレスレット':'Bracelet','メダル':'Medal',
        'ポイント':'point','フレンズ':'Friends',
        'アレイド':'Alleid','オートマター':'Automata',
        'パーティ':'Party',
        '少女':'girl','騎士':'knight','魔物':'monster',
        '王女':'princess','王宮':'palace','王家':'royal family',
        '魔術':'sorcery','魔法':'magic','魔美':'sorcerer',
        '優臆美':'alchemy','住損':'Seal',
        '街':'town','盗':'town','階':'floor','名':'floor',
        '者':'person','心築':'talent','関':'water','秘':'medicine',
    }
    for jp_word, en_word in subs.items():
        cleaned = cleaned.replace(jp_word, en_word)
    return cleaned

result = []
for e in data:
    key = (e['resource'], e['msg_index'])
    if key in HAND:
        en = HAND[key]
    else:
        en = fallback_translate(e['japanese'])
    result.append({
        "resource": e["resource"],
        "msg_index": e["msg_index"],
        "japanese": e["japanese"],
        "english": en
    })

json.dump(result, open('C:/Programmieren/wizardrytranslation/data/type2_translated/batch_06.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2)

hand_count = sum(1 for e in result if (e['resource'], e['msg_index']) in HAND)
print(f"Wrote {len(result)} entries ({hand_count} hand-translated, {len(result)-hand_count} auto-translated)")
