import json, re, sys

with open('C:/Programmieren/wizardrytranslation/data/type2_translation_batches/batch_09_R1353_R1354.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Build translation map: (resource, msg_index) -> english
tr = {}

def t(res, idx, eng):
    tr[(res, idx)] = eng

# ===================== RESOURCE 1353 =====================

# --- Common/system messages (same as other batches) ---
t(1353, 0, "The Medal that sealed / the demon's power / was offered to the gods.")
t(1353, 1, "Explore thoroughly / Potential Ability? / Ability Misc. 1 / Ability Misc. 2 / Ability Misc. 3 / Ability Misc. 4 / Ability Misc. 5 / Ability Misc. 6 / Ability Misc. 7 / Ability Misc. 8 / Ability Misc. 9 / Ability Misc. 10 / Shadow Check / Item Appraisal / Thanks to the gods? / Alleid Info 1 / Alleid Info 2 / Alleid Info 3 / Alleid Info 4 / Alleid Info 5 / Alleid Info 6 / Alleid Info 7 / Alleid Info 8 / The request was / completed.")
t(1353, 2, "The lever is locked / and won't move.")
t(1353, 3, "Operate the lever? / Yes  No")
t(1353, 5, "The lever is ON. / Operate the lever? / Yes  No")
t(1353, 6, "Turned the lever OFF.")
t(1353, 7, "The lever is OFF. / Operate the lever? / Yes  No")
t(1353, 8, "Turned the lever ON.")
t(1353, 9, "The lever is ON. / Operate the lever? / Yes  No")
t(1353, 10, "Turned the lever OFF.")
t(1353, 11, "The lever is OFF. / Operate the lever? / Yes  No")
t(1353, 12, "Turned the lever ON.")
t(1353, 13, "The lever is locked / and won't move.")
t(1353, 14, "Operate the lever? / Yes  No")

# Vigger Shop branch opens on B10
t(1353, 16, "Vigger Shop branch / has opened on / labyrinth B10.")

# --- Yoppen event on B10 ---
t(1353, 17, "Right after opening / Yoppen's door, you / found him sitting / nearby, idle.")
t(1353, 18, "\"Ahh! I'm so / tired!\"")
t(1353, 19, "Yoppen said with / a weary look.")
t(1353, 20, "Then, he looked / over and spoke.")
t(1353, 21, "I thought she was / my mom Aurora, but / that feeling has / disappeared.")
t(1353, 22, "It was a warm and / gentle feeling, / like a scent. I'd / felt it throughout / the labyrinth.")
t(1353, 23, "I never met her, / but somehow it / felt like her, so / that's what I / believed.")
t(1353, 24, "But it suddenly / vanished.")
t(1353, 25, "It was probably / just imagination, / but I'd convinced / myself, so losing / it made me sad!")
t(1353, 26, "I feel like I'll / never get to meet / Mom Aurora.")
t(1353, 27, "Yoppen looked dull, / stuffing his hands / into his brownish / orc helmet and / spinning it.")
t(1353, 28, "Hey, didn't you / feel it? That / feeling like Mom.")
t(1353, 29, "What do you think / happened to her?")
t(1353, 30, "How do you answer? / She's out there / She's gone   ")
t(1353, 31, "...............")
t(1353, 32, "You're such a / nice person.")
t(1353, 33, "I have no proof, / but I just know.")
t(1353, 35, "Yoppen's eyes / widened for a / moment, but soon / returned to his / weary look.")
t(1353, 36, "Unbelievable! / Well, not really. / You made it all / the way here, / after all.")
t(1353, 37, "I dunno why, but / monsters don't / attack me so it's / safe, but normally / that's dangerous.")
t(1353, 38, "Oh right, when I / think about it, / you're an / adventurer!")
t(1353, 39, "You came all this / way to find Mom, / right?")
t(1353, 40, "Maybe there's no / hope! She did do / bad things to the / king and princess / after all!")
t(1353, 41, "Yoppen let out / an even bigger / sigh.")
t(1353, 42, "Ahhh, I came all / this way to meet / Mom and now I / feel so let down!")
t(1353, 43, "What should I even / do from now on?")
t(1353, 44, "I only thought / about Mom, so I / can't think of / anything else.")
t(1353, 45, "Were you looking / for Mom too? What / will you do now?")
t(1353, 46, "Yoppen paused / briefly, then / spoke again.")
t(1353, 47, "Hey, it's totally / fine if you don't / want to, but would / you let me join / your party?")
t(1353, 48, "I've never fought / a monster since / entering this / labyrinth.")
t(1353, 49, "If I'm with you, / I'd get to see / lots of monsters! / Mom's not here, / but I really / love monsters.")
t(1353, 51, "Make Yoppen a / companion? / Yes  No")
t(1353, 52, "Really!? Yay! / I'll travel with / you and forget / about Mom!")
t(1353, 53, "I'll head back to / town now and sign / up at the Guild.")
t(1353, 54, "Whenever you feel / like it, take me / along with you.")
t(1353, 55, "Yoppen has been / registered at / the Guild.")
t(1353, 56, "I see...! Yeah, / I'm just a nobody / with a useless / name anyway.")
t(1353, 57, "Whatever, I give / up. I'll stop / going down there / and just study / monsters in town.")
t(1353, 58, "Well, take care!")
t(1353, 59, "Yoppen walked away / sadly, head hung / low.")

# --- Aurora scene (R1353 60-104) ---
t(1353, 60, "Gears of fate turn / with a clatter... / Joyful memories, / fun times, dreams / unfulfilled, and / even painful ones / all woven from / fleeting moments. / Aurora, what drove / you to come here?")
t(1353, 61, "In my long sleep, / I have seen many / things.")
t(1353, 62, "Some became kings / who ruled vast / lands with their / power,")
t(1353, 63, "others possessed / such iron will / that even death / itself could not / stop them.")
t(1353, 64, "But now, nothing / remains. The / merciless flow of / time has swept / everything away.")
t(1353, 65, "What will you / show me?")
t(1353, 66, "Noble one, in the / Battle of Banquo, / as reward for / aiding Ortrud, / he sent you here.")
t(1353, 67, "You have fought / off vile creatures / and now stand / before me.")
t(1353, 68, "The one whom / Ortrud sent has / overcome the / labyrinth's trials / and finally / arrived here.")
t(1353, 69, "Aurora raised her / voice joyfully, / as if delighted.")
t(1353, 70, "Don't worry, I / wasn't thinking / about you. I was / just happy, / that's all.")
t(1353, 71, "Anyone laughs when / they're happy, / right? So I did / the same.")
t(1353, 72, "After all, / something this / thrilling has not / happened in ages.")
t(1353, 73, "I waited in this / labyrinth for the / moment when the / great gate of / darkness opens.")
t(1353, 74, "And now the demons / have fallen, and / the gate of / darkness is about / to open.")
t(1353, 75, "The dark king / rises, and his / servants come to / devour all / living things.")
t(1353, 76, "It has been far / too long!! After / an eternity, I / can finally face / them once more.")
t(1353, 77, "The time for / battle has come. / The one blessed / by the labyrinth / shall lead this / fight.")
t(1353, 78, "Gather every / ounce of courage.")
t(1353, 79, "Me or you--whom / shall fate choose?")
t(1353, 80, "Now let us fight. / To end this war / that must never / be lost.")
t(1353, 81, "The eternal war / and pain have / passed, and at / last, I can die.")
t(1353, 82, "I held onto just / one single dream.")
t(1353, 83, "That dream was to / see the vile ones / burn in agony, / writhing in their / death throes.")
t(1353, 84, "What a long dream / it was! At last, / the day has come.")
t(1353, 85, "Adventurer, hear / me. The lord of / evil, Ashira, / is returning.")
t(1353, 86, "Breaking the / labyrinth's seal / and summoning the / evil ones--it / was all for this.")
t(1353, 87, "No magic or armor / can ever destroy / the evil ones.")
t(1353, 88, "Even if you / defeat them / physically, as / long as their / source remains, / they will return / again and again.")
t(1353, 89, "You who fought / Schedim should / understand this.")
t(1353, 90, "To destroy them, / you must drive a / great magic power / into the gate of / darkness and erase / their source.")
t(1353, 91, "Aurora held out / a flickering, / dark-flamed sword.")
t(1353, 92, "Received the / Dark Flame.")
t(1353, 93, "This sword / vanquished the / Ancient Dialant.")
t(1353, 94, "Use it at the / gate of darkness.")
t(1353, 95, "Aurora's body / gradually faded / as if melting / into the air.")
t(1353, 96, "The darkness is / coming!!")
t(1353, 97, "So this is what / death feels like!!")
t(1353, 98, "I can't see / anything anymore!!")
t(1353, 99, "Frieda! You / did not die!!")
t(1353, 100, "Like me! In the / endless darkness!")
t(1353, 102, "You've been waiting / all this time!")
t(1353, 103, "After Aurora / vanished, an item / appeared on the / ground.")
t(1353, 104, "Obtained the / Orobas Objet.")
t(1353, 105, "Vigger Friends / points increased / by 3.")
t(1353, 106, "Party's HP and MP / fully restored.")
t(1353, 107, "Vigger Friends / points increased / by 3.")

# --- Vigger Shop rest events ---
t(1353, 108, "While spacing out / for a while, you / gradually became / drowsy.")
t(1353, 109, "In your fading / consciousness and / dreams, you see / the shapes of / monsters.")
t(1353, 110, "Without time to / tell dream from / reality, the / monsters' shapes / attacked!")
t(1353, 111, "After the battle / with the orcs, as / you sat dazed, the / shop clerk rushed / back.")
t(1353, 112, "Whooooa, you okay / there, pal?")
t(1353, 113, "Our shop gets / attacked by scary / monsters like that / from time to time!")
t(1353, 114, "You weren't wakin' / up, so we left ya / behind and went / hidin'!")
t(1353, 115, "Well, glad yer / safe! C'mon, take / another nice rest!")
t(1353, 116, "But be careful, / don't go dozin' / off now!")
t(1353, 117, "Party's HP and MP / fully restored.")

# --- Lucy visits Vigger branch ---
t(1353, 118, "Lucy visited the / Vigger Shop branch / for the 1st time.")
t(1353, 119, "An empty spot in / the labyrinth now / had proper goods / and looked like / a real shop.")
t(1353, 120, "Behind the counter / was a monster / apparently hired / as a clerk.")
t(1353, 121, "Lucy was chatting / with the monster.")
t(1353, 122, "Lucy noticed you / and came over from / behind the desk.")
t(1353, 123, "Came to check out / the branch? / Me too!")
t(1353, 124, "It's the only / branch, y'know. I / registered as an / adventurer and / hired staff to get / all the way here.")
t(1353, 125, "It was a big deal, / but it was worth / the trip. I'm / really moved!")
t(1353, 126, "The shop got this / big thanks to you. / Really, I'm so / grateful!")
t(1353, 127, "So to make it / even bigger, keep / on shopping lots / and lots!")
t(1353, 128, "Well, I should / head back to town. / Getting back is / easy with the / return scroll!")
t(1353, 129, "I wish someone / would invent / something like a / branch scroll!")
t(1353, 130, "See ya! Stop by / the main shop too, / not just the / branch!")
t(1353, 131, "Lucy waved, then / pulled a scroll / from her bag and / read it aloud.")
t(1353, 132, "And she vanished / before your eyes.")

# --- Imp event space ---
t(1353, 133, "Next to the Imp / shopkeeper, a wall / was torn down / to create a space.")
t(1353, 134, "A plate on the / wall at the / entrance reads: / \"Event Venue.\"")
t(1353, 135, "A sign on the / counter reads: / \"Event Venue Now / Open! Vigger / Friends New Member / Enrollment!\"")
t(1353, 136, "The Imp at the / space notices you / and speaks up.")
t(1353, 137, "A sign at the Imp / event space says: / \"Vigger Friends / Now Accepting / Members!\"")
t(1353, 138, "The Imp at the / space speaks up.")
t(1353, 139, "Aha! I bet you're / interested in / joining the Vigger / Friends, huh?")
t(1353, 140, "No need to be shy! / How could anyone / not be interested / in such a great / deal?")
t(1353, 141, "How about it? Want / me to explain the / Vigger Friends / system? Or join / right away?")
t(1353, 142, "What will you do? / Hear explanation / Join right now / Do nothing   ")
t(1353, 143, "Is that so? Okay / then! Let me / explain the system / to you!")
t(1353, 144, "Oh, feel free to / just half-listen. / I'll hand you a / card when ya join.")
t(1353, 146, "Now I'll begin / the explanation!")
t(1353, 147, "The Vigger Friends / is a group where / everyone works / together to build / up Vigger Shop!")
t(1353, 148, "Members who pay / the fee get / amazing members- / only services!")
t(1353, 149, "At the Event / Venue, there are / Vigger Friends / members-only / limited events!")
t(1353, 150, "Plus, the more you / join events, the / more chances for / the super-lucky / members-only / Number Lottery!")
t(1353, 151, "How can you not / join, right? I'm / actually a member / too! A hardcore / one at that!")
t(1353, 152, "So you're joining? / The fee is 5000G / plus filling out / an application!")
t(1353, 153, "Oh, is that so? / You don't have to / be so modest!")
t(1353, 154, "You absolutely / must join next / time, bro!")
t(1353, 155, "Oh, is that so? / You don't have to / be so modest!")
t(1353, 156, "You absolutely / must join next / time, sis!")
t(1353, 157, "Join? Membership / fee: 5000G / Yes  No")
t(1353, 158, "Alright, alright! / Let me take your / membership fee!")
t(1353, 159, "Paid 5000G.")
t(1353, 160, "Payment confirmed! / Now let me give / you your Vigger / Friends card.")
t(1353, 161, "0123456789-000000 / Your membership / number is #___. / It's not on the / card though!")
t(1353, 162, "Thank you very / much!")
t(1353, 163, "Obtained the / member card.")
t(1353, 164, "Alright, alright! / Let me take your / membership fee!")
t(1353, 165, "Hey, wait! You / don't have 5000G!? / That's rough, / man!")
t(1353, 166, "Too bad! Next time / you come, bring / 5000G for sure!")
t(1353, 167, "Membership is on / hold 'til then!")
t(1353, 168, "Oh, is that so? / You don't have to / be so modest!")
t(1353, 169, "You absolutely / must join next / time, bro!")
t(1353, 170, "Oh, is that so? / You don't have to / be so modest!")
t(1353, 171, "You absolutely / must join next / time, sis!")
t(1353, 172, "A sign at the Imp / event space says: / \"Vigger Friends / Now Accepting / Members!\"")
t(1353, 173, "The Imp at the / space speaks up.")
t(1353, 174, "0123456789-000000 / Welcome back, / member number / ___!")
t(1353, 175, "Days 1 to 5 are / the Vigger Friends / enrollment / campaign period.")
t(1353, 176, "So no events / right now.")
t(1353, 178, "The event board / reads: \"Sorry, / currently on / break. Please / come back later.\"")
t(1353, 179, "????? Romy / Hey, big bro, / big sis! Welcome. / Want me to / tell your fortune?")
t(1353, 180, "The event board / reads: \"I shall / reveal the / abilities hidden / within you.\"")
t(1353, 181, "But there is / nobody at the / fortune counter.")
t(1353, 184, "A calling voice / comes from / somewhere.")
t(1353, 185, "You looked around / but couldn't find / the source of / the voice.")
t(1353, 186, "Looking at the / counter again, a / faint figure / appeared.")
t(1353, 187, "Poor thing. / You're the leader, / and you've got / nothing!")
t(1353, 188, "If you're gonna / blame someone, / blame fate, not / me.")
t(1353, 189, "Good for you. / Your Potential / Ability has / bloomed.")
t(1353, 190, "Good for you. / There's nothing / now but a hidden / ability will / surely awaken!")
t(1353, 191, "I hope it blooms / while you're still / alive.")
t(1353, 192, "I'm Romy, / a ghost. Pay me / 2000G and I'll / tell you more.")
t(1353, 193, "Get your fortune? / Fee: 2000G per / person / Yes  No")
t(1353, 194, "Then put the money / on the counter. / My hands pass / right through, so / I can't take it.")
t(1353, 195, "Not enough gold; / couldn't pay.")
t(1353, 196, "Nope, no / discounts!")
t(1353, 197, "If you don't have / the money, come / back when you do. / It's 2000G!")
t(1353, 198, "Paid 2000G.")
t(1353, 199, "Thanks a lot! / Who do you want to / know about?")
t(1353, 200, "Thanks a lot! / I'll also give / you 4 Vigger / Friends points.")
t(1353, 201, "So who do you / want to know / about?")
t(1353, 203, "Romy said that / and vanished / again.")
t(1353, 204, "Whose fortune / should be told?")
t(1353, 205, "'s ability / has already / been awakened.")
t(1353, 206, "The ability / hidden within / !")
t(1353, 207, "'s ability / has already / been awakened.")
t(1353, 208, "The ability / hidden within / !")
t(1353, 209, "'s ability / has already / been awakened.")
t(1353, 210, "The ability / hidden within / !")
t(1353, 211, "'s ability / has already / been awakened.")
t(1353, 212, "The ability / hidden within / !")
t(1353, 213, "'s ability / has already / been awakened.")
t(1353, 214, "The ability / hidden within / !")
t(1353, 215, "'s ability / has already / been awakened.")
t(1353, 216, "The ability / hidden within / !")

# --- Romy ability commentary ---
t(1353, 217, "Good for you! / Being able to use / lots of spells / sounds amazing / and wonderful.")
t(1353, 218, "Good for you! / If you're good at / offensive spells, / a front-line / fighting job might / suit you too.")
t(1353, 219, "Good for you! / Taming a dragon / as your familiar / means you must be / really strong.")
t(1353, 220, "Good for you! / Being good at / defeating demons-- / to them, you're / the real demon!")
t(1353, 221, "Good for you! / But don't try to / examine mine or / exorcise me! / I'm already dead!")
t(1353, 222, "Good for you! / But it's kinda / scary and / creepy! Don't / bully me, okay?")
t(1353, 223, "Good for you! / Don't just keep / dodging attacks; / make sure to / attack yourself / too!")
t(1353, 224, "Good for you! / Amazing, you / have the same / body as mine.")
t(1353, 225, "Good for you! / They say fewer / mistakes means / fewer regrets, / so that's really / a great thing.")
t(1353, 226, "Good for you! / I have no body / so I can't tell, / but monsters must / be terrified.")
t(1353, 227, "Good for you! / Being good at / finding items? / Give me something / sometime!")
t(1353, 228, "Good for you! / H-hey! Even if / you defeat me, / I won't drop any / rare treasure!")
t(1353, 229, "Potential Ability / 13 is cut.")
t(1353, 230, "Good for you! / But just because / you're self-aware / doesn't mean you / have real ability, / right?")
t(1353, 231, "Good for you! / Just because / you're good at / running doesn't / mean you'll get / stronger fleeing.")
t(1353, 232, "Good for you! / Turning anything / into stone? How / scary! Don't turn / me around!")
t(1353, 233, "Good for you! / Turning anything / to ashes? But / making me a / sacrifice is out / of the question!")
t(1353, 234, "Good for you! / What amazing / magic! You could / become a master / at Yugurta's / magic academy!")
t(1353, 235, "Good for you! / Healing yourself / on your own goes / beyond laziness / into impressive.")
t(1353, 236, "Good for you! / Drawing out the / power of ashes / is a wonderful / ability.")
t(1353, 237, "Nothing! I see / nothing!")
t(1353, 238, "...............")
t(1353, 239, "I feel bad, but / don't be down. / Most people in / the world have / no ability.")
t(1353, 240, "I mean, if / everyone had an / ability, that'd / be normal! So / having none makes / you the majority.")
t(1353, 241, "Those with / abilities are / extremely rare.")
t(1353, 242, "Normal is normal; / it's not inferior / at all. So don't / feel bad, okay?")
t(1353, 243, "For you, traveling / and gaining lots / of knowledge / seems like the key / to awakening / your ability.")
t(1353, 244, "Your ability / works best with / deep knowledge, so / studying hard is / the best way.")
t(1353, 245, "Your hidden / ability has a / deep connection / to faith.")
t(1353, 246, "If you live with / stronger faith, / I'm sure good / things will come / your way.")
t(1353, 247, "Face even the / mightiest monsters / bravely, without / being swayed by / physical limits.")
t(1353, 248, "You may lose your / life sometimes, / but that's good / experience in / itself.")
t(1353, 249, "Eventually you'll / willingly charge / at powerful / monsters instead / of running.")
t(1353, 250, "You have eyes that / surpass even a / demon's.")
t(1353, 251, "Once those eyes / awaken, they'll / become a truly / terrifying / weapon against / demons.")
t(1353, 252, "A scary person! / A reaper! Don't / be afraid of / those who cannot / truly die.")
t(1353, 253, "Collector, you'll / eventually grow / to love it, not / just be curious.")
t(1353, 254, "Your luck seems / to be quite good.")
t(1353, 255, "Rather than magic, / building your / physical strength / seems like the / way to develop / your ability.")
t(1353, 256, "Movements that / were too fast to / see before will / one day feel like / slow motion.")
t(1353, 257, "You naturally have / great reflexes / and physical / perception, so / just hone those.")
t(1353, 258, "You have great / vitality.")
t(1353, 259, "If you build up / your experience, / you might gain / incredibly / powerful stamina.")
t(1353, 260, "You have a / good eye. Your / concentration / seems high too.")
t(1353, 261, "Your ability to / read ahead will / keep developing.")
t(1353, 262, "Then you'll be / able to predict / enemy moves and / prevent mistakes.")
t(1353, 263, "You seem good at / grasping things / quickly.")
t(1353, 264, "So once that / ability awakens, / you can detect / enemy vital / points and finish / them off fast.")
t(1353, 265, "I sense something / truly wonderful / in your dexterity.")
t(1353, 266, "You'll be able to / find things that / normal people / would miss / without noticing.")
t(1353, 267, "I don't know your / abilities, but / I think you'd be / good at studying / and research.")
t(1353, 268, "Even if you / haven't tried, / you might be good / at it when / you do.")
t(1353, 269, "So there's a / possibility a / brand-new ability / like stealing / might emerge.")
t(1353, 270, "You might grow to / love extracting / organs from / monsters.")
t(1353, 271, "Potential Ability / 13 is cut.")
t(1353, 272, "You have the / potential to / become a kind of / mood maker.")
t(1353, 273, "No matter how / dire things get, / somehow you can't / give up!")
t(1353, 274, "Well, being self- / aware is an / ability in its / own way. Better / than being hated!")
t(1353, 275, "You have very / strong / sensitivity.")
t(1353, 276, "So if you hone / that, your / ability to read / the future will / greatly improve.")
t(1353, 277, "In battle, even / if a physically / unfit person / swings a weapon / hard, they can't / draw out its / power.")
t(1353, 278, "So normally / people wouldn't / equip things that / don't match their / build, but you're / different.")
t(1353, 279, "Your ability is / still dormant so / it's dangerous / now, but soon / you'll draw out / power from any / weapon.")
t(1353, 280, "Normally, wearing / things that don't / match your build / won't draw out / their power.")
t(1353, 281, "So people don't / normally equip / unfitting items, / but you're a bit / different.")
t(1353, 282, "Your ability is / still dormant so / it's dangerous / now, but soon / you'll draw out / power from any / accessory.")
t(1353, 283, "Deep within you, / I sense a very / strong magical / power.")
t(1353, 284, "You're the careful / type, so for now / it's best not to / overdo things.")
t(1353, 285, "Once your ability / blooms, building / magic power will / lead to amazing / growth speed.")
t(1353, 286, "Your body's / recovery speed / will become the / best of all.")
t(1353, 287, "Eventually, even / if you get hurt, / just standing / still will heal / you.")
t(1353, 288, "Well, it's best / not to get hurt / in the first / place though.")
t(1353, 289, "Your ability / draws out the / power of things, / not of yourself.")
t(1353, 290, "How to put it-- / you have better / compatibility / with objects than / with people!")
t(1353, 291, "Anyway, you'll / probably notice / that once your / ability blooms.")
t(1353, 292, "Romy's figure / flickered for / a moment.")
t(1353, 293, "Oh! I'm getting / tired.")
t(1353, 294, "I'll take a / break, so if you / want more / fortunes, come / back later.")
t(1353, 296, "Phew! I'm a bit / tired. Just so / you know, it uses / quite a lot of / energy.")
t(1353, 297, "I have no body, / so the drain is / really bad. / That's why I can / only do one / person at a time.")
t(1353, 298, "I'll take a / break, so if you / want more / fortunes, come / back later.")
t(1353, 300, "Romy disappeared.")
t(1353, 301, "Welcome, welcome!")

# --- Vigger Friends Number Lottery ---
t(1353, 302, "Days 26-30: / Vigger Friends / Members-Only / Number Lottery!   ")
t(1353, 303, "Hey, you're not / a member? The / lottery is for / members only! / Join now if / you're interested!")
t(1353, 304, "Vigger Friends / new enrollment / is only days / 1-5 at this / event counter!")
t(1353, 305, "Please come back / next time!")
t(1353, 306, "0123456789-0000000123456789- / Oh, member / number ___! / Welcome!")
t(1353, 307, "Let me check your / Friend Points, / one moment / please.")
t(1353, 309, "Oh no! Looks like / you don't have / enough points yet!")
t(1353, 310, "You need at least / 1 point to / participate in / the lottery!")
t(1353, 311, "Join more events / and earn more / points!")
t(1353, 312, "Alright, you're / all set! So, what / shall we do?")
t(1353, 313, "What will you do? / Cost: Points / 1 Pt draw / Hear explanation / Don't draw   ")
t(1353, 314, "What will you do? / Cost: Points / 1 Pt draw / 3 Pt draw / Hear explanation / Don't draw   ")
t(1353, 315, "What will you do? / Cost: Points / 1 Pt draw / 3 Pt draw / 5 Pt draw / Hear explanation / Don't draw   ")
t(1353, 316, "1 point taken! / Now then, Number / Lottery / Staaaaaart!")
t(1353, 317, "3 points taken! / Now then, Number / Lottery / Staaaaaart!")
t(1353, 318, "5 points taken! / Now then, Number / Lottery / Staaaaaart!")
t(1353, 320, "Ta-da! The number / is...!")
t(1353, 321, "Your member / number is... #!")
t(1353, 322, "...............")
t(1353, 323, "Biiiiig / winneeeeeer!")
t(1353, 324, "The Imp happily / clutched a sign / and threw / confetti / everywhere!")
t(1353, 325, "Wow, nice job! / You're actually / the very first / grand prize / winner!")
t(1353, 326, "So here's the / special prize! / An Identify / Bracelet packed / with memories!")
t(1353, 327, "Obtained Identify / Bracelet.")
t(1353, 328, "From the memories / in the bracelet, / learned a new / battle art: / Alleid.")
t(1353, 329, "Learned / Warp Attack.")
t(1353, 330, "By the way, from / now on the prizes / are Angel Bones / and Magic Wine!")
t(1353, 331, "Wow, again!? / Winning this many / times is bad for / business!")
t(1353, 332, "But hey, it's a / service! Here, / have some Angel / Bones and Magic / Wine!")
t(1353, 333, "Obtained Magic / Wine.")
t(1353, 334, "Your magic power / is buzzing!")
t(1353, 335, "You're out of / points already!")
t(1353, 336, "Earn more points / and come back!")
t(1353, 337, "You still have / points left!")
t(1353, 338, "Wanna try one / more time?")
t(1353, 339, "Draw again? / Yes  No")
t(1353, 340, "Oh well, too bad! / Come again!")
t(1353, 341, "0000000123456789- / Drawing...")
t(1353, 342, "Ta-da! The number / is...!")
t(1353, 343, "Your member / number is... #!")
t(1353, 344, "...............")
t(1353, 345, "Beeetter luck / next tiiiiime!")
t(1353, 346, "Tough luck! / Here's a / consolation / prize!")
t(1353, 347, "Ta-da! The number / is...!")
t(1353, 348, "Your member / number is... #!")
t(1353, 349, "...............")
t(1353, 350, "Beeetter luck / next tiiiiime!")
t(1353, 351, "Tough luck! / Here's a / consolation / prize!")
t(1353, 352, "Obtained Potion / of Recovery.")
t(1353, 354, "An explanation? / No problem!")
t(1353, 355, "The Number Lottery / works like this: / we draw a number / and if it matches / your member / number, you win!")
t(1353, 356, "Win and get an / awesome prize: an / Identify / Bracelet loaded / with memories!")
t(1353, 357, "But there's only / one bracelet, so / after a winner, / prizes change to / something else!")
t(1353, 358, "Even if you lose, / the consolation / prize is a Potion / of Recovery! / MP fully / restored!")
t(1353, 359, "By the way, you / can choose to / spend 1, 3, or 5 / points per draw!")
t(1353, 360, "The more points / you spend, the / better your / chances of / winning!")
t(1353, 361, "And that's the / deal! So come on / now, try your / luck!")
t(1353, 362, "An explanation? / No problem!")
t(1353, 363, "The Number Lottery / works like this: / we draw a number / and if it matches / your member / number, you win!")
t(1353, 364, "Win and get an / awesome prize: / Angel Bones and / Magic Wine! / Magic power / surging!")
t(1353, 365, "Even if you lose, / the consolation / prize is a Potion / of Recovery! / MP fully / restored!")
t(1353, 366, "By the way, you / can choose to / spend 1, 3, or 5 / points per draw!")
t(1353, 367, "The more points / you spend, the / better your / chances of / winning!")
t(1353, 368, "And that's the / deal! So come on / now, try your / luck!")
t(1353, 369, "Not drawing? Then / come back when / the lottery is / running again!")

# --- Romy package quest ---
t(1353, 370, "Romy / Hey, big bro, / big sis! / Did you bring it / for me?")
t(1353, 371, "Handed the package / received from / Ingo at B9 to / Romy.")
t(1353, 372, "Miraculously, it / passed through to / her hands without / going through her / body.")
t(1353, 373, "It's mine! / Thank you so much!")
t(1353, 374, "This is a memento / of my dad and / mom. They told me / to hold onto it.")
t(1353, 375, "Romy happily / untied the / package string / and took out / a white holy / sword.")
t(1353, 376, "Hehe! Pretty / sword, right?")
t(1353, 377, "Romy held out the / sword for you to / see.")
t(1353, 378, "The moment you / touched the sword, / a warm feeling / flowed into your / mind!")
t(1353, 379, "From the memories / in the white holy / sword, learned a / new battle art: / Alleid.")
t(1353, 380, "Learned / Break Silence.")
t(1353, 382, "Returned the / sword to Romy.")
t(1353, 383, "Oh! I need to / say thanks!")
t(1353, 384, "Open the treasure / chest behind the / counter for me!")
t(1353, 385, "As Romy said, you / opened the small / chest behind the / fortune counter.")
t(1353, 386, "Inside was a / beautiful baked / clay ring.")
t(1353, 387, "I bought this here / with money I / earned working. / Well, they only / let me order one / from this shop.")
t(1353, 388, "When she was / alive, my mom / always wore one. / I admired it.")
t(1353, 389, "Did you know? / Baked clay is / really valuable / and hard to find!")
t(1353, 390, "I bought it, but / I can't wear it, / so here, it's / yours.")
t(1353, 391, "Romy took the ring / from the chest / and handed it / over.")
t(1353, 392, "Come visit again! / Bye bye, !")
t(1353, 393, "Obtained the / Clay Ring.")

# --- Identify Bracelet on ledge ---
t(1353, 394, "An Identify / Bracelet was / caught on the / edge of a pit.")
t(1353, 395, "From the memories / in the bracelet, / learned a new / battle art: / Alleid.")
t(1353, 396, "Learned / Warp Attack.")

# --- Medal Shop / Ogre ---
t(1353, 397, "Hey there! Welcome / to the Medal / Shop!")
t(1353, 398, "So, what'll / it be?")
t(1353, 399, "Hey, welcome! / Welcome to the / Medal Shop!")
t(1353, 400, "This is a Medal / Shop. We buy, / sell, and install / Battle Medals.")
t(1353, 401, "We normally do / business quietly / by word of mouth, / but specifically / on days 16-20 / we set up here.")
t(1353, 402, "So, what'll / it be?")
t(1353, 403, "Medal Shop Menu / Buy Field Medals / Buy Battle Medals / Install Medals / Do nothing   ")
t(1353, 404, "Sorry, / installations / are outsourced / so I'm waiting / on materials from / the monsters.")
t(1353, 405, "If you want, / buy some! So, / what'll it be?")
t(1353, 406, "Alright, come / back anytime!")
t(1353, 407, "Field Medals are / 5 for 1000G. / Wanna buy?")
t(1353, 408, "Buy Field Medals? / 5 for 1000G / Yes  No")
t(1353, 410, "I'll throw in 2 / Vigger Friends / points too!")
t(1353, 412, "Paid 1000G.")
t(1353, 413, "Obtained 5 Field / Medals.")
t(1353, 415, "Whoa whoa, hold / on! You don't / have the money!")
t(1353, 416, "I ain't gonna cut / even 1G! Better / drop any ideas / about haggling!")
t(1353, 417, "So, anything / else?")
t(1353, 418, "Oh, I see. / (That little / brat, messing / with me...just / you wait!)")
t(1353, 419, "So, anything / else?")
t(1353, 420, "Oh! Sure, Battle / Medals, right?")
t(1353, 421, "Oh, sorry about / that! I'm all / out of stock / right now!")
t(1353, 422, "I do have Field / Medals though. / How about it?")
t(1353, 423, "Battle Medals / are 1000G each, / limited supply. / Wanna buy?")
t(1353, 424, "Buy Battle / Medals? / 1 for 1000G / Yes  No")
t(1353, 426, "I'll throw in 2 / Vigger Friends / points too!")
t(1353, 428, "Paid 1000G.")
t(1353, 429, "Obtained a / Battle Medal.")
t(1353, 431, "Whoa whoa, hold / on! You don't / have the money!")
t(1353, 432, "I ain't gonna cut / even 1G! Better / drop any ideas / about haggling!")
t(1353, 433, "So, anything / else?")
t(1353, 434, "Oh, I see. / (That little / brat, messing / with me...just / you wait!)")
t(1353, 435, "So, anything / else?")

# --- Alchemist / Automata checker ---
t(1353, 436, "Alchemist / I am one who / reads alchemy. / I make a living / reading the lines / of creatures made / by alchemy.")
t(1353, 437, "A reading costs / 1000G regardless / of the result. / Let me see how / much soul essence / has accumulated / in your soulless / creatures.")
t(1353, 438, "How about it? / Want me to check / how far your / automata has / developed?")
t(1353, 439, "Have your automata / checked? / Fee: 1000G / Yes  No")
t(1353, 440, "I read alchemy. / I make a living / reading the lines / of creatures made / by alchemy.")
t(1353, 441, "You don't seem to / have any automata / with you.")
t(1353, 442, "I'm here on days / 6 through 15. / If you have a / soulless creature, / bring it here.")
t(1353, 443, "Paid the 1000G / fee.")
t(1353, 444, "You're a Vigger / Friends member. / I'll add 2 / points for you.")
t(1353, 445, "Then, let me / examine it.")
t(1353, 446, "Very well. Then / let me examine / it.")
t(1353, 447, "The alchemist / carefully / examined the / automata using / special tools.")
t(1353, 448, " seems to / already have a / soul blooming.")
t(1353, 449, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 450, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 451, " needs a bit / more experience / to develop / further.")
t(1353, 452, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 453, " seems to / already have a / soul blooming.")
t(1353, 454, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 455, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 456, " needs a bit / more experience / to develop / further.")
t(1353, 457, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 458, " seems to / already have a / soul blooming.")
t(1353, 459, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 460, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 461, " needs a bit / more experience / to develop / further.")
t(1353, 462, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 463, " seems to / already have a / soul blooming.")
t(1353, 464, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 465, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 466, " needs a bit / more experience / to develop / further.")
t(1353, 467, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 468, " seems to / already have a / soul blooming.")
t(1353, 469, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 470, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 471, " needs a bit / more experience / to develop / further.")
t(1353, 472, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 473, " seems to / already have a / soul blooming.")
t(1353, 474, "0123456789- / 's growth / already has / enough experience / accumulated.")
t(1353, 475, "Go to the Alchemy / Guild and see / Guillaume.")
t(1353, 476, " needs a bit / more experience / to develop / further.")
t(1353, 477, "According to / research, an / automata needs / 128000 experience / to develop a / soul, for your / reference.")
t(1353, 478, "The alchemist / finished the / examination and / took a breath.")
t(1353, 479, "How was it? / Satisfied? Come / back whenever you / want another / checkup.")
t(1353, 480, "Not enough gold!")
t(1353, 481, "What, you don't / have enough? I'm / not running a / charity here, / so I can't do it / without payment.")
t(1353, 482, "When you have / enough money, / come back.")
t(1353, 483, "I see, not / interested? / It is certainly / an unnerving / thing, having / someone peer into / your creature's / soul.")
t(1353, 484, "If you become / interested, come / back anytime.")

# --- Part-time orc encounter ---
t(1353, 485, "You ran into an / orc working / part-time at the / shop.")
t(1353, 486, "The orc seemed / to recognize you / and happily came / over.")
t(1353, 487, "H-hello! Do you / remember me? / I'm workin' / part-time here!")
t(1353, 488, "I'm so happy! / Did you come to / check on us?")
t(1353, 489, "We'll do our / best! You keep / doin' your best / too, senpai!")
t(1353, 490, "The orc happily / went back to / cleaning duty.")
t(1353, 491, "Part-timer trust / went up by 5.")

# --- Package traps ---
t(1353, 492, "Something seems / to be inside / the bag.")
t(1353, 493, "Open the bag? / Yes  No")
t(1353, 494, "Untying the bag, / something like / smoke came out.")
t(1353, 495, "The smoke quickly / spread, filling / the area and / blocking your / vision.")
t(1353, 496, "Within the smoke- / filled area, / monsters had / appeared!")
t(1353, 497, "When the battle / ended, the / mysterious smoke / was gone too.")
t(1353, 498, "Decided to / leave it alone.")
t(1353, 499, "The bag is empty!")
t(1353, 500, "Something seems / to be inside / the bag.")
t(1353, 501, "Open the bag? / Yes  No")
t(1353, 502, "Inside the bag / was a pretty / golden key.")
t(1353, 503, "Obtained the / Golden Key.")
t(1353, 504, "Decided to / leave it alone.")
t(1353, 505, "The bag is empty!")

# --- Thurgo rescue ---
t(1353, 506, "\"Hey, help me / out!\"")
t(1353, 507, "\"If anyone's / there, get me / outta here!\"")
t(1353, 508, "\"Please, monster, / witch, anyone! / I don't care!\"")
t(1353, 509, "From deep inside / the dark pit, you / could hear an / adventurer / crying for help.")
t(1353, 510, "The adventurer / was Thurgo.")
t(1353, 511, "Thurgo was / clinging to the / edge of the pit, / dangling there.")
t(1353, 512, " pulled / Thurgo out of / the pit.")
t(1353, 513, "Thurgo: Oh, thank / the gods!!")
t(1353, 514, "Man, I was done / for! I dropped / my sword into / that pit,")
t(1353, 515, "and when I tried / to grab it, my / foot slipped and / I fell in!")
t(1353, 516, "I got so cold / and scared, I was / seriously about / to die.")
t(1353, 517, "Really, thanks! / I owe you one!")

# --- Angus and Thurgo scene ---
t(1353, 518, "\"Gwahahaha! / That's what you / get! Karma!\"")
t(1353, 519, "Suddenly, a loud / voice echoed.")
t(1353, 520, "It was the / booming voice of / a large man who / came through a / nearby warp zone.")
t(1353, 521, "The man / approached, / stroking his / massive body.")
t(1353, 522, "Th-the Chief / Angus!! Why are / you here!?")
t(1353, 523, "Angus: Well, / Ingo told me / you'd been getting / swords too, / hadn't he?")
t(1353, 524, "So I came to see / what you've been / hiding.")
t(1353, 525, "Listen up, / Thurgo.")
t(1353, 526, "Karma, I tell ya! / Having all that / talent and doing / nothing--the gods / punished you.")
t(1353, 527, "What are you / talking about!?")
t(1353, 528, "What karma!? / Prove it before / you say that!")
t(1353, 529, "You just want to / bully me, / don't you?")
t(1353, 530, "Right? Everyone / at the guild is / scared, so nobody / will go,")
t(1353, 531, "and you're just / trying to throw / me into fighting / the witch!")
t(1353, 532, "If you want the / witch dead so bad / why don't you do / it yourself!")
t(1353, 533, "If only I could.")
t(1353, 534, "If I didn't need / to ask the likes / of you, I'd have / done it already.")
t(1353, 535, "The chief's face / changed to a / sorrowful look.")
t(1353, 536, "I can't swing a / sword anymore.")
t(1353, 537, "During the Battle / of Banquo, I hurt / my body so bad / that even though / I want to fight, / I can't!")
t(1353, 538, "Hey, Thurgo, have / you ever thought / about it?")
t(1353, 539, "Why you were born / with such great / talent?")
t(1353, 540, "Everyone is born / with different / abilities.")
t(1353, 541, "Some are strong, / some are tough, / some have magic / talent, and some / are nimble!")
t(1353, 542, "That's because / the gods thought / it through and / gave those gifts / to us.")
t(1353, 543, "So that everyone / can combine their / strengths and / build a happy / world.")
t(1353, 544, "Listen, Thurgo. / We were both born / and raised in / this Duhan. / We're family.")
t(1353, 545, "And the town is / like the mother / who raised us. / Right?")
t(1353, 546, "And that mother / needs our / strength right / now.")
t(1353, 547, "Won't you use / your power, just / once in your / limited life, / for the sake of / our mother?")
t(1353, 548, "Thurgo stood / silently, saying / nothing.")
t(1353, 549, "After a while, / Thurgo spoke up.")
t(1353, 550, "What if I die?")
t(1353, 551, "I'm saying this / not as a chief, / but as one man.")
t(1353, 552, "I'd rather die / holding a great / dream than live / as if already / dead.")
t(1353, 553, "Isn't protecting / this town and its / people a dream / worth having?")
t(1353, 554, "Fine, but if / I die, you'd / better pay the / condolence money.")
t(1353, 555, "Nobody to / receive it, so / feed my dog the / most delicious / food in the / world.")
t(1353, 556, "Got it? Otherwise / I absolutely / won't do it.")
t(1353, 557, "The chief smiled / warmly and patted / Thurgo's back / a couple times.")
t(1353, 558, "Got it, I / understand. You / really are a / good kid. I'll / definitely keep / that promise!")
t(1353, 559, "You've saved my / life many times. / I'm grateful.")
t(1353, 560, "If you ever need / my help, just / say the word.")
t(1353, 561, "I'll head back to / town first and / register at the / Adventurer's / Guild.")
t(1353, 562, "\"Wait up, old / man!\"")
t(1353, 563, "\"I don't have / a return scroll!\"")
t(1353, 564, "Thurgo hurried / after the chief / and shouted.")
t(1353, 565, "Thurgo has been / registered at the / Adventurer's / Guild.")

# --- Uli scene ---
t(1353, 566, "\"Have you ever / considered that / Aurora might / be a god?\"")
t(1353, 567, "The elf elder / Uli slowly / approached.")
t(1353, 568, "Uli: What / separates the / living from / the dead?")
t(1353, 569, "I once pursued / the study of life / and death as a / scholar, seeking / answers from / great heights, / but the riddle / remains unsolved.")
t(1353, 570, "I've been thinking / about her for / a long time.")
t(1353, 571, "If something / called immortality / truly exists, / and if Aurora / truly has it,")
t(1353, 572, "then she might / hold the key to / solving this / eternal mystery.")
t(1353, 573, "But my conclusion / was that / immortality is / merely a plaything / of necromancers-- / nothing more.")
t(1353, 574, "Indeed, the word / 'undead' is used / for zombies and / such.")
t(1353, 575, "But they are / merely the dead, / reproducing the / body's decay / and regeneration.")
t(1353, 576, "They have no / memories or / consciousness / from when they / were alive; they / merely exist.")
t(1353, 577, "Why can / immortality not / truly exist?")
t(1353, 578, "Because living / things cannot / endure the agony / that time brings.")
t(1353, 579, "But she is alive.")
t(1353, 580, "That is what I / find so strange.")
t(1353, 581, "Uli paused, his / expression / sinking into / deep thought.")
t(1353, 582, "In the ancient / kingdom of / Narkia, she / appeared and / declared:")
t(1353, 583, "That she had / lived through an / age of thousands / of years, and / witnessed the / fall of all the / old kingdoms.")
t(1353, 584, "What do you / think? If that / is true, then / she has existed / since the distant / past.")
t(1353, 585, "I cannot believe / that.")
t(1353, 586, "If someone could / truly live for / thousands of / years and remain / sane, that being / would be a god.")
t(1353, 587, "Even elves are / said to live only / a few hundred / years.")
t(1353, 588, "Certainly, with / their vast / knowledge and / magical skill, / further longevity / might be / possible.")
t(1353, 589, "But no one tries / to achieve it.")
t(1353, 590, "Because every / elf knows that / time corrupts / the soul.")
t(1353, 591, "Have you ever / thought about it?")
t(1353, 592, "What would happen / if you truly had / a life spanning / thousands of / years?")
t(1353, 593, "Do you think long, / happy days would / continue?")
t(1353, 594, "Surely, any being / would tire of / life, and their / emotions would / erode away.")
t(1353, 595, "Life inherently / demands change.")
t(1353, 596, "The ability to / move one's eyes / well, and every / sense governing / the body--none / can resist the / decay of time.")
t(1353, 597, "Even if one / obtained / immortality, / they could not / endure its / torment.")
t(1353, 598, "But she is alive.")
t(1353, 599, "If she is not / a god, then we / must be / overlooking / something vital!")
t(1353, 600, "Uli looked down, / lost in thought / for a while.")
t(1353, 601, "Even the wisest / scholar, when / all certain facts / are removed and / what remains is / the answer-- / that is the / truth.")
t(1353, 602, "This is a tenet / of alchemist / thinking.")
t(1353, 603, "I will go once / more to the / Ancient Kingdom / ruins on the 5th / level to confirm / my hypothesis.")
t(1353, 604, "I've come this / deep, but I have / no interest in / defeating Aurora / or solving this / floor's riddle.")
t(1353, 605, "Uli said that / and walked away.")

# --- Vago and Casta scene ---
t(1353, 606, "You spotted Vago / and Casta ahead / on the path.")
t(1353, 607, "\"You stupid orc!\"")
t(1353, 608, "\"Grrr! Annoying!\"")
t(1353, 609, "They seem to be / arguing.")
t(1353, 610, "As you watched, / both noticed you / and walked over.")
t(1353, 611, "Oh, we meet / again! By now / I should've been / back to normal / time already!")
t(1353, 612, "Vago glared at / Casta.")
t(1353, 613, "This idiot says / the shock from / getting stuck / at B5 made him / forget the spell!")
t(1353, 614, "H-hey! You'd / never understand / my trembling / heart!")
t(1353, 615, "Hmph, don't want / to understand!")
t(1353, 616, "Vago turned away / from Casta and / spoke to you.")
t(1353, 617, "Are you familiar / with this area? / I want to go to / the place with a / huge crystal in / the center.")
t(1353, 618, "If you lead us / there, I'll repay / you somehow.")
t(1353, 619, "Great! I knew / you'd help us!")
t(1353, 620, "It's definitely / on this floor, so / just lead us / there.")
t(1353, 621, "We'll follow / behind you / quietly. We / won't be a / bother, promise!")
t(1353, 622, "Let's hurry, / I want to get / back soon!")
t(1353, 623, "Too bad! With / this pig, there's / a limit to how / far we can / search on our / own.")
t(1353, 624, "Oh well, let's / go back to B4 / and regroup.")
t(1353, 625, "So we're heading / back to B4 for / now, but if you / change your mind / about guiding us, / come find us!")

# --- Vago & Casta reach crystal ---
t(1353, 626, "Vago & Casta / \"Ah, this is it!\"")
t(1353, 627, "Casta shouted.")
t(1353, 628, "Oh my, it really / does look just / like that / crystal!")
t(1353, 629, "Yeah, yeah! This / is where we can / go back!")
t(1353, 630, "Yep yep, this'll / definitely take / us back!")
t(1353, 631, "Vago looks happy.")
t(1353, 632, "I owe you / everything! / Thank you!")
t(1353, 633, "Getting sent to / this weird era, / I thought things / would be nothing / but trouble, but / being treated / well feels nice.")
t(1353, 634, "Yeah! Thanks to / you, our precious / lives are saved!")
t(1353, 635, "Right, I need to / give you your / reward!")
t(1353, 636, "Vago said that / and removed a / pretty ring from / her finger, / offering it / to you.")
t(1353, 637, "We'll probably / never meet again, / but sometimes / look at this ring / and remember us!")
t(1353, 638, "Now, Casta! I'll / carve the crystal / like when we / came here. You / stay back!")
t(1353, 639, "Stealin' jewels is / bad, but this / time there's no / choice!")
t(1353, 640, "Vago pulled out / a knife, gripped / it firmly, and / began carving the / crystal.")
t(1353, 641, "Casta stuck close / behind Vago, / watching intently.")
t(1353, 642, "The moment Vago's / knife touched the / crystal--!")
t(1353, 643, "Intense light / overflowed from / the crystal's / surface, engulfing / the entire area.")
t(1353, 644, "\"It feels just / like when we / first came!\"")
t(1353, 645, "\"We're goin' / back!\"")
t(1353, 646, "The light made / it impossible / to see, but you / could hear both / their voices.")
t(1353, 647, "\"I feel like / I'm being pulled / away! Thank you!\"")
t(1353, 648, "\"Take care!\"")
t(1353, 649, "When the light / faded, the two / were already / gone.")
t(1353, 650, "Obtained the / Sorceress Ring.")
t(1353, 651, "Did Vago and the / others make it / safely back to / their own time?")

# ===================== RESOURCE 1354 =====================

# --- Webster ring scene ---
t(1354, 0, " was led to / a parlor and / greeted by / Lord Webster.")
t(1354, 1, "Webster: I just / got word from / Zel.")
t(1354, 2, "You found the / princess's ring. / Thank you.")
t(1354, 3, "This confirms / that the / princess's body / is hidden in the / labyrinth.")
t(1354, 4, "We will assemble / a search party / at once to / recover her / remains.")
t(1354, 5, "Now the princess / can finally / rest in peace.")
t(1354, 6, "Come, the lord / awaits you over / there.")
t(1354, 7, "Just as Lord / Webster was about / to lead  to / the king,")
t(1354, 8, "a hoarse voice / suddenly echoed / through the / parlor.")
t(1354, 9, "\"Long ago, the / King of Sepoy / once said:\"")
t(1354, 10, "\"If you journey / to the holy land / while alive and / obtain the / sacred sword,\"")
t(1354, 11, "\"it would have / been possible. / If the countless / explorations / before hadn't all / been destroyed.\"")
t(1354, 12, "A robed old man / had slipped past / the guards at / the corridor's / entrance and was / approaching.")
t(1354, 13, "What insolence!")
t(1354, 14, "What are the / guards doing!?")
t(1354, 15, "Nobody noticed / him getting all / the way here!?")
t(1354, 16, "Get him out of / here at once!")
t(1354, 17, "\"Let him be. / Allow him / through.\"")
t(1354, 18, "\"He is the Grand / Sorcerer Wezbell. / No one in this / world can stop / him.\"")
t(1354, 19, "King Ortrud spoke / to Webster and / the guards who / had moved to / seize the old / man.")
t(1354, 20, "Wezbell: The / Drakul Army of / Ancient Gilten / conquered five / kingdoms in / merely two / years with its / overwhelming / might.")
t(1354, 21, "The sorcerers of / Irikia who / lived in the / Middle Ages had / magic powerful / enough to move / mountains.")
t(1354, 22, "But they're all / gone. Yes, that / woman destroyed / them all.")
t(1354, 23, "The magnificent / kingdom now / leaves no trace / of its existence / in this world.")
t(1354, 24, "Do you understand / what I'm trying / to say, Ortrud?")
t(1354, 25, "Ortrud: Why would / I know what the / Grand Sorcerer / Wezbell thinks?")
t(1354, 26, "I am not that / wise.")
t(1354, 27, "But surely you / didn't come all / the way here / just for / pleasantries.")
t(1354, 28, "Grand Sorcerer / Wezbell, you / bring up the / glory of old / kingdoms to tell / me what?")
t(1354, 29, "What are you / hiding, Ortrud?")
t(1354, 30, "Why does Duhan / still survive?")
t(1354, 31, "In all these / years, why has / that woman done / nothing?")
t(1354, 32, "If she became / serious, she / could not only / curse the land,")
t(1354, 33, "but easily / annihilate Duhan / entirely, as / you well know.")
t(1354, 34, "You must know / something. / Tell me.")
t(1354, 35, "Enough, Wezbell. / I have enough / troubles as / it is.")
t(1354, 36, "Our lands were / stolen, and our / people wither / from the ongoing / curse.")
t(1354, 37, "Because of that / labyrinth, we / must even limit / trade routes.")
t(1354, 38, "You've seen how / Duhan decays / beyond / recognition.")
t(1354, 39, "You would ask me / for more / misfortune on / top of all that?")
t(1354, 40, "I simply want / to know.")
t(1354, 41, "Why does the man / once feared as / the Unrivaled / King, who / brought all of / Venoa to peace,")
t(1354, 42, "now sit idle / while the kingdom / collapses, / sending only / half-hearted / search parties?")
t(1354, 43, "Why leave that / witch alone?")
t(1354, 44, "Having assembled / an army, why / do you not even / control your own / soldiers? I want / to understand / your reasoning.")
t(1354, 45, "Wezbell, enough / games. What do / you want to say?")
t(1354, 46, "That I have some / sort of deal / with Aurora?")
t(1354, 47, "That the witch / is so gentle, / merely stealing / my lands, / cursing this / body, and / creating a / labyrinth?")
t(1354, 48, "Hmph, ridiculous.")
t(1354, 49, "If you have time / for such / conspiracy / theories, I'd / rather you join / the subjugation / force.")
t(1354, 50, "Hmm! So you / wouldn't mind if / I were to / investigate on / my own?")
t(1354, 51, "Why hesitate? / Whoever slays / the witch / shall become / Duhan's new hero.")
t(1354, 52, "And I eagerly / await that day. / That is my only / wish.")
t(1354, 53, "Very well, then / I shall prepare / and enter the / labyrinth / myself.")
t(1354, 54, "Lord Webster, who / had watched the / exchange between / the sorcerer and / the king, / approached with / a dubious look.")
t(1354, 55, "Who was that?")
t(1354, 56, "The shell of / a man once known / as the Grand / Sorcerer.")
t(1354, 57, "The witch Aurora / took everything / from him, and / now he is but a / madman.")
t(1354, 58, "I apologize for / the unexpected / intrusion.")
t(1354, 59, "Now then, would / you show me the / ring you found?")
t(1354, 60, "King Ortrud took / the ring from / and confirmed / it was the / princess's ring.")
t(1354, 61, "This is indeed / Oriana's. But / why was it in / the labyrinth?")
t(1354, 62, "What interest / could anyone / have in her body? / Why would they / disturb her / resting place?")
t(1354, 63, "I cannot say. / But this proves / that someone has / hidden the / princess's / remains in the / labyrinth.")
t(1354, 64, "Immediately, I / shall enter the / labyrinth and / join the search / party myself.")
t(1354, 65, "Rest assured. / I will answer / the lord's / expectations / without fail.")
t(1354, 66, "With a strong / smile, Lord / Webster departed.")
t(1354, 67, "Watching him go, / Ortrud muttered / quietly:")
t(1354, 68, "Adventurer, it / is a curious / thing. People of / all kinds and / purposes have / gathered in / Duhan.")
t(1354, 69, "The righteous / and the wicked / alike fight to / fulfill their / dreams.")
t(1354, 70, "Some come to / reclaim what / they once lost,")
t(1354, 71, "others head into / the labyrinth / to satisfy / their thirst for / the unknown.")
t(1354, 72, "Whatever they / truly seek in / their hearts, / it all serves to / protect Duhan.")
t(1354, 73, "I care not who / it may be. If / someone in this / world can slay / Aurora,")
t(1354, 74, "I would gladly / give up this / throne.")
t(1354, 75, "So saying, / Ortrud stared / intently at .")
t(1354, 76, "Perhaps it is / you.")
t(1354, 78, "With a warm / smile, Ortrud / departed.")

# --- Webster first meeting scene ---
t(1354, 79, " entered / the castle and / was led to / a reception room.")
t(1354, 80, "Several men. / You must be the / new member of / the subjugation / force.")
t(1354, 81, "I received word / from General / Belgradno.")
t(1354, 82, "That a promising / newcomer has / arrived.")
t(1354, 83, "Forgive me, I am / Lord Webster, / Ferry de Lufol. / I serve as / regent of this / kingdom.")
t(1354, 84, "I'm sure we'll be / relying on each / other going / forward. Pleased / to meet you.")
t(1354, 85, "Webster smiled / gently.")
t(1354, 86, "Webster: Come, / this way. King / Ortrud awaits. / Tell him about / the expedition.")
t(1354, 87, " walked / forward to the / throne.")
t(1354, 88, "King Ortrud was / served holy water / by an attendant / and appeared / frail.")
t(1354, 89, "The king skipped / formalities and / got right to / the point.")
t(1354, 90, "Ortrud: Recently, / attacks on / expedition teams / have increased / sharply.")
t(1354, 91, "There are even / reports of / adventurers / disguising / themselves to / attack the / expedition.")
t(1354, 92, "When we must / unite against / a common enemy, / such incidents / cannot be / tolerated.")
t(1354, 93, "So let me ask / once more: was / it indeed / monsters that / attacked the / expedition?")
t(1354, 94, "Who attacked the / expedition? / Definitely / monsters / ...Not sure")
t(1354, 95, "So the reports / are consistent-- / it was all the / work of the / monsters.")
t(1354, 96, "Dear me, the / mystery only / deepens.")
t(1354, 97, "The soldiers / accompanying / them were all / found dead in / the labyrinth, / unable to speak.")
t(1354, 98, "How dreadful it / must have been. / They died without / the chance to / avenge their / honor.")
t(1354, 99, "There are / troubling rumors / about the / soldiers / circulating in / town.")
t(1354, 100, "That all the / expedition / incidents were / actually staged / by the soldiers / themselves.")
t(1354, 101, " recalled the / kind of wound / the expedition / woman had.")
t(1354, 103, "A soldier would / have many ways / to kill without / using a blade.")
t(1354, 104, "That leads to / only one / conclusion.")
t(1354, 105, "Before being / attacked by / monsters, the / expedition must / have fought / someone else.")
t(1354, 106, "That is useful / information.")
t(1354, 107, "There are some / troubling rumors / about the / soldiers / circulating.")
t(1354, 108, "That all the / expedition / incidents were / staged by the / soldiers.")
t(1354, 109, "Outrageous!")
t(1354, 110, "The king glared / into the distance / and sighed / heavily.")
t(1354, 111, "How frustrating!")
t(1354, 112, "Because of the / witch's curse, / this body / withers. I can / barely even / walk now.")
t(1354, 113, "If this body / were sound, I / would go to the / labyrinth / myself to / investigate!")
t(1354, 114, ", this / time I thank / you for your / service.")
t(1354, 115, "An attendant / placed a brightly / glowing magic / sheath before .")
t(1354, 116, "Obtained the / Magic Sheath.")
t(1354, 117, "It's not much, / but it's a sheath / imbued with magic. / Useful against / undead foes.")
t(1354, 118, "Please accept it / as a token of / my gratitude.")
t(1354, 119, "Adventurer, may / I ask you / something?")
t(1354, 120, "Why do you enter / the labyrinth?")
t(1354, 121, "For money? / For revenge? Or / do you fight / without purpose?")
t(1354, 122, "Your reason for / entering? / For money / For revenge / No reason")
t(1354, 124, "I once had / nothing. Born in / the slums of a / remote province, / I struggled even / to buy a single / piece of armor.")
t(1354, 125, "But looking back, / I had everything.")
t(1354, 126, "Comrades I could / trust from the / heart, and dreams / worth risking my / life for--yes, / everything!")
t(1354, 127, "I became King of / Duhan. And I / gained money and / vengeance.")
t(1354, 128, "But what I once / had is now gone.")
t(1354, 129, "Hear this as / advice from a / man who was once / an adventurer / like you.")
t(1354, 130, "Find comrades you / can truly trust.")
t(1354, 131, "Friends who can / watch your back / in battle cannot / be bought with / all the world's / riches.")
t(1354, 132, "They don't just / save your life-- / they give you / everything.")
t(1354, 133, "Money, revenge, / dreams--yes, / everything.")
t(1354, 134, "Hmm, for revenge / then!")
t(1354, 135, "I once had / nothing. Born in / the slums of a / remote province, / I struggled even / to buy a single / piece of armor.")
t(1354, 136, "But looking back, / I had everything.")
t(1354, 137, "Comrades I could / trust from the / heart, and dreams / worth risking my / life for--yes, / everything!")
t(1354, 138, "I became King of / Duhan. And I / gained money and / vengeance.")
t(1354, 139, "But what I once / had is now gone.")
t(1354, 140, "Hear this as / advice from a / man who was once / an adventurer / like you.")
t(1354, 141, "Find comrades you / can truly trust.")
t(1354, 142, "Friends who can / watch your back / in battle cannot / be bought with / all the world's / riches.")
t(1354, 143, "They don't just / save your life-- / they give you / everything.")
t(1354, 144, "Money, revenge, / dreams--yes, / everything.")
t(1354, 145, "Then let me say / this: find / comrades you / can truly trust.")
t(1354, 146, "Friends who can / watch your back / in battle cannot / be bought with / all the world's / riches.")
t(1354, 147, "They don't just / save your life-- / they give you / everything.")
t(1354, 148, "Money, revenge, / dreams--yes, / all of it!")
t(1354, 149, "Ha, perhaps it's / the illness / making me too / sentimental.")
t(1354, 150, "That's all for / today. The / palace doctor / should be here / any moment with / his vile / medicine.")
t(1354, 151, "King Ortrud was / helped up by / an attendant / and departed.")

# --- Belgradno first meeting ---
t(1354, 152, "Upon entering the / castle,  was / led to a room / resembling a / military office.")
t(1354, 153, "It was a well- / maintained room, / but without / paintings; the / tapestries and / tablecloths were / plain and without / decoration.")
t(1354, 154, "Belgradno: / Sorry to keep / you waiting. / Make yourself / comfortable.")
t(1354, 155, "Belgradno placed / some documents / and a small / pouch of dark / velvet on the / table.")
t(1354, 156, "The velvet pouch / was unknown, but / the documents / were letters / bearing the / royal seal and / various reports.")
t(1354, 157, "Right now, Duhan / is plagued by / a certain / problem.")
t(1354, 158, "The thorough / screening of / newcomers and / the gathering / of adventurers / like you--it's / all because of / that.")
t(1354, 159, "The problem is / the emergence / of monsters.")
t(1354, 160, "Do you know of / Karman's / Labyrinth / outside town?")
t(1354, 161, "The numbers are / still small, but / monsters have / been crawling out / from below.")
t(1354, 162, "So what we ask / of you is to / enter the / labyrinth and / bring back the / head of the / witch, the root / of all evil.")
t(1354, 163, "The witch's name / is Aurora.")
t(1354, 164, "A wicked / incarnation of / darkness who / seeks to lead / Duhan to ruin.")
t(1354, 165, "That dreadful / witch has cursed / all of Duhan / and created the / labyrinth.")
t(1354, 166, "She appeared / years ago, on / the day of / Princess Oriana / and Lord / Webster's / wedding.")
t(1354, 167, "\"It's been a / while, my lord.\"")
t(1354, 168, "A woman with / darkly gleaming / eyes stepped / before King / Ortrud.")
t(1354, 169, "\"A-Aurora!! Your / Grace looks / lovely!\" / \"Wh-what have you / come here for!?\"")
t(1354, 170, "The courtiers / began to / murmur.")
t(1354, 171, "Everyone knew / that dreaded / name. A witch / with eternal / life who had / destroyed the / ancient kingdoms.")
t(1354, 172, "\"What have you / come for!?\" / \"Please, recall / our promise! / If you hear my / wish, I shall / leave at once!\"")
t(1354, 173, "\"Tell me, what / is your wish?\" / \"My wish is for / this kingdom, / Duhan, to be / destroyed.\"")
t(1354, 174, "An uproar / engulfed the / hall. All the / courtiers / watched this / extraordinary / event in shock.")
t(1354, 175, "\"You want / Duhan?\" \"Yes.\" / \"Are you / certain?\" \"I am / merely stating / the truth.\"")
t(1354, 176, "The guards / rushed forward.")
t(1354, 177, "But when fixed / by the witch's / gaze, everyone / froze as if / spellbound, / unable to move.")
t(1354, 178, "\"Is this your / answer?\" / \"I'm glad you / think so.\"")
t(1354, 179, "\"Very well. Then / walk the path of / ruin. I / prophesy: your / body shall rot / and the princess / shall become a / cold corpse.\"")
t(1354, 180, "The witch left / her words of / curse and / departed.")
t(1354, 181, "Shortly after, / a strange / sickness struck / the kingdom. / Everyone / whispered that / the witch had / cast her curse.")
t(1354, 182, "Belgradno: We / must destroy her / as soon as / possible and / break the curse / on Duhan.")
t(1354, 183, "If you succeed / in bringing the / head of the / witch Aurora, / your reward shall / be anything / you wish.")
t(1354, 184, "Any information / about her is / also welcome. / Anything that / helps defeat her / will be / compensated.")
t(1354, 185, "What do you say? / Will you join / the subjugation / force?")
t(1354, 186, "Join the / subjugation / force? / Yes  No")
t(1354, 187, "Very well. / Prudence is also / a valuable / quality for an / adventurer.")
t(1354, 188, "I won't force / you, but if you / ever feel like / helping Duhan, / please come / anytime.")
t(1354, 189, "I'll be waiting / here.")
t(1354, 190, "Indeed, the speed / of your decision / is an excellent / quality for / a leader.")
t(1354, 191, "Belgradno: Well? / Have you decided / to join the / subjugation / force?")
t(1354, 192, "Or did you come / as an adventurer / just to enjoy / the town's / sights?")
t(1354, 193, "Join the / subjugation / force? / Yes  No")
t(1354, 194, "You've finally / come around.")
t(1354, 195, "I believe that / decision will / bring you / invaluable / experience and / adventure.")
t(1354, 196, "I see, still / thinking it / over. Very well, / take your time.")
t(1354, 197, "Belgradno showed / the documents / bearing the / royal seal to / demonstrate the / extent of the / reward.")
t(1354, 198, "Listed were vast / tracts of land, / tax exemptions, / the right to / build a castle, / to have a / personal army-- / rewards fit for / gaining a whole / kingdom.")
t(1354, 199, "As you might / guess, those / terms were / written by the / king himself.")
t(1354, 200, "No matter how / extravagant, / those terms will / be honored as / long as the / Kingdom of Duhan / exists.")
t(1354, 201, "Belgradno handed / the item wrapped / in dark velvet / to .")
t(1354, 202, "Obtained Identify / Bracelet.")
t(1354, 204, "That bracelet / identifies you / as a member of / the subjugation / force.")
t(1354, 205, "All who enter / the labyrinth / must wear it on / their arm.")
t(1354, 206, "Don't put it in / your bags--keep / it on your arm / at all times.")
t(1354, 207, "Our own soldiers / and many / adventurers are / in the labyrinth / as part of the / force.")
t(1354, 208, "If you're caught / in the labyrinth / without that / bracelet, you / have no grounds / for complaint / if attacked.")
t(1354, 209, " put the / Identify / Bracelet on.")
t(1354, 210, "I regularly go / to the labyrinth / to check on the / other / adventurers.")
t(1354, 211, "Come see me when / you're ready.")
t(1354, 212, "Oh, if you need / healing, visit / the Church of / Salem first.")

# --- Zel scene ---
t(1354, 213, "\"I hear you were / attacked by / bandits.\"")
t(1354, 214, "From within the / mist, a single / figure rose like / a pillar. It was / Zel, leader of / the Order of / Light.")
t(1354, 215, "Zel: I received / word that you / encountered and / were attacked by / bandits on the / 3rd level.")
t(1354, 216, "We rushed there / too, but by then / you'd already / dealt with them.")
t(1354, 218, "Let me be clear: / those bandits / abandoned their / faith and fell / into darkness.")
t(1354, 219, "They have no / connection to us. / Just scum.")
t(1354, 220, "We planned to / deal with them / ourselves / eventually.")
t(1354, 221, "Thank you for / taking care of / it on our / behalf.")
t(1354, 222, "Zel thanked you / briefly, but his / cold expression / betrayed no / emotion.")
t(1354, 223, "I have one more / thing to ask.")
t(1354, 224, "Show me the ring / you found.")
t(1354, 225, "The ring you / should have / received from a / man named Ingo.")
t(1354, 227, "Hmm, this crest / is unmistakably / the princess's.")
t(1354, 228, "Well found. This / will be a clue / to searching for / the princess's / remains.")
t(1354, 229, "Now, go to the / castle.")
t(1354, 230, "The lord will / surely be / pleased.")
t(1354, 231, "Zel's figure / melted into the / mist and / disappeared.")

# --- Arrival in Duhan scenes ---
t(1354, 232, "Dark clouds hung / low and a fog / tinged with / minerals / shrouded the / town.")
t(1354, 233, "Not a soul could / be seen. Even / the wind had / stopped; without / a sound, the / entire town lay / in utter / stillness.")
t(1354, 234, "Upon arriving in / town, what  / saw was not the / city once famed / as the Jewel of / Venoa, a royal / capital brimming / with grandeur.")
t(1354, 235, "It was a bleak, / desolate town / that seemed / devoid of life / and foreboding.")
t(1354, 236, "After gazing / around the town / for a while, / a man's voice / came from beyond / the mist.")
t(1354, 237, "\"Hey, come on, / tell me! You / can't hide it / forever, y'know!\"")
t(1354, 238, "A man approached / unsteadily.")
t(1354, 239, "His hair was / a mess, his beard / unkempt, his / sunken eyes / unfocused, and / his face frozen / in terror.")
t(1354, 240, "Suspicious man: / Heheheh, you / know where God / is hiding, / don't you?")
t(1354, 241, "Come on, tell me! / I have to / deliver that / message, fast!")
t(1354, 242, "Hehe, I know! / I know you're / hiding God's / chosen location!")
t(1354, 243, "You'd better / confess soon, / for your own / good.")
t(1354, 244, "The man gave / a dark smile / and glared.")
t(1354, 245, "Haha, I see! / So you don't / know about THAT, / huh?")
t(1354, 246, "That's why / you're hiding / God's chosen / location! I / figured as much.")
t(1354, 247, "But you see, / I saw it.")
t(1354, 248, "Yeah, they were / right there. / Hiding deep in / the dark.")
t(1354, 249, "And if you just / stand there / spacing out, / they suddenly / attack.")
t(1354, 250, "Hehe, my friends / got chomped right / from the head.")
t(1354, 251, "Munch munch, / chomp. Munch / munch, chomp.")
t(1354, 252, "The man made / exaggerated / biting motions / over and over, / as if playing / around.")
t(1354, 253, "No matter what, / it's useless, / useless, useless!")
t(1354, 254, "Some even begged / for their lives / while crying.")
t(1354, 255, "Hahahaha! / Ahahahaha!")
t(1354, 256, "His hysterical / laughter echoed / throughout the / town.")
t(1354, 257, "The man fell / to his knees, / clutching his / head while / laughing.")
t(1354, 258, "Mad with terror, / tears ran down / his face and / drool dripped / from his mouth, / unnoticed.")
t(1354, 259, "Ahahahaha! / Some even fought / to the death!")
t(1354, 260, "But nooope, / nothing works!")
t(1354, 261, "Seriously, I / think it's / hopeless. Even / God would be / destroyed by / those things.")
t(1354, 263, "\"What are you / doing out there?\"")
t(1354, 264, "A Sister spotted / them from afar / and came running.")
t(1354, 265, "Sister: I looked / everywhere for / you! Sitting out / here like this, / you'll catch / cold!")
t(1354, 266, "Come, your warm / meal is ready. / Let's go eat!")
t(1354, 267, "The man called / Simzon obediently / followed the / Sister's words / and walked off / toward the / church.")
t(1354, 268, "Please don't / blame that man. / He fought for / this town and / ended up like / that.")
t(1354, 269, "I heard he was / once the leader / of a very brave / expeditionary / force.")
t(1354, 270, "But Karman's / Labyrinth / destroyed his / mind.")
t(1354, 271, "Now he wanders / the town every / day, as if / fleeing from / something.")
t(1354, 272, "I don't know / what he saw.")
t(1354, 273, "But it must have / been something / terrible enough / to drive a / strong man to / such madness.")
t(1354, 274, "From what I see, / you appear to be / an adventurer / yourself.")
t(1354, 275, "It must be a / hard profession. / Having to risk / your life to / gain something.")
t(1354, 276, "I pray for your / safety and / well-being.")
t(1354, 277, "Please, do be / careful.")

# --- Second arrival ---
t(1354, 278, "Dark clouds hung / low and a fog / tinged with / minerals / shrouded the / town.")
t(1354, 279, "Not a soul could / be seen. Even / the wind had / stopped; without / a sound, the / entire town lay / in utter / stillness.")
t(1354, 280, "Upon arriving in / town, what  / saw was not the / city once famed / as the Jewel of / Venoa, a royal / capital brimming / with grandeur.")
t(1354, 281, "It was a bleak, / desolate town / that seemed / devoid of life / and foreboding.")
t(1354, 282, "After gazing / around for a / while, voices of / young girls came / from beyond the / mist.")
t(1354, 283, "Girl A: \"A new / person arrived!\" / Girl B: \"What / are they like? / Strong?\" / Girl A: \"Maybe / they'll help?\" / Girl B: \"Let's / go see!\"")
t(1354, 284, "From beyond the / mist came a pair / of elf girls.")
t(1354, 285, "Elf Girl: Hey / hey, you're a new / adventurer, / right?")
t(1354, 286, "I saw you just / now, registering / at the guild!")
t(1354, 287, "Innocent faces; / one brunette, / one blonde, but / from their / features to / their build, / the twin girls / looked alike.")
t(1354, 288, "You're going / to Karman's / Labyrinth too, / aren't you?")
t(1354, 289, "Nobody can leave / this town right / now anyway.")
t(1354, 290, "Sigh...I'm / so worried.")
t(1354, 291, "Ever since the / princess / disappeared, / it's been / nothing but / bad news.")
t(1354, 292, "Monsters in the / labyrinth, the / town blockaded, / and the king is / gravely ill.")
t(1354, 293, "They say it's / all the work of / the witch in the / labyrinth, but / nobody's even / found her yet.")
t(1354, 294, "Basically, / everyone's been / useless.")
t(1354, 295, "What about you?")
t(1354, 296, "Think you can / find her?")
t(1354, 297, "If you manage / to defeat the / witch, there's / an amazing / reward waiting!")
t(1354, 298, "We tried to / divine it. And / the stars told / us:")
t(1354, 299, "Soon, something / will threaten / the very future / of the Kingdom / of Duhan.")
t(1354, 300, "That's why we've / been watching / for new / adventurers.")
t(1354, 301, "And there's one / more important / thing.")
t(1354, 302, "More people are / having a / terrifying dream / recently.")
t(1354, 303, "A really sad / vision! The whole / town engulfed / in darkness, and / everyone / dying.")
t(1354, 304, "We don't know / what it means, / but something / big is coming / soon for sure.")
t(1354, 305, "We're interested / in that too.")
t(1354, 306, "The two lowered / their voices and / began whispering.")
t(1354, 307, "Girl A: \"Hey, / Emilia, we / should go soon.\" / Girl B: \"Right. / They might've / noticed by now.\" / Girl A: \"If we / get caught again / they definitely / won't let us / out for a while!\"")
t(1354, 308, "Well, we've got / something to do, / so we'll say / goodbye! Let's / meet again / somewhere!")
t(1354, 309, "My name is / Emilia.")
t(1354, 310, "I'm Lute. We / both live in the / castle. See you!")
t(1354, 311, "The elf girls / hurried back / into the mist.")

# Build output
output = []
for entry in data:
    key = (entry["resource"], entry["msg_index"])
    eng = tr.get(key, "")
    if not eng:
        # Fallback: mark untranslated
        eng = "[UNTRANSLATED]"
        print(f"WARNING: Missing translation for R{entry['resource']} msg={entry['msg_index']}: {entry['japanese'][:60]}", file=sys.stderr)
    output.append({
        "resource": entry["resource"],
        "msg_index": entry["msg_index"],
        "japanese": entry["japanese"],
        "english": eng
    })

with open('C:/Programmieren/wizardrytranslation/data/type2_translated/batch_09.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

# Count stats
total = len(output)
translated = sum(1 for o in output if o["english"] != "[UNTRANSLATED]")
print(f"Total entries: {total}")
print(f"Translated: {translated}")
print(f"Missing: {total - translated}")
